### ISSUE TITLE
Can we pass real IP from nginx to Recorder?

### ISSUE THREAD

**Issue by jpmens** [owntracks/recorder#100]
This is not a Recorder issue per se; adding here as reminder

**Comment by t-8ch** [comment]
From http://nginx.org/en/docs/http/ngx_http_proxy_module.html
```
proxy_set_header X-Real-IP $remote_addr;
```

**Comment by jpmens** [comment]
I just knew it'd be terrifically hard ... 😆 
thanks, @t-8ch
