### ISSUE TITLE
TLS error occured

### ISSUE THREAD

**Issue by enriquefernandez** [owntracks/recorder#102]
I'm having trouble running the recorder.
I'm running the recorder and the broker in OSX El Capitan.

My mosquitto broker with TLS enabled seems to be working fine, and OwnTracks in iOS is able to connect to it. I'm also able to connect to my mosquitto broker both from the server and from outside the network.

However, the recorder app (running in the same machine as the broker) can't connect.

The recorder shows this message continuously:

```
Mar 21 12:06:01  ot-recorder[25309] <Info>: MQTT connection: rc=8 [A TLS error occurred.] (errno=0; Undefined error: 0). Sleeping...
```

When that happens, the mosquitto broker logs this:

```
1458562011: New connection from 10.0.1.100 on port 8883.
1458562011: OpenSSL Error: error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
1458562011: OpenSSL Error: error:140940E5:SSL routines:ssl3_read_bytes:ssl handshake failure
1458562011: Socket error on client <unknown>, disconnecting.
```

My script to launch recorder is as follows:

```
#: Configuration for Private mode (your own MQTT broker). This requires
#: at least HOST and PORT. If you need TLS, set CAFILE, and for
#: authentication set USER and PASS additionally.

#:-- Private mode
export OTR_HOST="<my-host>"         # MQTT hostname
export OTR_PORT="8883"          # MQTT port (set to 8883 for TLS and define OTR_CAFILE)
export OTR_USER="<my-user>"                       # broker user name
export OTR_PASS="<my-pass>"                     # broker password
export OTR_CAFILE="/Users/efernan/iot/private_config/mosquitto_certificate/ca.crt"              # PEM CA certificate chain for broker

export OTR_STORAGEDIR="/Users/efernan/iot/owntracks/storage"

opts="${opts} --http-host 127.0.0.1 --http-port 8093 --debug"

exec "/usr/local/sbin/ot-recorder" ${opts} "owntracks/#"
```

The certificates were generated with your script.

The following works fine to communicate with the broker from inside the server:

```
mosquitto_sub --cafile ca.crt -h 10.0.1.100 -p 8883 --tls-version tlsv1 -u <my-user> -P <my-pass> -t thetopic
mosquitto_pub  --cafile ca.crt -h 127.0.0.1 -p 8883 --tls-version tlsv1 -m "some messsage" -t thetopic -u <my-user> -P <my-pass>
```

The same works from the outside if I use the right host name and port (I use a different external port that the router maps to 8883).
Also, OwnTracks in iOS is working fine and I'm using the ca.crt there as well.

It seems like the error is related to the protocol of tls.
Can I tell the recorder to use tls version 1? I'm using version 1 because I show somewhere in the OwnTracks documentation that that is needed for some reason.

Any ideas to fix this?

Thank for the help!
I'm amazed by how good all these apps are! Keep up the good work!

**Comment by jpmens** [comment]
It seems to me as though you've configured Mosquitto to use TLSv1 only. Can you please verify that your `mosquitto.conf` does **not** contain a `tls_version` configuration statement? Newer Mosquitto versions will fall back to sane levels and you ought to be able to drop `--tls-version` options from your `mosquitto_sub` client invocations.

**Comment by jpmens** [comment]
> somewhere in the OwnTracks documentation that that is needed for some reason.

If you can point me to where it says that, please; that is certainly no longer correct.

**Comment by jpmens** [comment]
Ignore my last question please: I've found the mention and I've removed the limitation from the Booklet.

**Comment by enriquefernandez** [comment]
My mosquitto.conf definitely had the line `tls_version tlsv1`
I've removed that and it seems like everything works great now!

By the way, I think an old entry in your blog also references tlsv1.

Thanks!

**Comment by jpmens** [comment]
Good to hear.

(I don't typically go back to update old blog posts, which is why they have dates on them :-)
