### ISSUE TITLE
Recorder not saving addresses

### ISSUE THREAD

**Issue by enriquefernandez** [owntracks/recorder#105]
I think something's going on with the addresses in my recorder installation.

When I run the ocat command `ocat --last --user user --device iphone`, I get most of what I expect including correct lat/lot, times, etc.

However, I do not get the 'addr' field as the README.md documentation suggests I should.
I do get, however, a 'ghash' field with some key value that I assume is a mapping from my location to an actual address.

My recorder error log file is full of these messages

```
Mar 23 01:55:15  ot-recorder[481] <Error>: gcache_json_get: mdb_txn_begin: (-30783) MDB_BAD_RSLOT: Invalid reuse of reader locktable slot
```

If I scroll higher up in the error log, there are a lot of the following messages (but it looks like these are no longer being generated)

```
Mar 22 08:44:29  ot-recorder[481] <Error>: gcache_json_get: mdb_txn_begin: (22) Invalid argument
Mar 22 08:44:29  ot-recorder[481] <Error>: gcache_put: mdb_txn_begin: Invalid argument
```

In the standard output log I do see some addresses being resolved properly, but I don't know if they are being stored anywhere.

It seems like something is wrong with the LMDB database? Maybe some permissions issue?

The folder storage/ghash has files data.mdb and lock.mdb.
I'm running everything on a mac mini in OSX El Capitan.

Thanks!

**Comment by jpmens** [comment]
There are two things you should please do after stopping `ot-recorder`:

1. remove the `lock.mdb` file
2. start the Recorder once with the `--storage` option you use **and** the `--initialize` option: this sets up the named databases and it is non-destructive.

Then relaunch as normal.

You can check the content of the address database with an `ocat --dump`. Those geohashes you've seen are the keys to the JSON within the address cache in LMDB. If the Recorder can successfully obtain a reverse-geo lookup it caches the result as JSON keyed by the geohash.

**Comment by enriquefernandez** [comment]
I think this fixed it. Thanks!
I think the original problem was some confusion with privileges (I had run ot-recorder as root and also as my user).

**Comment by jpmens** [comment]
Yes, that would break things. This, by the way, is why for the Linux packages I decided to have both `ot-recorder` and `ocat` run setuid as `owntracks` -- in order to avoid this kind of problem. Running suid has been very good (even if one person bitterly complained about it offline to me ;-) 

Please ensure that `ot-recorder` can write to its files (and create directories within the STORAGE), and that `ocat` can at least read the files and LMDB database. (In case you ever use `ocat --load`, which you don't typically need), it too would need to be able to write to LMDB in the `ghash/` store.

**Comment by enriquefernandez** [comment]
I finally set it up as my own user. Running it as 'owntracks' user sounds like a good idea, but I feel lazy about adding additional users in my remote computer right now.. :)

You can definitely mark this issue as closed, as I think that this issue happened as a result of me running it as root and as user.

Completely off topic, but now that we're talking: is it possible to get events out from ocat? (enter, leave events for example). I don't seem to find an easy way to do that looking at the documentation.

Thanks!

**Comment by jpmens** [comment]
Good that you solved it, and thanks for the feedback.

No, we can't extract events with ocat. Do me a favor please: create a new issue and tell me what data you'd like to be able to get.
