### ISSUE TITLE
Export events using ocat

### ISSUE THREAD

**Issue by enriquefernandez** [owntracks/recorder#106]
If recorder logs events, it'd be great to be able to export them using ocat.

A use case would be using this information for computing your average commuting time, for example (event leave home to even enter office).

**Comment by jpmens** [comment]
As a short-term, quick and dirty workaround, you can easily obtain the JSON from these events directly from the `.rec` file:

```bash
grep "Z\tevent " $STORAGE/rec/user/device/2016-03.rec | sed -e 's/^.*{/{/'
```

**Comment by enriquefernandez** [comment]
Awesome.
Thanks!

**Comment by jpmens** [comment]
I have decided we won't do this at the moment because it's easy to obtain the data as shown above. We _might_ revisit at some future point.
