### ISSUE TITLE
Install on Ubuntu 14 - input in flex scanner failed

### ISSUE THREAD

**Issue by jimiz12** [owntracks/recorder#112]
I have installed and when running ot-recorder --initialize  i am receiving "input in flex scanner failed"

any suggestions

**Comment by jpmens** [comment]
I have no idea what that means, to be honest. How did you install (directly from repo, package, and if so from which source)?

Nowhere in our source does it say that ...

**Comment by jimiz12** [comment]
Thx for fast reply. I did a pull from source zip 0.6.2

I will pull log file in a few

**Comment by jimiz12** [comment]
Here is the app being run 
user@ubuntuhome:/var/www/html$ cd ~/install/recorder-0.6.2/
user@ubuntuhome:~/install/recorder-0.6.2$ ot-recorder 
input in flex scanner failed

I re-ran the make install
user@ubuntuhome:~/install/recorder-0.6.2$ sudo make install
mkdir -p /usr/local/bin
mkdir -p /usr/local/sbin
mkdir -p /var/spool/owntracks/recorder/htdocs
mkdir -p /var/spool/owntracks/recorder/store/last
cp -R docroot/* /var/spool/owntracks/recorder/htdocs/
install -m 0755 ot-recorder /usr/local/sbin
install -m 0755 ocat /usr/local/bin
test -r //etc/defaults/ot-recorder || install -D -m 640 etc/ot-recorder.default //etc/defaults/ot-recorder
/usr/local/sbin/ot-recorder --initialize
input in flex scanner failed
make: *** [install] Error 2

**Comment by jimiz12** [comment]
Closing issue.  restored snapshot of virtual and re-ran setup.   Issue not longer happens.  Must have been something that was introduced as I added to the Virtual.  New Ubuntu 14 virtual is up and running.

Thank you
