### ISSUE TITLE
Provide public key for repositories in a secure location

### ISSUE THREAD

**Issue by t-8ch** [owntracks/recorder#113]
Currently the gpg key for the repositories are only available from the repository server itself which is served over plain HTTP.
It would be nice to get the signing key over an authenticated channel.

Ideas:
* Server the repository itself over HTTPS, then we can also get the pubkey from there
* Add the pubkeys to the git repository on GitHub
* Provide long digest fingerprints of the pubkeys in the repo

**Comment by jpmens** [comment]
Valid point. I'm taking the simplest way out for the time being and I'm adding the public key block to `etc/repo.owntracks.org.gpg.key` in this repository.
