### ISSUE TITLE
reverse geo info doesn't work anymore

### ISSUE THREAD

**Issue by janvonde** [owntracks/recorder#115]
Hi, I compiled ot-recorder from source and I am getting the following error now when I try to get the addr via the api/0/ endpoint:
>ot-recorder[25310]: gcache_json_get: mdb_txn_begin: (-30783) MDB_BAD_RSLOT: Invalid reuse of reader locktable slot

did I miss anything here or is it broken?

**Comment by binarybucks** [comment]
We're also experiencing geocoder issues in the Android app. As both are
using the same API, it could be that the Google API endpoint is
experiencing some issues.

Mit freundlichen Grüßen / With kind regards
Alexander Rust

On 03 Apr 2016, at 23:03, Jan Vonde <notifications@github.com> wrote:

Hi, I compiled ot-recorder from source and I am getting the following error
now when I try to get the addr via the api/0/ endpoint:

ot-recorder[25310]: gcache_json_get: mdb_txn_begin: (-30783) MDB_BAD_RSLOT:
Invalid reuse of reader locktable slot

did I miss anything here or is it broken?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/recorder/issues/115>

**Comment by janvonde** [comment]
Problems in the App are fixed for me now. Problems in the recorder persist. I did a fairly big Version Update btw...

**Comment by jpmens** [comment]
@janvonde please stop the recorder and remove the `lock` file from `STORAGEDIR/ghash/`. Launch Recorder once with your storage directory and `--initialize`, then restart as usual; that should solve it.

**Comment by janvonde** [comment]
@jpmens that fixed it. thanks.

I have a second problem with the recorder not recording the positions anymore. I can publish the location via mqtt and see the correct location in the webinterface but it is not storing the information. Do you want me to create another ticket for this or can we continue here?

**Comment by jpmens** [comment]
Do you see the publish on the Recorder's _stdout_ ?

**Comment by janvonde** [comment]
No. I have the following:

> ✓  root@service01 /opt/owntracks/recorder master $ ./ot-recorder --http-host 10.10.1.30 --doc-root /opt/owntracks/recorder/docroot/ --lua-script /tmp/ot-test.lua 'owntracks/#'
> ot-recorder[31256]: version 0.6.2 starting with STORAGEDIR=/var/spool/owntracks/recorder/store
> ot-recorder[31256]: initializing Lua hooks from `/tmp/ot-test.lua'
> ot-recorder[31256]: recorder lua hooks starting
> ot-recorder[31256]: HTTP listener started on 10.10.1.30:8083
> ot-recorder[31256]: Using storage at /var/spool/owntracks/recorder/store with precision 8

I was pretty sure, that I was able to see a successful connection log message in the mosquitto.log file but I can not see it currently... What I saw was probably this line:
> 1459752263: New connection from 127.0.0.1 on port 1883.

But I didn't read the one after that and misinterpreted an icinga2 check...:
> 1459752263: New client connected from 127.0.0.1 as check-mqtt-12853 (c1, k60).

Is the README still up to date? I tried to start ot-recorder with the --host option but it told me "unrecognized option '--host'"

**Comment by jpmens** [comment]
The README is up to date (and if it isn't it's a bug).
As you have already noticed, the Recorder isn't connecting to your MQTT broker. Please use either `--host` and `--port` or `$OTR_HOST`, `$OTR_PORT` or the configuration file.

`--host` works here.

**Comment by jpmens** [comment]
BTW, did you compile without support for MQTT? :laughing:

**Comment by janvonde** [comment]
Well ......

..............

Shame on me!!

... 

I have no idea how that could happen, the config.mk looked good and the only options I changed were
> WITH_LUA ?= yes
> LUA_CFLAGS = `pkg-config --cflags lua5.2`
> LUA_LIBS   = `pkg-config --libs lua5.2`

I did a rm config.mk && cp config.mk.in config.mk, edited it again, recompiled and it is working now. Sorry for that, I have no idea how this stupid error could happen ... I should cycle to work now  ..... :sunglasses:
