### ISSUE TITLE
the howto inside the sandstorm package seems outdated

### ISSUE THREAD

**Issue by ovizii** [owntracks/recorder#118]
on android it says: click the i in the top left and enter the info but there is no i so I assume I need to go to preferences, select private instead of public and then? I see fields for server, port, etc, etc.

**Comment by jpmens** [comment]
1. what is a `davros` package?
2. show us a screenshot please (the (I) typically refers to iOS

**Comment by jpmens** [comment]
3. what does this have to do with the Recorder?

**Comment by ovizii** [comment]
Sorry, my bad. Had not yet finished my first coffee :-( 

I will try and correct the title of my post and edit this whole issue. give me a minute please.

**Comment by ovizii** [comment]
So, I installed the sandstorm package onto my own sandstorm instance from here: https://apps.sandstorm.io/app/cjv3p2a970vrm729x9x0v54k0nff6x6s2xcgwvgpuzhgk56wum5h

The instructions: https://db.tt/HwPcJGDk 

But after installing the owntracks android app, those instructions aren't helpful as there is no single field to enter this info or am I missing something?

**Comment by binarybucks** [comment]
The sandstorm app is not maintained nor supported by us. If their documentation isn't correct, they should probably update it ;)

**Comment by ovizii** [comment]
Hi there,

I just double checked and their app does indeed link to their own github page, no idea how I landed here, lets say its the Monday morning blues :-( 

Sorry for the confusion.
