### ISSUE TITLE
Debian Jessie distro missing binary-armhf 

### ISSUE THREAD

**Issue by jhedup** [owntracks/recorder#122]
http://repo.owntracks.org/debian/dists/jessie/main/  lists binary-amd64/ but the repo should include binary-armhf/ for the raspberry pi please.

**Comment by jhedup** [comment]
This is the problem with 'sudo apt-get update':

W: Failed to fetch http://repo.owntracks.org/debian/dists/jessie/InRelease  Unable to find expected entry 'main/binary-armhf/Packages' in Release file (Wrong sources.list entry or malformed file)

**Comment by jpmens** [comment]
@jhedup So, I think we now have this ... Would you kindly test?

**Comment by jpmens** [comment]
It's been confirmed to me that the package works.

**Comment by jhedup** [comment]
Thank you so much, I will only be home to see for myself. 

Sent from my iPhone

On 20 Jul 2016, at 05:29, JP Mens <notifications@github.com> wrote:

Closed #122.
