### ISSUE TITLE
NoApiKeys and MissingKeyMapError errors on map pages

### ISSUE THREAD

**Issue by philipsd6** [owntracks/recorder#124]
I've setup `ot-recorder` behind `nginx` according to the docs, but when I access map pages, the map fails to load, and leaves an "Oops! Something went wrong. This page didn't load Google Maps correctly. See the JavaScript console for technical details." message.

The javascript console displays `NoApiKeys` and `MissingKeyMapError` errors.

When I load `ot-recorder` directly on 127.0.0.1:8083, the javascript console displays just the `NoApiKeys` error, but it still loads the map. 

Here's the relevant section in my nginx config for OwnTracks:
```
    # Proxy and upgrade Websocket connection
    location /owntracks/ws {
        auth_basic "OwnTracks";
        auth_basic_user_file /local/secrets/htpasswd;
        rewrite ^/owntracks/(.*)  /$1 break;
        proxy_pass          http://127.0.0.1:8083;
        proxy_http_version  1.1;
        proxy_set_header    Upgrade $http_upgrade;
        proxy_set_header    Connection "upgrade";
        proxy_set_header    Host $host;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header    X-Real-IP $remote_addr;
    }

    location /owntracks/ {
        auth_basic "OwnTracks";
        auth_basic_user_file /local/secrets/htpasswd;
        proxy_pass          http://127.0.0.1:8083/;
        proxy_http_version  1.1;
        proxy_set_header    Host $host;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header    X-Real-IP $remote_addr;
    }
```

This happens whether or not I use the `--geokey` parameter for `ot-recorder`.

**Comment by jpmens** [comment]
> displays NoApiKeys and MissingKeyMapError errors.

errors or _warnings_?

> "Oops! Something went wrong"

We do this permanently behind nginx as described; I've never seen this error. Might it be something temporary issued by Google (it's not in our code)?

**Comment by philipsd6** [comment]
Well I'll clarify &mdash; the NoApiKeys is a warning, but MissingKeyMapError is an *error*. The live map loads, but then disappears and I'm left with:

![image](https://cloud.githubusercontent.com/assets/908201/16363983/4ec62656-3bdc-11e6-98ad-3fe08cec4aa3.png)

Per this [recent announcement](http://googlegeodevelopers.blogspot.de/2016/06/building-for-scale-updates-to-google.html):

> We no longer support keyless access&hellip; [for] Maps API implementations created on or after June 22nd, 2016

However, they've grandfathered in existing applications based on their current usage, which is probably why *you've* never seen this error (yet!)

**Comment by philipsd6** [comment]
FWIW, I updated the html files to change this:
```html
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true"></script>
```
into this:
```html
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true&key=BROWSER_KEY"></script>
```

After which it works via the nginx reverse proxy; however, it then fails when accessed as `localhost` with a `RefererNotAllowedMapError` error because `localhost` isn't in the list of approved referrers.

I'm not sure how best to manage this dynamically, so I leave it up to you.

**Comment by jpmens** [comment]
Thank you for trying that. Am I right that `BROWSER_KEY` is the API key you got from google?

**Comment by philipsd6** [comment]
Yes, I'm using a server key for the `--geokey` parameter, but a browser key is required for the script load. I had to enable the Google Maps JavaScript API for my project for that to work as well.

**Comment by kabili207** [comment]
Based on this error that ot-recorder ouputs to the console whenever a location updated is received, you shouldn't have a referrer configured.
```
revgeo: REQUEST_DENIED ({
   "error_message" : "Browser API keys cannot have referer restrictions when used with this API.",
   "results" : [],
   "status" : "REQUEST_DENIED"
}
)
```

**Comment by juankymoral** [comment]
Adding BROWSER_KEY in html files worked for me too ;)

**Comment by jpmens** [comment]
So this has been more difficult (for me) than expected. I have just now pushed a patch which dynamically adds a browser API key to the Google maps URL. (The main difficultly [for me] was getting the websocket connection to then actually succeed).

Would anybody care to try this out? (Rebuilding Recorder is **not necessary**) It is implemented for the `last/` URL in the Recorder, i.e. the live map. The code currently expects a file `<docroot>/last/apikey.js` which looks like this:

```js
var apiKey = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
```

**Comment by jpmens** [comment]
If this works for you, we'll then implement the same for the other maps. I would like some thoughts as to where/how we should hand over the browser api key. The following ideas come to mind:

1. Provide the key from a static `apikey.js` file which users would have to create
2. Add an option to `ot-recorder` to pass this additional key. From that, `ot-recorder` could intercept a request to URLs ending in `apikey.js` and build that on the fly.

Number 1 is easiest of course, but number 2 better matches how we currently handle the server api key.

**Comment by jpmens** [comment]
We've had confirmation that this is working.
