### ISSUE TITLE
locations API request produces no data on FreeBSD

### ISSUE THREAD

**Issue by jpmens** [owntracks/recorder#125]
I confirm [the issue reported here](https://community.owntracks.org/topic/125/ocat-ot-recorder-web-interface-not-showing-tracks-points/20), at least on FreeBSD 10.2 (using `clang` and `pkg install lmdb mosquitto`)

Other API invocations (e.g. `version`, `list`, `last`) work.

**Comment by jpmens** [comment]
Compiling with _clang_:

```
secs = mktime(&tmline);
printf("lo=%ld secs=%ld hi=%ld\n", s_lo, secs, s_hi);
lo=1452189180 secs=-1 hi=1468861402
```

Compiling with _gcc_:

```
lo=1452189180 secs=1468548495 hi=1468861444
```

So, _clang_ is causing `candidate_line()` to fail because not between `s_lo` and `s_hi`

**Comment by yggdr** [comment]
I was about to open an issue about it not compiling here on FreeBSD 10.3 when I saw this. For me, gmake errors out with

    cc   -c mdb.c
    mdb.c:4835:39: error: use of undeclared identifier 'O_DSYNC'
                        env->me_mfd = open(dpath, oflags | MDB_DSYNC, mode);
                                                           ^
    mdb.c:432:20: note: expanded from macro 'MDB_DSYNC'
    # define MDB_DSYNC      O_DSYNC
                        ^
    mdb.c:9678:46: warning: data argument not used by format string [-Wformat-extra-args]
                                (int)mr[i].mr_pid, (size_t)mr[i].mr_tid, txnid);


How do you get it to compile in the first place?

**Comment by jpmens** [comment]
@yggdr please install lmdb from ports:

```
cd /usr/ports/database*/lmdb
make install
```

Then, in Makefile:

```
LIBS += -llmdb -lpthread
#TARGETS += mdb/liblmdb.a
```

**Comment by yggdr** [comment]
Thank you.
I just saw the section in the config.mk for FreeBSD that I overlooked somehow. After uncommenting them I now get a linker error
    /usr/bin/ld: cannot find -lcurl

curl is installed, a separate libcurl pacakge doesn't exist. A curl.h can be found in /usr/local/include/curl/curl.h, but I cannot get ld to recognize it.

**Comment by jpmens** [comment]
Add `-I /usr/local/include` to CFLAGS and `-L /usr/local/lib` to LIBS

**Comment by yggdr** [comment]
CFLAGS already contains that, and there is a MORELIBS variable having the /usr/local/lib. Even after adding this to the LIBS variable the linker error persists

**Comment by jpmens** [comment]
If you have `/usr/local/lib/libcurl.a` and linker doesn't find it, there's something wrong with `-L` in invocation: please ensure you see -L/usr/local/lib during the _make_ phase.

**Comment by yggdr** [comment]
Thank you very much for those pointers.
I had to edit the Makefile and add -L/usr/local/lib to LIBS there, even though it should take if from the MORELIBS variable from the included config.mk. Very strange. But now I have a runable binary :)

**Comment by jpmens** [comment]
@yggdr sorry about that; `MORELIBS` was being reset further down in `config.mk`; that is now fixed.

**Comment by yggdr** [comment]
Hi again,

just reinstalled my main machines and wanted to play around with this once more. Running on FreeNAS 9.10 (builds on top of FreeBSD 10.3) I snatched the current 0.6.8 tarball, unpacked, copied config.mk.in to config.mk, uncommented the FreeBSD section at the top: same error as in my first post.
Following you advises here doesn't yield any difference, I can't seem to get it to compile.
lmdb, curl, and libconfig are installed, mucking around with the LIBS variable in Makefile doesn't seem to change anything.

**Comment by jpmens** [comment]
What does "can't seem to get it to compile" mean? What errors do you get?

**Comment by yggdr** [comment]
I'm sorry I didn't make this clear: it's the same error I already posted, see my post third from top, about undefined O_DSYNC.

**Comment by jpmens** [comment]
And you're sure you followed instructions in `config.mk` (after copying from `config.mk.in`): 

```
# Uncomment the following for FreeBSD; this assumes:
#
#       cd /usr/ports/databases/lmdb; make config; make install clean
#       cd /usr/ports/ftp/curl; make config; make install clean
#       cd /usr/ports/devel/libconfig; make config; make install clean
#
# CC      = clang
# CFLAGS += -I/usr/local/include
# MORELIBS += -L /usr/local/lib
# -- end FreeBSD
```

obviously then uncommentind the the lines CC, CFLAGS, MORELIBS?

**Comment by jpmens** [comment]
To clarify: you did say you did, it's just I can't reproduce the issue

**Comment by yggdr** [comment]
Yes, very sure.
I just extracted a fresh copy from 0.6.8.tar.gz, copied the config.mk again, uncommented the three lines pertaining to FreeBSD, and additionally added a -v flag to the CC=clang variable.
Calling gmake results in the attached error.

[GMAKE_FAIL.txt](https://github.com/owntracks/recorder/files/583321/GMAKE_FAIL.txt)

**Comment by jpmens** [comment]
I think the issue is in the `Makefile` (the last line of your compilation phase -- thanks for that!) shows the locally built `mdb/liblmdb.a` is to be linked in, but we don't have that as you've installed mdb from packages (correctly so)

Please edit `Makefile`d, line 23 and change

```
LIBS += mdb/liblmdb.a -lpthread
TARGETS += mdb/liblmdb.a
```

to

```
LIBS += -lpthread
TARGETS += 
```

**Comment by yggdr** [comment]
Oh, that's the same fix you proposed in your original response to me! Sorry, I thought that had been merged, I didn't realise it was still necessary. Ok, I changed the Makefile, but it needs a -llmdb in LIBS, like in your original post. Then it compiles! Thanks very much (again).

Is it possible to change the config.mk and Makefile to just use a variable "FreeBSD", which you can set in config.mk in one line (or give on the command line to gmake), then takes care of all these changes? I know only little about writing make files, else I would propose a diff.

**Comment by jpmens** [comment]
Yes, @yggdr, I should really do this -- I've opened an issue for it.
