### ISSUE TITLE
Compiler error: Maybe uninitialized variable

### ISSUE THREAD

**Issue by avanc** [owntracks/recorder#128]
While compiling the recorder under Arch Linux, it fails with the following error using gcc 6.1.1:

    base64.c: In function ‘base64_decode’:
    base64.c:116:41: error: ‘n[3]’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
      *data_len = q-data - (n[2]==-1) - (n[3]==-1);
                                        ~~~~~^~~~~
    base64.c:116:28: error: ‘n[2]’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
      *data_len = q-data - (n[2]==-1) - (n[3]==-1);
                           ~~~~~^~~~~
    cc1: all warnings being treated as errors
    make: *** [<builtin>: base64.o] Error 1

**Comment by jpmens** [comment]
You ought to be able to work around this by temporatily removing -Werror
from the compilation flags.

**Comment by avanc** [comment]
Thanks for the hint. I ignored the error using -Wno-maybe-uninitialized.
In addition, it fails with errro _unused result_ which I ignore using -Wno-unused-result
