### ISSUE TITLE
Allow changing web map provider to OpenStreetMap

### ISSUE THREAD

**Issue by strugee** [owntracks/recorder#129]
The admin should be allowed to use OpenStreetMap instead of Google Maps in the web view.

**Comment by strugee** [comment]
https://wiki.openstreetmap.org/wiki/Deploying_your_own_Slippy_Map has information on embedding OSM maps

**Comment by jpmens** [comment]
Unsure whether we'll go to the trouble of implementing this and #130, but I'd accept a pull-request which does so.

**Comment by strugee** [comment]
Noted, thanks.

**Comment by jpmens** [comment]
I'm closing this now, but will still accept a pull-request which implements this. :-)
