### ISSUE TITLE
Allow doing reverse geo lookups with OpenStreetMap

### ISSUE THREAD

**Issue by strugee** [owntracks/recorder#130]
I'd prefer not to leak all my reverse geo lookups to Google. Not sure if an OSM-backed reverse lookup API exists, but if so, the admin should be able to use that instead of Google, if they so desire.

**Comment by strugee** [comment]
Looks like this might do the trick: https://wiki.openstreetmap.org/wiki/Nominatim#Reverse_Geocoding

Although it's unclear to me whether it would be acceptable use or not.

**Comment by jpmens** [comment]
Follow-up in #149
