### ISSUE TITLE
Warn if the configuration file or CA file isn't readable

### ISSUE THREAD

**Issue by strugee** [owntracks/recorder#131]
I spent a long time trying to figure out why my configuration wasn't taking effect, only to finally realize that my config file wasn't readable by the user I was running `ot-recorder` as.

I would've saved a lot of time if the program had warned me that it couldn't read its configuration. Ditto for the CA file.

**Comment by jpmens** [comment]
Log for CA file was in the code; log for `defaults` configuration file added.
