### ISSUE TITLE
timestamp api doesn't use date from gps.

### ISSUE THREAD

**Issue by matbor** [owntracks/recorder#133]
@jpmens as discussed and confirm by you.
## 

Scenario - If I use a GPS offline for a few days/weeks and then upload ALL that data and at the time of uploading we have rolled into the next month, that information gets recorded in the current months .rec file with the time stamp in the first column of the day it is logged. 

Now when using the recorder api and displaying data on a map via the api it doesn't use the date from the GPS data, it uses the date of when the data was recorder. (see screenshot below of the .rec file) which can be an issue if the gps data is from a different timeframe.

In the picture below you can see the date of when the data was uploaded and the data from the GPS was timestamp is for an older date, which is correct.

![image 1](https://cloud.githubusercontent.com/assets/1978503/17688885/93f33536-63c6-11e6-8901-6cf174441a76.png)

Matt.

**Comment by jpmens** [comment]
What we should probably do is to use `tst` from the location report instead of `now`

**Comment by binarybucks** [comment]
Would also fix some order issues when the Android client has to requeue messages.

**Comment by jpmens** [comment]
What will not change short-notice is that we append to the `.rec` files as the messages trickle in. So, messages arriving at 10, 11, 10 will be stored in that order, irrespective where we get the timestamp from.

**Comment by jpmens** [comment]
@matbor this has now been packaged as 0.6.9 for Debian/Raspbian/CentOS and is available in our package repository. I would appreciate you testing it.

**Comment by matbor** [comment]
@jpmens thx, will see how I go on the weekend.
