### ISSUE TITLE
Allow specifying Google Maps browser API key in configuration

### ISSUE THREAD

**Issue by strugee** [owntracks/recorder#146]
I've installed Recorder from the Debian repo, and thus my docroot is `/usr/share/owntracks/recorder/htdocs`. I'd really rather avoid touching anything in `/usr` (especially since it'll probably get blown away when I upgrade Recorder, so the README's instructions to copy `$docroot/static/apikey.js.sample` to `$docroot/static/apikey.js` are unideal.

I should be able to specify the API key in the usual configuration places.

Refiling #132 as that one got off-topic.

**Comment by jpmens** [comment]
While I fully agree that editing a static file in `/usr` is meh (I did it on the spur of the moment, expecting somebody would complain ...), I have no idea at the moment how we should go about implementing this.  I think what we're going to have to do is parse the HTML files looking for an `@@APIKEY@@` token or something and replace that on-the-fly, similarly to how we do that in our _views_.

**Comment by jpmens** [comment]
@strugee `ot-recorder --browser-apikey xxxx` should now do the trick: the Recorder catches requests to and then constructs/serves `apikey.js`.

I've implemented this as an option, but we can easily put this in the `defaults` configuration if you think it should be there.

**Comment by strugee** [comment]
Seems better in the configuration file, but this is already way way better. Thanks :)

**Comment by jpmens** [comment]
No worries: I wrote the code in the train this evening and will push as soon as I have connectivity.

(Possibly off topic: have you ever been in a hotel without wifi? No, I didn't think so.)
