### ISSUE TITLE
How do you delete/forget devices?

### ISSUE THREAD

**Issue by travisghansen** [owntracks/recorder#147]
During testing I've had several different test devices I'd like to remove all traces of.  What's the best way to approach that?

Thanks!

**Comment by jpmens** [comment]
In Recorder, change to your configured _store_ directory and remove the corresponding `.rec` files and their containing directories. Alternatively, you can do this via the HTTP API using the `kill` command (if it's been compiled in).

**Comment by travisghansen** [comment]
```kill``` command doesn't seem to work

```
curl http://127.0.0.1:8083/api/0/kill -d user=thansen -d device=htcm8wl
no comprendo
```
```
curl "http://127.0.0.1:8083/api/0/kill?user=thansen&device=htcm8wl"
no comprendo
```

Am I doing that wrong?

**Comment by jpmens** [comment]
If it's been compiled in means if you built it with `WITH_KILL ?= yes`
Alternatively, just remove the files and you'll be done with it.

**Comment by travisghansen** [comment]
Ah I'm running in the docker image..is it not in there?  I can delete for sure just want to make sure I'm not doing something incorrectly.

**Comment by jpmens** [comment]
Ah, `kill` is not in the Docker image.
Just delete the `.rec` files, making sure you delete the ones you really no longer want/need.
