### ISSUE TITLE
Default Autozoom for LIVE Map

### ISSUE THREAD

**Issue by travisghansen** [owntracks/recorder#148]
Is it possible to have the live map default to autozoom?

Also, is it possible to have the popover visible for all devices by default?  I currently have 1 point with the popover visible without manually clicking on each point.  I'm unsure what the logic is about which is chose on page load.  In my case the device with the _oldest_ checkin.

Thanks!

**Comment by jpmens** [comment]
Both these enhancement requests would be possible to implement. The reason we don't show the popover for all devices is we have maps with > 50 devices on them; you can imagine the ensuing clutter ;)

The "logic" for the topic with the visible popover is "the last message received from the broker upon connecting".

**Comment by travisghansen** [comment]
@jpmens ok, might be viable to have as a configuration option.  Additionally, I seem to recall reading somewhere in the documentation about placing user images somewhere.  If those are in place is the 'red dot' replaced with the image?

**Comment by jpmens** [comment]
No, the red dot on the map stays. The image is bled into the popup overlay when a new location is posted on the live map.

**Comment by travisghansen** [comment]
Based on everything I've learned I think ideal for me would be (for the live reload map):

 * autozoom by default
 * user images instead of red dots
 * info box never pops up automatically (but can if manually clicked)

Essentially just a bunch of faces moving around without any other clutter.

**Comment by stefaanbolle** [comment]
Is it possible to change the default zoom level?
When loading last view I see whole Europe

**Comment by fab33** [comment]
It will be fine if we can have autozoom and user images instead red dots

**Comment by travisghansen** [comment]
With no bubbles by default too :)

**Comment by jpmens** [comment]
Closing as stale.
