### ISSUE TITLE
Allow for a Lua function to populate "reverse-Geo" lookups (ghash table)

### ISSUE THREAD

**Issue by jpmens** [owntracks/recorder#149]
We currently use Google for reverse geo lookups, and this is fine for most people (except those who'd prefer Nominatim). We also use Recorder [for other things](https://community.owntracks.org/topic/220/importing-airplane-locations-into-owntracks-with-dump1090) though, and here reverse lookups to populate the location field are possibly not suitable.

We could add a feature in which the Recorder checks if the JSON location payload has a `_lua` key in it. If so, it'd be the name of a Lua _hook_ which is given the full payload as a table and would return the string with which to populate the `ghash` lmdb table, thus allowing completely foreign texts, such as _flight number / destination_ for the above example.

Abstracting slightly further, there'd be a default Lua hook which is invoked if no `_lua` key is in the payload, allowing people to plug in their preferred reverse-geo lookup source.

**Comment by vielmetti** [comment]
Indeed! And I'd say if that if you're tracking airplanes with Recorder, you should run with `--norevgeo` enabled, because otherwise you quickly get the OVER_QUERY_LIMIT error from Google:

```
   "error_message" : "You have exceeded your daily request quota for this API. We recommend registering for a key at the Google Developers Console: https://console.developers.google.com/apis/credentials?project=_",
```

**Comment by jpmens** [comment]
Note that our plane tracker adds _geoprec to payloads.

**Comment by jpmens** [comment]
Documented [here](https://github.com/owntracks/recorder/blob/master/doc/HOOKS.md#otr_revgeo)
