### ISSUE TITLE
missing libsodium13 package

### ISSUE THREAD

**Issue by travisghansen** [owntracks/recorder#152]
Trying to update in the docker image produces:
```
root@69846445121b:/# apt-get install ot-recorder
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ot-recorder : Depends: libsodium13 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by jpmens** [comment]
I tried updating the Docker image on docker hub; got stuck at precisely that and spent almost two (2!) hours trying to solve but failed. I don't know what it is or how to solve it, at least not at the moment.

**Comment by travisghansen** [comment]
Well they have libsodium18 I believe.  Not sure if the change affects recorder at all though.

**Comment by jpmens** [comment]
Thanks to @juzam we now have updated Docker images on docker hub after switching to Debian.

**Comment by travisghansen** [comment]
Great! I'll try it out and report any issues.
