### ISSUE TITLE
Docker image to install recorder. Publish got Denied

### ISSUE THREAD

**Issue by howardweng** [owntracks/recorder#155]
I use Docker engine to install recorder image. But when I try to login MQTT coming with Recorder, and I always got "Denied PUBLISH" message, I also tried the same way to install MQTT Mosquitto only, and it works fine. I am not sure if I missed anything. Can anyone help?

I use the image of owntracks/recorderd:latest

Here is my log file. 
2016-10-11T10:08:49.039390898Z 1476180529: Denied PUBLISH from macid (d0, q0, r0, m0, 'owntracks/howard', ... (157 bytes))
2016-10-11T10:08:49.254126202Z 1476180529: Denied PUBLISH from macid (d0, q0, r0, m0, 'owntracks/howard', ... (157 bytes))
2016-10-11T10:08:49.454499862Z 1476180529: Denied PUBLISH from macid (d0, q0, r0, m0, 'owntracks/howard', ... (157 bytes))
2016-10-11T10:08:49.630997483Z 1476180529: Denied PUBLISH from macid (d0, q0, r0, m0, 'owntracks/howard', ... (157 bytes))

**Comment by jpmens** [comment]
You'll have to give more details and show me your configuration. Also, the topic doesn't look right: it should be `owntracks/<username>/<devicename>`

**Comment by howardweng** [comment]
Thanks sir for your reply

I used the Docker Image, and I rechecked the topic, and it should be corrected as following, but the problem remained. 

The setting and MQTT FX setting as attached, hope you can enlighten me. 

JPG 01 ---> It shows docker image setting, and it runs. 
JPG02 ---> you can see the Web pages is correctly displayed. 
JPG03 --->MQTT FX topic and Publish interface, Green shows it connected MQTT broker correctly. 
JPG04 ---> it shows my setting to broker. 

Can you help?


------------Log-------

![01](https://cloud.githubusercontent.com/assets/19993172/19483167/053f7830-9586-11e6-819e-23cef569fbbd.jpg)
![02](https://cloud.githubusercontent.com/assets/19993172/19483166/053b7140-9586-11e6-9133-b4f82eb16472.jpg)
![03](https://cloud.githubusercontent.com/assets/19993172/19483168/05405cc8-9586-11e6-9b0b-54e65eafc150.jpg)
![04](https://cloud.githubusercontent.com/assets/19993172/19483165/053a82c6-9586-11e6-91a1-f1279aa24e37.jpg)




recorderd-5bea4898-1 | 2016-10-18T14:42:49.875193574Z ......................................................+++
recorderd-5bea4898-1 | 2016-10-18T14:42:49.875803727Z e is 65537 (0x10001)
recorderd-5bea4898-1 | 2016-10-18T14:42:49.901663608Z /usr/local/sbin/generate-CA.sh: line 94: /sbin/ifconfig: No such file or directory
recorderd-5bea4898-1 | 2016-10-18T14:42:49.906332105Z --- Creating and signing server certificate
recorderd-5bea4898-1 | 2016-10-18T14:42:49.910146101Z Signature ok
recorderd-5bea4898-1 | 2016-10-18T14:42:49.910307025Z subject=/CN=recorderd-5bea4898-1/O=OwnTracks.org/OU=generate-CA/emailAddress=nobody@example.net
recorderd-5bea4898-1 | 2016-10-18T14:42:49.910778946Z Getting CA Private Key
recorderd-5bea4898-1 | 2016-10-18T14:42:50.100949397Z 2016-10-18 14:42:50,100 CRIT Supervisor running as root (no user in config file)
recorderd-5bea4898-1 | 2016-10-18T14:42:50.106214523Z 2016-10-18 14:42:50,106 INFO supervisord started with pid 1
recorderd-5bea4898-1 | 2016-10-18T14:42:51.109894437Z 2016-10-18 14:42:51,109 INFO spawned: 'recorder' with pid 57
recorderd-5bea4898-1 | 2016-10-18T14:42:51.118028825Z 2016-10-18 14:42:51,117 INFO spawned: 'mosquitto' with pid 58
recorderd-5bea4898-1 | 2016-10-18T14:42:51.133914261Z 1476801771: mosquitto version 1.3.4 (build date 2014-08-17 00:14:52-0300) starting
recorderd-5bea4898-1 | 2016-10-18T14:42:51.134466771Z 1476801771: Config loaded from /owntracks/mosquitto/mosquitto.conf.
recorderd-5bea4898-1 | 2016-10-18T14:42:51.135265389Z 1476801771: Opening ipv4 listen socket on port 1883.
recorderd-5bea4898-1 | 2016-10-18T14:42:51.135694436Z 1476801771: Opening ipv6 listen socket on port 1883.
recorderd-5bea4898-1 | 2016-10-18T14:42:51.136098342Z 1476801771: Opening ipv4 listen socket on port 8883.
recorderd-5bea4898-1 | 2016-10-18T14:42:51.137169635Z 1476801771: Opening ipv6 listen socket on port 8883.
recorderd-5bea4898-1 | 2016-10-18T14:42:51.143272640Z ot-recorder[57]: version 0.6.8 starting with STORAGEDIR=/owntracks/recorder/store
recorderd-5bea4898-1 | 2016-10-18T14:42:51.147278276Z ot-recorder[57]: connecting to MQTT on localhost:1883 as clientID ot-recorder-recorderd-5bea4898-1-57 without TLS
recorderd-5bea4898-1 | 2016-10-18T14:42:51.153739149Z 1476801771: New connection from ::1 on port 1883.
recorderd-5bea4898-1 | 2016-10-18T14:42:51.154101290Z 1476801771: New client connected from ::1 as ot-recorder-recorderd-5bea4898-1-57 (c0, k60).
recorderd-5bea4898-1 | 2016-10-18T14:42:51.154365610Z 1476801771: Sending CONNACK to ot-recorder-recorderd-5bea4898-1-57 (0)
recorderd-5bea4898-1 | 2016-10-18T14:42:51.155137638Z ot-recorder[57]: HTTP listener started on 0.0.0.0:8083
recorderd-5bea4898-1 | 2016-10-18T14:42:51.155578325Z ot-recorder[57]: Using storage at /owntracks/recorder/store with precision 7
recorderd-5bea4898-1 | 2016-10-18T14:42:51.155912498Z ot-recorder[57]: Subscribing to owntracks/# (qos=2)
recorderd-5bea4898-1 | 2016-10-18T14:42:51.156325915Z 1476801771: Received SUBSCRIBE from ot-recorder-recorderd-5bea4898-1-57
recorderd-5bea4898-1 | 2016-10-18T14:42:51.156601272Z 1476801771: 	owntracks/# (QoS 2)
recorderd-5bea4898-1 | 2016-10-18T14:42:51.156895657Z 1476801771: ot-recorder-recorderd-5bea4898-1-57 2 owntracks/#
recorderd-5bea4898-1 | 2016-10-18T14:42:51.157175087Z 1476801771: Sending SUBACK to ot-recorder-recorderd-5bea4898-1-57
recorderd-5bea4898-1 | 2016-10-18T14:42:52.159075364Z 2016-10-18 14:42:52,158 INFO success: recorder entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
recorderd-5bea4898-1 | 2016-10-18T14:42:52.159155844Z 2016-10-18 14:42:52,158 INFO success: mosquitto entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
recorderd-5bea4898-1 | 2016-10-18T14:43:22.556727500Z ot-recorder[57]: http: GET /
recorderd-5bea4898-1 | 2016-10-18T14:43:22.723185486Z ot-recorder[57]: http: GET /static/js/jquery-1.12.0.min.js
recorderd-5bea4898-1 | 2016-10-18T14:43:22.754230619Z ot-recorder[57]: http: GET /static/js/mustache.js
recorderd-5bea4898-1 | 2016-10-18T14:43:22.929164353Z ot-recorder[57]: http: GET /static/js/moment.min.js
recorderd-5bea4898-1 | 2016-10-18T14:43:23.453947628Z ot-recorder[57]: http: GET /api/0/last
recorderd-5bea4898-1 | 2016-10-18T14:43:23.511592501Z ot-recorder[57]: http: GET /static/recorder.png
recorderd-5bea4898-1 | 2016-10-18T14:43:50.194680903Z 1476801830: Received PINGREQ from ot-recorder-recorderd-5bea4898-1-57
recorderd-5bea4898-1 | 2016-10-18T14:43:50.194746248Z 1476801830: Sending PINGRESP to ot-recorder-recorderd-5bea4898-1-57
recorderd-5bea4898-1 | 2016-10-18T14:44:50.185945057Z 1476801890: Received PINGREQ from ot-recorder-recorderd-5bea4898-1-57
recorderd-5bea4898-1 | 2016-10-18T14:44:50.186019175Z 1476801890: Sending PINGRESP to ot-recorder-recorderd-5bea4898-1-57
recorderd-5bea4898-1 | 2016-10-18T14:45:30.921785713Z 1476801930: New connection from 1.161.18.228 on port 1883.
recorderd-5bea4898-1 | 2016-10-18T14:45:30.926039256Z 1476801930: New client connected from 1.161.18.228 as howard (c1, k60, uhoward).
recorderd-5bea4898-1 | 2016-10-18T14:45:30.926062301Z 1476801930: Sending CONNACK to howard (0)
recorderd-5bea4898-1 | 2016-10-18T14:45:45.872586272Z 1476801945: Denied PUBLISH from howard (d0, q0, r0, m0, 'owntracks/howard/test1', ... (0 bytes))
recorderd-5bea4898-1 | 2016-10-18T14:45:50.184399294Z 1476801950: Received PINGREQ from ot-recorder-recorderd-5bea4898-1-57
recorderd-5bea4898-1 | 2016-10-18T14:45:50.184464943Z 1476801950: Sending PINGRESP to ot-recorder-recorderd-5bea4898-1-57
recorderd-5bea4898-1 | 2016-10-18T14:46:31.071743091Z 1476801991: Received PINGREQ from howard
recorderd-5bea4898-1 | 2016-10-18T14:46:31.071827814Z 1476801991: Sending PINGRESP to howard
recorderd-5bea4898-1 | 2016-10-18T14:46:50.186045141Z 1476802010: Received PINGREQ from ot-recorder-recorderd-5bea4898-1-57
recorderd-5bea4898-1 | 2016-10-18T14:46:50.186119986Z 1476802010: Sending PINGRESP to ot-recorder-recorderd-5bea4898-1-57
recorderd-5bea4898-1 | 2016-10-18T14:47:31.072019179Z 1476802051: Received PINGREQ from howard
recorderd-5bea4898-1 | 2016-10-18T14:47:31.072099291Z 1476802051: Sending PINGRESP to howard

**Comment by howardweng** [comment]
I meant denied as following. 

recorderd-5bea4898-1 | 2016-10-18T14:45:45.872586272Z 1476801945: Denied PUBLISH from howard (d0, q0, r0, m0, 'owntracks/howard/test1', ... (0 bytes))

**Comment by jpmens** [comment]
In the volume mounted as `/owntracks` there is a file called `mosquitto.acl`. Please edit that file and add

```
topic owntracks/howard/#
```

and restart the container.

**Comment by howardweng** [comment]
it works, thanks my friend, you really made my day

**Comment by suhlig** [comment]
I get the same error, but the additional line in `mosquitto.acl` did not help. Using the iPhone client, I set the device id to `test1` and the user to `howard` (with an empty password, and authentication turned off). After stopping, removing and starting the container again I still get this:

```
1479507657: New client connected from ???.???.???.??? as howard/test1 (c0, k60, u'howard').
1479507657: Sending CONNACK to howard/test1 (0, 0)
1479507657: Denied PUBLISH from howard/test1 (d0, q1, r1, m7, 'owntracks/howard/test1', ... (175 bytes))
1479507657: Sending PUBACK to howard/test1 (Mid: 7)
```

Here is the complete `mosquitto.acl`:

```
$ docker run --rm -it -v /var/owntracks:/owntracks owntracks/recorderd bash
root@3c0b788ec038:/# cat /owntracks/mosquitto/mosquitto.acl
# This affects access control for clients with no username.
topic read $SYS/#

# This only affects clients with username "roger".
user roger
topic foo/bar

user jane
topic owntracks/jjolie/phone

# This affects all clients.
pattern write $SYS/broker/connection/%c/state

topic owntracks/howard/#

```

Any ideas?

**Comment by suhlig** [comment]
There is something going on with the ACL file. I just commented out the following line from `/var/owntracks/mosquitto/mosquitto.conf`

```
#acl_file /owntracks/mosquitto/mosquitto.acl
```

After another restart all is fine:

```
1479508803: Received PUBLISH from howard/test1 (d0, q1, r1, m16, 'owntracks/howard/test1', ... (175 bytes))
1479508803: Sending PUBACK to howard/test1 (Mid: 16)
1479508803: Sending PUBLISH to ot-recorder-mqtt.???-29 (d0, q1, r0, m2, 'owntracks/howard/test1', ... (175 bytes))
1479508803: Sending PUBLISH to howard/test1 (d0, q1, r0, m2, 'owntracks/howard/test1', ... (175 bytes))
1479508803: Received PUBACK from ot-recorder-mqtt.???-29 (Mid: 2)
1479508803: Received PUBACK from howard/test1 (Mid: 2)
```

Removing the ACL altogether is obviously not really a solution. What's wrong here?

**Comment by howardweng** [comment]
Dear Steffen

Let us do this, see my note "===>" and remember to remove
it.



----------begin-------------

# This affects access control for clients with no username.
topic read $SYS/#


topic read owntracks/#          ===>  this is for owntracks to read
everyone's records.



# This only affects clients with username "roger".
user roger
topic foo/bar

user jane
topic owntracks/jjolie/phone

# This affects all clients.
pattern write $SYS/broker/connection/%c/state

topic owntracks/howard/#


user howard           ==>　need user name in the front before topic.

topic owntracks/#    ==> this is to give authorization to publish all
under Owntracks/  or you can only limit it to User Name howard, which
is owntrack/howard/#



--end-------------------------------------------------------


then you have to "redeploy" not restart, and keep the container.


I am making a video tutorial to explain this, will be ready soon on youtube.


few setting on iphone has to be correct, please see attachment of screen shoot.


let me know if that works.


Howard










2016-11-19 6:46 GMT+08:00 Steffen Uhlig <notifications@github.com>:
