### ISSUE TITLE
MQTT connection: rc=8 [A TLS error occurred.]

### ISSUE THREAD

**Issue by ezar** [owntracks/recorder#161]
I cannot connect recorder to MQTT broker.
I use ca.crt for mosquitto but seems doesn't works!
Can you help me?

**Comment by jpmens** [comment]
I cannot help without details, in particular without you telling us what your configuration looks like.

**Comment by ezar** [comment]
Error in mosquitto.log:

> OpenSSL Error: error:140890C7:SSL routines:SSL3_GET_CLIENT_CERTIFICATE:peer did not return a certificate

**Comment by jpmens** [comment]
Looks to me because of `peer did not return a certificate` that you have `require certificate` in your mosquitto.conf. ??

**Comment by ezar** [comment]
Yes.

**Comment by jpmens** [comment]
So, what make you think that recorder supports client certificates? In fact, did you even look at the list of issues here, in particular #159 ?

**Comment by ezar** [comment]
Ok. That's the problem.
Thank you. I change to connect to internal port (1183) that I don't need TLS 👍 works!

Other question, file .service is correct? I don't need to add 'owntracks/#'?

I start from console: sudo /usr/sbin/ot-recorder 'owntracks/#'  --debug
Logs:
> ot-recorder[18973]: version 0.6.8 starting with STORAGEDIR=/var/spool/owntracks/recorder/store
> ot-recorder[18973]: connecting to MQTT on localhost:1883 as clientID ot-recorder-pihome-18973 without TLS
> ot-recorder[18973]: HTTP listener started on 192.168.1.120:8083
> ot-recorder[18973]: Using storage at /var/spool/owntracks/recorder/store with precision 7
> ot-recorder[18973]: Subscribing to owntracks/# (qos=2)
> +++++ [owntracks/ezarlive/iphone (plen=188, r=1) 
> [<<ommited by ezar>>]
> +++++ [owntracks/ezarlive/g3 (plen=124, r=1) 
> [<<ommited by ezar>>]

But when I access to web, no elements. Why?

**Comment by ezar** [comment]
Ok. I need to force an update!!! 👍 
Its a fantastic app!
Regards,
