### ISSUE TITLE
systemd order to start

### ISSUE THREAD

**Issue by ezar** [owntracks/recorder#162]
Hi,
Seems that ot-recorder starts after mosquitto and It not try to reconnect. I need to restart ot-recorder to start working.
Can you help me?
Regards,

**Comment by jpmens** [comment]
Recorder should start after Mosquitto because the former connects *to* the latter.

**Comment by ezar** [comment]
I know. But in my system, seems that mosquitto starts after recorder.
In this situation recorder cannot connect, and don't try to reconnect.
Any ideas?

**Comment by ezar** [comment]
Hi @jpmens Can you add a retry option?
Regards,

**Comment by jpmens** [comment]
If in your system, Recorder starts after Mosquitto, then you should fix your system.

**Comment by ezar** [comment]
How? Can you help me please?
Why not retry the connection?
Regards,
