### ISSUE TITLE
Add FREEBSD switch to config.mk.in

### ISSUE THREAD

**Issue by jpmens** [owntracks/recorder#163]
and carry into `Makefile` as discussed in #125

**Comment by yggdr** [comment]
On the note of FreeBSD compatibility:
FreeBSD's install has a different function for the -D option, so `gmake install` will fail there. I opted to just `pkg install coreutils` and `sed -E -i "" "s/([[:space:]])install/\1ginstall/" Makefile`, but it might be cleaner to define a $INSTALLOPTS variable and change that depending on the OS/FREEBSD variable.
