### ISSUE TITLE
Switch default port to 8883 when using TLS

### ISSUE THREAD

**Issue by yggdr** [owntracks/recorder#164]
Default port for MQTT over TLS is 8883, so when not giving an explicit configuration for a port for recorder to use, make the port that gets used dependent on whether TLS is in use or not. Currently the default port is 1883 (MQTT without TLS) and you have to explicitly specify it as 8883 when using TLS.

**Comment by jpmens** [comment]
It's trivial to configure port 8883 instead of 1883. Won't fix.
