### ISSUE TITLE
password protect http access

### ISSUE THREAD

**Issue by Dahaniel** [owntracks/recorder#165]
I am running ot-recorder on Ubuntu 14.04 with nginx installed. As ot-recorder uses its own webserver I cannot restrict access to its http directory via nginx config.

Is there a way to restrict http access to ot-recorder via a password?

**Comment by jpmens** [comment]
You can restrict access by configuring nginx as proxy to Recorder (there is an example snippet of configuration in the documentation). Also, Recorder's views can be password-protected, but we recommend the proxy.
