### ISSUE TITLE
Add support for Google Earth Live Tracking

### ISSUE THREAD

**Issue by cpujoe** [owntracks/recorder#166]
It would be helpful if ocat had the functionality to export to KML (or some other equivalent format) so that the current location of all users can be tracked in real-time.

Additional functionality, such as plotting the last X points and a drive-path, would be especially helpful.

**Comment by jpmens** [comment]
According to [this](https://support.google.com/earth/answer/148095?hl=en), Google Earth can import GPX which `ocat` can export. Have you tried it?

**Comment by cpujoe** [comment]
Yes, I have no doubt that this data will import. What I am looking for is a real-time data-feed. The process you linked to is a one-time import for historic data.

Realtime data in Google Eath can be accomplished via KML (ref https://developers.google.com/kml/documentation/kmlreference?csw=1#refreshinterval).

Maybe ocat could be extended to support KML export and/or ot-recorder could expose a KML stream?

**Comment by jpmens** [comment]
This can be accomplished using Lua hooks which would emit KML over HTTP in order to feed Google Earth. I don't think we need to touch Recorder for this.
