### ISSUE TITLE
Content-Type header missing for apikey.js

### ISSUE THREAD

**Issue by hoalex** [owntracks/recorder#168]
When visiting the web interface of the Recorder, I get the following error message in Chrome:

`Refused to execute script from 'https://<mysite>/owntracks/static/apikey.js' because its MIME type ('') is not executable, and strict MIME type checking is enabled.`

I am using nginx as a reverse proxy with the following global directive for security reasons:
`add_header X-Content-Type-Options nosniff;`

I guess this issue could be solved by instructing recorders built-in HTTP server to send a Content-Type of `application/javascript` (or `text/plain` ?) for `apikey.js`.

**Comment by jpmens** [comment]
Before: 
```
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
```

After:

```
< HTTP/1.1 200 OK
< Content-type: application/javascript
< Transfer-Encoding: chunked
```

**Comment by hoalex** [comment]
That was fast, thank you :-)
