### ISSUE TITLE
systemd service not running

### ISSUE THREAD

**Issue by SkizzoSaar** [owntracks/recorder#175]
I have set up different MQTT-port in configuration file (8883). When i manually start ot-recorder everything is working fine.

`$ ot-recorder 'owntracks/#'`

Result is:

```
ot-recorder[11962]: version 0.6.9 starting with STORAGEDIR=/var/spool/owntracks/recorder/store
ot-recorder[11962]: connecting to MQTT on openhab.mynet.local:8883 as clientID ot-recorder-openhab-11962 without TLS
ot-recorder[11962]: HTTP listener started on 127.0.0.1:8083
ot-recorder[11962]: Using storage at /var/spool/owntracks/recorder/store with precision 7
ot-recorder[11962]: Subscribing to owntracks/# (qos=2)
```

But when i try start the service nothing happens.

```
$ service ot-recorder start
$ service ot-recorder status
```
Result:

```
● ot-recorder.service - OwnTracks Recorder
   Loaded: loaded (/etc/systemd/system/ot-recorder.service; enabled)
   Active: failed (Result: exit-code) since Do 2016-12-22 02:03:48 CET; 21s ago
  Process: 12131 ExecStart=/usr/sbin/ot-recorder (code=exited, status=1/FAILURE)
 Main PID: 12131 (code=exited, status=1/FAILURE)

Dez 22 02:03:48 openhab ot-recorder[12131]: --debug                         additional debugging
Dez 22 02:03:48 openhab ot-recorder[12131]: Options override these environment variables:
Dez 22 02:03:48 openhab ot-recorder[12131]: $OTR_STORAGEDIR
Dez 22 02:03:48 openhab ot-recorder[12131]: $OTR_HOST                MQTT hostname
Dez 22 02:03:48 openhab ot-recorder[12131]: $OTR_PORT                MQTT port
Dez 22 02:03:48 openhab ot-recorder[12131]: $OTR_USER
Dez 22 02:03:48 openhab ot-recorder[12131]: $OTR_PASS
Dez 22 02:03:48 openhab ot-recorder[12131]: $OTR_CAFILE                PEM CA certificate chain
Dez 22 02:03:48 openhab systemd[1]: ot-recorder.service: main process exited, code=exited, status=1/FAILURE
Dez 22 02:03:48 openhab systemd[1]: Unit ot-recorder.service entered failed state.
```

Disabling MQTT in **/etc/default/ot-recorder** solves the problem.

`OTR_PORT=0`

When i now start the service no problems occur:

```
service ot-recorder start
service ot-recorder status
```

Result:

```
● ot-recorder.service - OwnTracks Recorder
   Loaded: loaded (/etc/systemd/system/ot-recorder.service; enabled)
   Active: active (running) since Do 2016-12-22 02:06:13 CET; 1s ago
 Main PID: 12285 (ot-recorder)
   CGroup: /system.slice/ot-recorder.service
           └─12285 /usr/sbin/ot-recorder

Dez 22 02:06:13 openhab systemd[1]: Started OwnTracks Recorder.
Dez 22 02:06:13 openhab ot-recorder[12285]: ot-recorder[12285]: version 0.6.9 starting with STORAGEDIR=/var/s...store
Dez 22 02:06:13 openhab ot-recorder[12285]: version 0.6.9 starting with STORAGEDIR=/var/spool/owntracks/recor...store
Dez 22 02:06:13 openhab ot-recorder[12285]: ot-recorder[12285]: Not using MQTT: disabled by port=0
Dez 22 02:06:13 openhab ot-recorder[12285]: Not using MQTT: disabled by port=0
Dez 22 02:06:13 openhab ot-recorder[12285]: ot-recorder[12285]: HTTP listener started on 127.0.0.1:8083
Dez 22 02:06:13 openhab ot-recorder[12285]: HTTP listener started on 127.0.0.1:8083
Dez 22 02:06:13 openhab ot-recorder[12285]: ot-recorder[12285]: Using storage at /var/spool/owntracks/recorde...ion 7
Dez 22 02:06:13 openhab ot-recorder[12285]: Using storage at /var/spool/owntracks/recorder/store with precision 7
Hint: Some lines were ellipsized, use -l to show in full.
```

Any help would be great. Thanks in advance.

**Comment by jpmens** [comment]
I note you're using port 8883 which is typically MQTT over TLS. Is it possible that, in your environment you have OTR_CAFILE defined when you launch manually, but do not have that in /etc/default/ot-recorder? 

Strangely, what you show indicates a usage error ... Can you show me your /etc/default/ot-recorder (without passwords of course)? If you want, you can send it to support@owntracks.org

**Comment by SkizzoSaar** [comment]
Thanks for your quick reply and pardon me for my late answer. It's not TLS, see the output when i start it manually:

`ot-recorder[11962]: connecting to MQTT on openhab.mynet.local:8883 as clientID ot-recorder-openhab-11962 without TLS`

So this can't be the problem i think, can it?

Here is my /etc/default/ot-recorder without the comments:

```
OTR_HOST="openhab.skraus.local"
OTR_PORT=8883
OTR_USER="***"
OTR_PASS="***"
OTR_HTTPHOST="127.0.0.1"
OTR_HTTPPORT=8083
```

and here in complete:

```
#(@)ot-recorder.default
#
# Specify global configuration options for the OwnTracks Recorder
# and its associated utilities to override compiled-in defaults.
# Lines beginning with # are comments
# *** In libconfig versions < 1.4 a trailing semicolon is mandatory

# -----------------------------------------------------
# Storage directory
#

# OTR_STORAGEDIR="/var/spool/owntracks/recorder/store"

# -----------------------------------------------------
# Address or hostname of the MQTT broker
#

OTR_HOST="openhab.skraus.local"

# -----------------------------------------------------
# Port number of the MQTT broker. Defaults to 1883.
# MQTT can be disabled by setting this to 0.
#

#OTR_PORT=1883
OTR_PORT=8883
#OTR_PORT=0

# -----------------------------------------------------
# Username for the MQTT connection
#

OTR_USER="***"

# -----------------------------------------------------
# Password for the MQTT connection
#

OTR_PASS="***"

# -----------------------------------------------------
# QoS for MQTT connection
#

# OTR_QOS=2

# -----------------------------------------------------
# MQTT clientid (default is constant+hostname+pid)
#

# OTR_CLIENTID=""

# -----------------------------------------------------
# Path to PEM-encoded CA certificate file for MQTT (no default)

# OTR_CAFILE=""

# -----------------------------------------------------
# Address for the HTTP module to bind to (default: localhost)
#

OTR_HTTPHOST="127.0.0.1"

# -----------------------------------------------------
# Port number for the HTTP module to bind to (default: 8083)
#

OTR_HTTPPORT=8083

# -----------------------------------------------------
# optional path to HTTP directory in which to store
# access log. Default is to not log access

# OTR_HTTPLOGDIR=""

# -----------------------------------------------------
# API key for reverse-geo lookups
#

# OTR_GEOKEY=""

# -----------------------------------------------------
# Reverse geo precision
#

# OTR_PRECISION=8

# -----------------------------------------------------
# Browser API key for Google maps
#
# OTR_BROWSERAPIKEY=""

# -----------------------------------------------------
# List of topics for MQTT to subscribe to, blank separated in a string
#

# OTR_TOPICS="owntracks/+/+"
```

I'm not a programmer so i can't review the code. I realized that there is no option to enable / disable MQTT over TLS in the /etc/default/ot-recorder. May it be that with port 8883 the connection is automatically established encrypted when starting the service?

Merry Christmas, Happy Holidays!

**Comment by SkizzoSaar** [comment]
> I'm not a programmer so i can't review the code. I realized that there is no option to enable / disable MQTT over TLS in the /etc/default/ot-recorder. May it be that with port 8883 the connection is automatically established encrypted when starting the service?

i tested it out, that's seems not to be the problem. when i configure mosquitto to listen under port 1883 it's 
the same behaviour, the service won't start but manually starting works.

**Comment by jpmens** [comment]
You haven't confirgured OTR_CAFILE in the defaults file, as I said: you have it in environment only which is why it works from the command line but not via systemd.

**Comment by SkizzoSaar** [comment]
Maybe I understood something wrong. I thought OTR_CAFILE is only needed when using TLS. Is that correct or am i wrong?

But I do not use TLS. Here my mosquitto configuration:

```
listener 8883 0.0.0.0
#listener 1883 0.0.0.0
log_type error
log_type warning
log_type notice
log_type information
connection_messages true
log_timestamp true
allow_anonymous false
listener 9001
protocol websockets
pid_file /var/run/mosquitto.pid
persistence true
persistence_location /var/lib/mosquitto/
log_dest file /var/log/mosquitto/mosquitto.log
include_dir /etc/mosquitto/conf.d
```

So I would think the behaviour should be the opposite if OTR_CAFILE was set in the environment and not set in the defaults file: starting via systemd should work and starting from command line should crash (I remember I read somewhere in the documentation that setting OTR_CAFILE implicitly would use TLS).

Or do I even need OTR_CAFILE to be set up, even if my connection does not use TLS?

I guess somewhere I do go wrong, but I don't see where I made my mistake.

**Comment by jpmens** [comment]
I was confused by your (extremely unusual) use of port 8883 for plain MQTT. (Why are you doing that?)

Anyway that's not the problem. Please check your logs (systemd) to determine if you find something; I cannot think of anything (other than permissions?) which should prohibit systemd to start Recorder

**Comment by SkizzoSaar** [comment]
Thanks for your reply. I'll try to investigate soon but I guess it will take a few days till I can take a look at it.

**Comment by VitaliFrolov** [comment]
I am having the same issue more or less when running recorder on raspbian. It is not starting at boot as a service:

```
pi@raspberrypi:~ $ service ot-recorder status
● ot-recorder.service - OwnTracks Recorder
   Loaded: loaded (/etc/systemd/system/ot-recorder.service; enabled)
   Active: failed (Result: exit-code) since Вт 2017-01-10 00:10:48 EET; 1min 2s ago
  Process: 321 ExecStart=/usr/sbin/ot-recorder (code=exited, status=14)
 Main PID: 321 (code=exited, status=14)
```

My problem is due to insufficient permissions. When I try to run it as normal user (default Pi). I get an error:

```
pi@raspberrypi:~ $ service ot-recorder start
Failed to start ot-recorder.service: Access denied
```

But if I use sudo, everything works fine:

```
pi@raspberrypi:~ $ sudo service ot-recorder start
pi@raspberrypi:~ $ service ot-recorder status
● ot-recorder.service - OwnTracks Recorder
   Loaded: loaded (/etc/systemd/system/ot-recorder.service; enabled)
   Active: active (running) since Вт 2017-01-10 00:13:48 EET; 3s ago
 Main PID: 1128 (ot-recorder)
   CGroup: /system.slice/ot-recorder.service
           └─1128 /usr/sbin/ot-recorder
```

Any ideas how to fix this?

**Comment by mking007** [comment]
I think I have a similar issue to this. 
I've just installed ot-recorder on a raspberry pi and it runs fine if I start it from a terminal with: `ot-recorder 'owntracks/#'`
I can see MQTT logging data and can browse to localhost:8083 and see the map and data.

However the service doesn't start automatically if I reboot. 
`cat /var/log/syslog |grep ot-recorder`
gives me the following errors in the system log
```
Jan 12 00:30:33 raspberrypi systemd[1]: ot-recorder.service: main process exited                                                        , code=exited, status=1/FAILURE
Jan 12 00:30:33 raspberrypi systemd[1]: Unit ot-recorder.service entered failed                                                         state.

```
Any ideas appreciated
Michael

**Comment by mking007** [comment]
I've been trying to track this down and I am convinced it's a permissions problem. Following some of the other issues here I used this command: 
`env - /usr/sbin/ot-recorder 'owntracks/#' `
This gives me the following output
`ot-recorder[4298]: Cannot read defaults from /etc/default/ot-recorder: Permission denied
ot-recorder[4298]: version 0.6.9 starting with STORAGEDIR=/var/spool/owntracks/recorder/store
ot-recorder[4298]: connecting to MQTT on localhost:1883 as clientID ot-recorder-raspberrypi-4298 without TLS
ot-recorder[4298]: HTTP listener started on 127.0.0.1:8083
ot-recorder[4298]: Using storage at /var/spool/owntracks/recorder/store with precision 7
ot-recorder[4298]: Subscribing to owntracks/# (qos=2)
`
The defaults file `/etc/default/ot-recorder` has 0640 permissions and ownership of owntracks:root

I'm definitely not a linux expert, so any thoughts appreciated if this has triggered anything.

**Comment by jpmens** [comment]
Would you please show me an `ls -l /usr/sbin/ot-recorder`?

**Comment by mking007** [comment]
Thanks for your help. Here is the result of an `ls -l /usr/sbin/ot-recorder`

`---s--x--x 1 owntracks owntracks 402948 Nov 25 17:54 /usr/sbin/ot-recorder
`

**Comment by jpmens** [comment]
The red is indicating it's an SUID program (`--s`); this means the program runs as `owntracks`, and as such must be able to read your `/etc/default/ot-recorder` which is 0640 and belongs to `owntracks:root` ...

**Comment by mking007** [comment]
Hi @jpmens Yes, just to confirm that `/etc/default/ot-recorder` is 0640 and owntracks:root. See below

`pi@raspberrypi:/etc/default $ stat ot-recorder
  File: ‘ot-recorder’
  Size: 2230            Blocks: 8          IO Block: 4096   regular file
Device: b307h/45831d    Inode: 393473      Links: 1
Access: (0640/-rw-r-----)  Uid: (  116/owntracks)   Gid: (    0/    root)
Access: 2017-01-12 18:11:26.000000000 +0000
Modify: 2016-11-25 17:54:19.000000000 +0000
Change: 2017-01-12 18:54:25.814583254 +0000
 Birth: -
pi@raspberrypi:/etc/default $ ls -al ot-recorder
-rw-r----- 1 owntracks root 2230 Nov 25 17:54 ot-recorder
`

**Comment by M-ax-G** [comment]
I just installed ot-recorder on Jessie/rPi
it would not start with ./ot-recorder 'owntracks/#'
-bash: ./ot-recorder: No such file or directory

then tried:
sudo service ot-recorder start
and
service ot-recorder status
● ot-recorder.service - OwnTracks Recorder
   Loaded: loaded (/etc/systemd/system/ot-recorder.service; disabled)
   Active: failed (Result: exit-code) since Sat 2017-01-21 18:54:36 AEST; 6min ago
  Process: 1134 ExecStart=/usr/sbin/ot-recorder (code=exited, status=1/FAILURE)
 Main PID: 1134 (code=exited, status=1/FAILURE)

and get:
ls -l /usr/sbin/ot-recorder
---s--x--x 1 owntracks owntracks 791384 Nov 26 03:53 /usr/sbin/ot-recorder

Maybe this helps with troubleshooting?

**Comment by simonszu** [comment]
Hi,

i have the same problem, Debian Jessie on amd64. Starting the recorder via `sudo ot-recorder 'owntracks/#'` is fine, but not via systemd. The `systemctl status` command looks like this:

```
● ot-recorder.service - OwnTracks Recorder
   Loaded: loaded (/etc/systemd/system/ot-recorder.service; disabled)
   Active: failed (Result: exit-code) since So 2017-01-29 21:23:25 CET; 11min ago
  Process: 17424 ExecStart=/usr/sbin/ot-recorder (code=exited, status=1/FAILURE)
 Main PID: 17424 (code=exited, status=1/FAILURE)

Jan 29 21:23:25 tharan ot-recorder[17424]: --debug                         additional debugging
Jan 29 21:23:25 tharan ot-recorder[17424]: Options override these environment variables:
Jan 29 21:23:25 tharan ot-recorder[17424]: $OTR_STORAGEDIR
Jan 29 21:23:25 tharan ot-recorder[17424]: $OTR_HOST                MQTT hostname
Jan 29 21:23:25 tharan ot-recorder[17424]: $OTR_PORT                MQTT port
Jan 29 21:23:25 tharan ot-recorder[17424]: $OTR_USER
Jan 29 21:23:25 tharan ot-recorder[17424]: $OTR_PASS
Jan 29 21:23:25 tharan ot-recorder[17424]: $OTR_CAFILE                PEM CA certificate chain
Jan 29 21:23:25 tharan systemd[1]: ot-recorder.service: main process exited, code=exited, status=1/FAILURE
Jan 29 21:23:25 tharan systemd[1]: Unit ot-recorder.service entered failed state.
```
which looks exactly like the console output when you start ot-recorder manually but not specifying any values. 
Please note that i have not defined `$OTR_CAFILE` in the `/etc/default/ot-recorder` since i am allowing unencrypted access to my MQTT instance from localhost, and both applications are running on the same host. 
The permissions of the default-file and the ot-recorder binary are the same as the others here are telling, since i have installed ot-recorder via the APT repo as well.

**Comment by simonszu** [comment]
Nevermind, the systemd had no configuration of which MQTT topic to subscribe to built in, so of course the recorder won't start. I had to manually edit the unit template and add 'owntracks/#' to the end of the ExecStart line.

**Comment by M-ax-G** [comment]
@simonszu : do you mind showing where and what you've changed please?

**Comment by simonszu** [comment]
@M-ax-G Open the systemd unit, located in `/etc/systemd/system/ot-recorder.service`. There will be a line which says `ExecStart=/usr/sbin/ot-recorder`. This will tell systemd to try to startup ot-recorder, but ot-recorder refuses to start because it has no topic to subscribe to. So i changed the line to `ExecStart=/usr/sbin/ot-recorder 'owntracks/#'` and after a `systemctl daemon-reload` ot-recorder starts up just fine. 

Someone could create a Pull Request, maybe even with a configurable topic in `/etc/default/ot-recorder`, but to be honest, i am too lazy for it just now. Just hoping that all the folks trying to install ot-recorder on hosts with systemd will somewhen find this issue. ;)

**Comment by M-ax-G** [comment]
@simonszu : Thank you very much!!

**Comment by jpmens** [comment]
I cannot reproduce the issue. Configuring the following in `/etc/default/ot-recorder`

```
egrep -v '^#|^$' /etc/default/ot-recorder
OTR_HOST="192.168.1.130"
OTR_PORT=1883
OTR_TOPICS="owntracks/+/+"
```

enables me to start the service using `systemctl start ot-recorder`.

```
$ systemctl status ot-recorder
● ot-recorder.service - OwnTracks Recorder
   Loaded: loaded (/etc/systemd/system/ot-recorder.service; disabled)
   Active: active (running) since Tue 2017-03-14 11:41:28 CET; 2min 8s ago
 Main PID: 1273 (ot-recorder)
   CGroup: /system.slice/ot-recorder.service
           └─1273 /usr/sbin/ot-recorder
```

After enabling the service with `systemctl enable ot-recorder`, the service starts on boot:

```
# systemctl status ot-recorder
● ot-recorder.service - OwnTracks Recorder
   Loaded: loaded (/etc/systemd/system/ot-recorder.service; enabled)
   Active: active (running) since Tue 2017-03-14 11:46:30 CET; 49s ago
 Main PID: 495 (ot-recorder)
   CGroup: /system.slice/ot-recorder.service
           └─495 /usr/sbin/ot-recorder

```

**Comment by simonszu** [comment]
You're right. For some reason, i did not see this option in my default.conf, maybe because it's at the very bottom. After uncommenting it, i could start ot-recorder with an unmodified systemd unit file. My fault.

**Comment by Aquariu** [comment]
Sorry to pull a closed issue from the grave, but what hasn't been stated here, and what was messing up with my systemd service file, is that the owntracks user **also** needs to own the `/var/spool/owntracks` directory (or wherever you've chose to put your data). I needed to set this manually because of no deb package build for Stretch on raspberry pi. And make install obviously didn't change those permission itself (and it shouldn't since it's a configurable thing).
