### ISSUE TITLE
Constant 100% CPU usage

### ISSUE THREAD

**Issue by zabouth** [owntracks/recorder#176]
The ot-recorder process is constantly using 100% of the CPU. 

Tested on:

- OS: Ubuntu 16.04.1 LTS 
- MQTT: mosquitto 1.4.10 with TSL from mosquitto PPA
- OwnTracks Recorder: 0.6.9 and c1a1701

**Comment by jpmens** [comment]
Please explain under what conditions this happens. Lots of publishes, viewing maps, ... ? If necessary, launch with `--debug` to get more information.

**Comment by zabouth** [comment]
It is a test system with 2 live users and very few updates. The only messages showing up on the debug output are the latest two location messages for the users. The system jump to 100% CPU a few seconds after starting and stays there till terminated. 

<pre>
ps -p 483 -o %cpu,%mem,cmd
%CPU %MEM CMD
100  0.1 ot-recorder --debug
</pre>

**Comment by zabouth** [comment]
After more investigation I have found triggering the issue.
It only occurs when you set the http port to 0. Tested both the command line switch and the config file.

**Comment by jpmens** [comment]
I confirm: this is a *bug*. Thank you for investigating!

**Comment by jpmens** [comment]
Thank you @zabouth; I believe I've now fixed this, if you care to test from a git checkout.

**Comment by zabouth** [comment]
Tested from f9bc997 it's working preferably. Thank you so much!
