### ISSUE TITLE
Create packages (.deb, .rpm, ....)

### ISSUE THREAD

**Issue by jpmens** [owntracks/recorder#18]
Any takers to assist me in doing this (in particular .deb)?
I've started on a `.spec` (in etc/)

**Comment by jpmens** [comment]
Packages for RHEL/Centos are [being made available](https://packagecloud.io/owntracks/ot-recorder)

**Comment by justyns** [comment]
Were these packages built manually last time?   It doesn't look like they're up to date with the github releases at least.

**Comment by jpmens** [comment]
They were built manually of sorts: RHEL-type on OBS and Debian with fpm.  We still haven't got around to getting this streamlined. If you have any good ideas, shout out, please! :-)

**Comment by darix** [comment]
you want to clarify the license compatibility to make it even possible for distros to include it. also api key should be a runtime setting i think.

**Comment by jpmens** [comment]
IANAL

**Comment by darix** [comment]
So I asked a friend who knows a bit more about the whole license stuff. You have at least one conflict ... [BSD-4-Clause][1] and [GPL-2.0][2] .

The usage of the GPL-2.0 library makes the whole work GPL-2.0 licensed. But GPL-2.0 doesn't allow further restrictions to the redistribution than its own. The advertisement clause from BSD-4-Clause is a further restriction.

[1]: https://github.com/owntracks/recorder/blob/master/LICENSE#L83
[2]: https://github.com/owntracks/recorder/blob/master/LICENSE#L184

**Comment by jpmens** [comment]
So you are saying that if I remove the `base64.[ch]` files and thus the [BSD-4-Clause](https://github.com/owntracks/recorder/blob/master/LICENSE#L83), the result is clean enough?

**Comment by darix** [comment]
yes

**Comment by jpmens** [comment]
`base64.[ch]` replaced. Thanks for your input @darix
