### ISSUE TITLE
otr_putrec not preventing storage of record

### ISSUE THREAD

**Issue by binarybucks** [owntracks/recorder#180]
I'm bridging the greenwich data from your broker to my local one on `greenwich/bbucks/356612027385477`

Recorder subscribes to that topic and publishes it in json format to `owntracks/alexander/a4`. 
That works very well. 

I've added a pubrec hooklet to prevent the raw topic from showing up in recorder
```
function otr_putrec(u, d, s)
    if(u == 'bbucks') then
      return 1
    end
end
```

However, it still records the raw bbucks device in addition to the alexander/a4 device. 
The putrec function seems to be called and the if matches.

**Comment by jpmens** [comment]
I cannot reproduce this: I have a most similar function:

```lua
function otr_putrec(u, d, s)
        if (u == 'uno') then
                print("skip PUTREC " .. u)
                return 1
        end
end
```

and when I publish I see the request on the Recorder's console

```
skip PUTREC uno
* 09:09:16 nop/uno/lua                         t=u tid=JJ loc=48.85833,3.29513 [FR] D6, 77510 Bellot, France (u0d)
```

and no record is added to the `.rec` file.

**Comment by jpmens** [comment]
@binarybucks Have you tried reproducing this issue? As demonstrated above, I cannot.
