### ISSUE TITLE
README.md - hours 

### ISSUE THREAD

**Issue by powermik** [owntracks/recorder#182]
from README.md
"hours 	N 	number of past hours (from "now") for which to show data; use instead of from and to"

It looks like that one is not implemented.

Is there another way to show waypoints for the last 48 hours without calculating --from time?

**Comment by jpmens** [comment]
Please show me proof that it doesn't work, by showing me your view file.

**Comment by powermik** [comment]
seems that i misread the documentation:
i thought that there is a statement that "ocat" uses the same parameters
