### ISSUE TITLE
recorder view

### ISSUE THREAD

**Issue by helio58** [owntracks/recorder#188]
Hi,
I have the recorder setup in a macbook homebrew.
The recorder works great, but i m not able to run the view.
I have changed the xmap to vmap , user and password to match and date.
But when try to reach http://localhost:8083/owntracks/view/iphone
I get 404 not found.
please could i get same guidance?
Thanks

**Comment by jpmens** [comment]
Do  you have a file called `iphone.json` configured with the view data?

**Comment by helio58** [comment]
Hi, 
Yes I have. with this :
{
	"page" : "vmap.html",
	"user" : "iphone",
	"device" : "iphone",
	"from" : "2017-03-16",
	"to"   : "2017-09-25",

	"label" : "iphone",

}
I have placed this file in the views folder same as jane.json.sample
Maybe there is a error in my configuration?

**Comment by jpmens** [comment]
That is not valid JSON (trailing comma on last element). You can test that yourself:

```
$ python -mjson.tool < /tmp/x
Expecting property name: line 10 column 7 (char 159)
```

**Comment by helio58** [comment]
Thanks you have changed works

**Comment by jpmens** [comment]
Eh, what?

**Comment by helio58** [comment]
Sorry I mean I have changed , removed the ","
Thanks again
