### ISSUE TITLE
Problem showing maps when behind reverse proxy

### ISSUE THREAD

**Issue by Woefdram** [owntracks/recorder#189]
Hi,

I configured the recorder to listen on eth0 instead of localhost, because it runs on a server without graphical environment. When I point my browser at it, everything works like a charm. I don't have a Google API key, and I assume I don't need one because the documentation tells me that the recorder uses OpenStreetMap by default.

After initial testing, I configured a reverse proxy with Apache, so that I could do some authentication/authorization. But then the live map and the views fail. I see the map, and the last known position for a fraction of a second, and then the screen turns grey and tells me something went wrong:

![owntracks-errors2](https://cloud.githubusercontent.com/assets/26726517/24420126/010fd8be-13f2-11e7-83c1-85f26c201d96.jpg)

In the JavaScript console I find this message:

"Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error"

This suggests I need a key, but everything works just fine without one if I connect to the recorder directly. I don't trust Google, so I would really like to avoid having to get a key from them.

Seeing how everything works just fine without the reverse proxy, I assume that that's where the problem is. Can anyone shed some light on this?

Hans

**Comment by jpmens** [comment]
If the documentation suggests OpenStreetMap is default, that is a bug in the documentation. As you'd then be using Google by default you will require appropriate keys.

**Comment by jpmens** [comment]
You're right and the documentation is right: the default is OpenStreetMap, but that works only on the live map (the person who contributed the code did it for that map only), which means if you want to use views, you'll need Google maps for it. (Unless of course you feel like contributing code to make OpenStreetMap work in views ... :-)

**Comment by Woefdram** [comment]
As much as I'd like to make that contribution, I don't think I'm up for it, sorry...

**Comment by epideme** [comment]
As for the original error ( MissingKeyMapError ):
I get this error consistently if i access my reverse proxy with FQDN "http://mypiname.localdomain.net/owntracks/", but the map works perfectly if I use the host name only "mypiname/owntracks/", or if I use IP address "http://192.168.3.4/owntracks".

**Comment by Jestre** [comment]
Using the Docker version, I get the same error message when I click on the Live map.  I expected it to just work with OSM, but it appears the default for me was gMaps, so I just applied a key in the config file and things started working.  I didn't see a switch to use OSM maps.

**Comment by jpmens** [comment]
The docker images will be updated shortly and will then have the same defaults as the packages.
