### ISSUE TITLE
502 Proxy Error when running ot-recorder in Apache reverse proxy

### ISSUE THREAD

**Issue by gwillegers** [owntracks/recorder#190]
Hello,
I have mosquitto and ot-recorder running on a Raspberry Pi, with Raspbian as OS.
Mosquitto and ot-recorder are working fine. I installed the OwnTracks Android app on my phone, and it reports my location, which is then recorded.
I installed Apache2 and configured a reverse proxy as described in [https://github.com/owntracks/recorder/blob/master/README.md#apache](url).
When I try to connect to http://pi/owntracks, I get:
```
Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /owntracks.

Reason: Error reading from remote server

Apache/2.4.10 (Raspbian) Server at pi1 Port 88
```
This is /etc/apache2/conf-available/ot-recorder.conf:
```
ProxyPass        /owntracks/ws        ws://127.0.0.1:8883/ws keepalive=on retry=60
ProxyPassReverse /owntracks/ws        ws://127.0.0.1:8883/ws keepalive=on

# Static files
ProxyPass /owntracks                  http://127.0.0.1:8883/
ProxyPassReverse /owntracks           http://127.0.0.1:8883/
```
Regards,
George

**Comment by gwillegers** [comment]
Time to answer my own question. I just noticed I had the wrong port number in the reverse proxy config. Port 8883 should be 8083. Problem solved.

**Comment by Vino-git** [comment]
Can you please give full details of how you setup this apache server for owntrack recorder. I have everything running except owntrack over internet
