### ISSUE TITLE
Docker - Should user be displayed automatically on map?

### ISSUE THREAD

**Issue by Jestre** [owntracks/recorder#191]
I download the app to my iPhone today, then went the Docker route for setting up the server.  After watching for errors I ended up uncommenting the `mosquitto.passwd` line in .conf and creating a password file.  I then added the following to the `mosquitto.acl`, based on another post here:

    user bob
    topic /owncloud/bob/#

There are now no errors in the output that I can see, but I am unable to see anything but the `ping` user items on my map.  I stopped (^C) and started the docker thingy between changes, and even tried to `exec` into it and `kill -HUP` the recorder, just to see if that would cause it to start showing my data, no joy.  Nor does adding `?user=bob` to the end of any of the URLs.

What am I missing?

**Comment by jpmens** [comment]
Are you sure you mean `/owncloud` ?

**Comment by Jestre** [comment]
Woops, no.  Typed that instead of pasting it.  Sorry, different project :)  I also do not have the preceding slash as in the original post.  Here is the relevant snip:

    user bob
    topic owntracks/bob/#

**Comment by jpmens** [comment]
Are you sure data from your device is actually reaching the Recorder? See if you can view the initial page (or the Table view) to verify.

**Comment by Jestre** [comment]
No, it doesn't appear as if any of the data are reaching the recorder piece, that's the issue.  If I go to the web, the only data I see on the table and/or map are those of the `ping`.

I know the data are getting as far as the mosquitto instance, since I see what appears to be proper log information from that:

    1493735195: New client connected from 174.194.x.x as bob/bobiPhone (c0, k60, u'bob').
    1493735195: Sending CONNACK to bob/bobiPhone (0, 0)
    1493735195: Received PUBLISH from bob/bobiPhone (d0, q1, r1, m540, 'owntracks/bob/bobiPhone', ... (175 bytes))
    1493735195: Sending PUBACK to bob/bobiPhone (Mid: 540)
    1493735195: Sending PUBLISH to bob/bobiPhone (d0, q1, r0, m572, 'owntracks/bob/bobiPhone', ... (175 bytes))
    1493735195: Received PUBACK from bob/bobiPhone (Mid: 572)

And I see that the recorder piece seems to be up and available from mosquitto (if I understand these messages):

    1493735197: Received PINGREQ from ot-recorder-catalyst.bob.net-30
    1493735197: Sending PINGRESP to ot-recorder-catalyst.bob.net-30

But if I check the files under the recorder directory, I see that they are current, but include no information for the `bob` user:

    jestre@catalyst:/srv/owntracks/recorder/store$ cat monitor
    1493735683 owntracks/ping/ping
    
    jestre@catalyst:/srv/owntracks/recorder/store$ ls last/
    ping

**Comment by jpmens** [comment]
You evaluation is correct as are all your assumptions. The important bit to look for later will be wether files under `recorder/store/rec/` are created, rather one file (`2017-05.rec`) containing current publishes for your user.

Can you run a `ps ax` on that machine and show me the `ot-recorder` process arguments? 

You've protected publishes to user `bob` with a password which also means  that your recorder process needs authorization to access said publishes. Easiest way will be to add user `bob` and its password to the recorder's `/etc/defaults/ot-recorder` file so that when it launches it authenticates to the broker.

**Comment by Jestre** [comment]
Here is the `ps ax`:

       30 ?        S      0:00 /usr/sbin/ot-recorder --http-host 0.0.0.0

This is the docker version, so I'll work on figuring out that last part :)

**Comment by Jestre** [comment]
Okay, that seems to have worked, thank you!

I guess I need to read more about the security functionality in mosquitto in case I want to add additional users to the system.  But for now, my data are displaying.

**Comment by jpmens** [comment]
I'm glad to hear you got it going. It's not trivial, but it's rewarding when it finally does work, eh? :-)
I think you'll find plenty to read in the Mosquitto documentation as well as a tutorial-like chapter in our [Booklet](http://owntracks.org/booklet/).
