### ISSUE TITLE
docker alpine

### ISSUE THREAD

**Issue by roblad** [owntracks/recorder#192]
Hi,

I created docker on alpine linux with mqtt integrated - for rpi and amd64 platforms.

https://hub.docker.com/r/robowntracks/owntracks-alpine/
https://github.com/roblad/ot-recorder
Regards,
RL

**Comment by jpmens** [comment]
Thank you, that sounds useful I think. @juzam could you have a look at this, and should we mention this in `recorderd`?

**Comment by juzam** [comment]
I hope to take a look at the repo and the image during the weekend. As per the mention, a line in README.md after how the official images are being built and pushed to the Docker HUB would do?

**Comment by roblad** [comment]
# BULD
USE TAG for RPI - :armhf
docker build --no-cache=true --compress=true -t robowntracks/owntracks-alpine:amd64 .

# Container create and run 
USE TAG for RPI - :armhf
docker run -ti  --name=ot-recorder -p 8083:8083 -p 1883:1883 robowntracks/owntracks-alpine:amd64 

for background add option -d
# Start Stop container 

docker ot-recorder start 

docker ot-recorder stop
