### ISSUE TITLE
Offline map

### ISSUE THREAD

**Issue by audunbrekke** [owntracks/recorder#194]
Is it possible to use / store offline maps ? I would like ti use owntracks recorder in a closed network with no internet connection.

**Comment by jpmens** [comment]
That is currently not possible.

**Comment by audunbrekke** [comment]
This should be possible. Then it would be "true" owntracks :) OpenStreetMap has the option to download tiles, or even render you own maps from downloaded data. It should then be easy to cache / download tiles on the local owntracks recorder server.  Is it possible that this can ble implemented ?

**Comment by jpmens** [comment]
Sure, you can implement it, and we will very gladly take a pull-request for it.
