### ISSUE TITLE
Client certificate not being passed

### ISSUE THREAD

**Issue by Ggator** [owntracks/recorder#197]
I'm using mosquitto v1.4.12 with ot-recorder v0.7.1.

No problems connecting to mosquitto using client authentication via OwnTracks iOS app or command line (mosquitto_sub, mosquitto_pub).  However, ot-recorder will not connect despite using the OTR_CERTFILE and OTR_KEYFILE variables in the config file.

If I disable client authentication (comment out "require_certificate true" in mosquitto.conf), then ot-recorder connects.

With mosquitto client authentication enabled, I get the following ot-recorder error message:

```
ot-recorder[31164]: connecting to MQTT on localhost:8883 as clientID ot-recorder-server-31164 with TLS
ot-recorder[31164]: HTTP listener started on XX.XX.XX.XX:8083
ot-recorder[31164]: Using storage at /var/spool/owntracks/recorder/store with precision 7
ot-recorder[31164]: MQTT connection: rc=8 [A TLS error occurred.] (errno=0; Success). Sleeping...
```

And the following from mosquitto:

```
1497027790: New connection from ::1 on port 8883.
1497027790: OpenSSL Error: error:140890C7:SSL routines:ssl3_get_client_certificate:peer did not return a certificate
1497027790: Socket error on client <unknown>, disconnecting.
```

My mosquitto.conf file contains the following:

```
listener 8883
cafile /etc/mosquitto/certs/ca.crt
certfile /etc/mosquitto/certs/server.crt
keyfile /etc/mosquitto/certs/server.key
#tls_version tlsv1.2
require_certificate true
#use_identity_as_username true
```

Block from ot-recorder config file:

```
OTR_CAFILE="/etc/mosquitto/certs/ca.crt"
OTR_CERTFILE="/etc/mosquitto/certs/recorder.crt"
OTR_KEYFILE="/etc/mosquitto/certs/recorder.key"
```

Output from ocat -v:

```
This is OwnTracks Recorder, version 0.7.1
built with:
	WITH_MQTT = yes
	WITH_HTTP = yes
	WITH_ENCRYPT = yes
	WITH_PING = yes
	CONFIGFILE = "/etc/default/ot-recorder"
	STORAGEDEFAULT = "/var/spool/owntracks/recorder/store"
	STORAGEDIR = "/var/spool/owntracks/recorder/store"
	DOCROOT = "/var/spool/owntracks/recorder/htdocs"
	GHASHPREC = 7
	DEFAULT_HISTORY_HOURS = 6
	JSON_INDENT = "NULL"
	LIBMOSQUITTO_VERSION = 1.4.12
	MDB VERSION = LMDB 0.9.16: (August 14, 2015)
	SODIUM VERSION = 1.0.8
	GIT VERSION = tarball
```

ca.crt, recorder.crt, and recorder.key are PEM encoded (and work fine with other clients).  I don't think it's a permissions issue because I've run ot-recorder as root (yes, I know, bad practice, but did it for purposes of troubleshooting) and other clients access the certs and keys fine from that directory.

**Comment by jpmens** [comment]
Thank you for your succinct and clear issue report: you have found a bug, or rather, you caught me cheating. :-)

Unfortunately (I ought to say 'stupidly'), these options are not meant for the defaults file but rather are supposed to be environment variables which are picked up by `ot-recorder` at the time it launches. So, in order to get your TLS client certificate going, you would

```bash
export OTR_CAFILE="/etc/mosquitto/certs/ca.crt"
export OTR_CERTFILE="/etc/mosquitto/certs/recorder.crt"
export OTR_KEYFILE="/etc/mosquitto/certs/recorder.key"

ot-recorder ...
```

I'm ashamed to say the documentation is also incorrect, and I will be opening an issue about this right now.

**Comment by Ggator** [comment]
Hi,
Thanks for responding so quickly.
Unfortunately, I tried your suggestion and get the same error, so I don't think they are getting picked up even as environment variables.
Best regards,Brian

**Comment by jpmens** [comment]
Please export the values pointing to something non-existent (eg OTR_CAFILE=kdkdkdk) and run ot-recorder. Does it complain? If so, then it's picking up the appropriate files.

**Comment by Ggator** [comment]
I exported OTR_ stuff to point to garbage and the error message didn't change at all.

**Comment by jpmens** [comment]
If you run this, what output do you get?

```
OTR_CAFILE=kdkd OTR_KEYFLE=xxx OTR_CERTFILE=999 ./ot-recorder --port 8883 --host 127.0.0.1 'asdf'
```

**Comment by Ggator** [comment]
Using:
`OTR_CAFILE=kdkd OTR_KEYFILE=xxx OTR_CERTFILE=999 ot-recorder --port 8883 --host 127.0.0.1 'asdf'`

Results in:
```
ot-recorder[7411]: version 0.7.1 starting with STORAGEDIR=/var/spool/owntracks/recorder/store
ot-recorder[7411]: cafile configured as `kdkd' can't be opened: No such file or directory
```

Since I don't have a problem with ca.crt, I tried the following:
`OTR_KEYFILE=xxx OTR_CERTFILE=999 ot-recorder --port 8883 --host 127.0.0.1 'asdf'`

And got the following:
```
ot-recorder[7437]: version 0.7.1 starting with STORAGEDIR=/var/spool/owntracks/recorder/store
Cannot set TLS CA: Invalid function arguments provided. (check path names)
```

**Comment by jpmens** [comment]
That proves that OTR_KEYFILE and OTR_CERTFILE are being picked up (the error message is issued by the Mosquitto library, and it's basicallly telling us the files can't be opened, which is correct).

You should, now, be able to give it the correct paths to your files.

**Comment by Ggator** [comment]
Yes, just tried that,  and it provided the same error:

```
ot-recorder[7437]: version 0.7.1 starting with STORAGEDIR=/var/spool/owntracks/recorder/store
Cannot set TLS CA: Invalid function arguments provided. (check path names)
```

**Comment by jpmens** [comment]
That definitely indicates there's something wrong with the certificate/key files. Please double-check the user can read them (are you still running as root?), and that they're PEM formatted (`openssl x509 -in filename -noout -text {cafile,certfile}`

**Comment by jpmens** [comment]
The diagnostic `Cannot set TLS CA: Invalid function arguments provided. (check path names)` is printed whenever Mosquitto detects that an incorrect or non-existing/readable file is given as either `$OTR_CERTFILE` or `$OTR_KEYFILE`.

**Comment by jpmens** [comment]
This works fine here.

#### `cat /tmp/runit`

```bash
export OTR_CAFILE="/tmp/gator/ca.crt"
export OTR_CERTFILE="/tmp/gator/jp.crt"
export OTR_KEYFILE="/tmp/gator/jp.key"

./ot-recorder --port 9993 --host 127.0.0.1 --clientid GgatorTest 'owntracks/ggator/#'
```

#### mosquitto.conf

```bash
...
listener 9993
cafile tls4/ca.crt
capath tls4/
certfile tls4/tiggr.ww.mens.de.crt
keyfile tls4/tiggr.ww.mens.de.key
require_certificate true
use_identity_as_username true
```

#### `sh /tmp/runit`

```
Jun 10 10:39:04  ot-recorder[3500] <Debug>: version 0.7.1 starting with STORAGEDIR=JP
Jun 10 08:39:04  ot-recorder[3500] <Info>: connecting to MQTT on 127.0.0.1:9993 as clientID GgatorTest with TLS
Jun 10 08:39:04  ot-recorder[3500] <Info>: HTTP listener started on 127.0.0.1:8085
Jun 10 08:39:04  ot-recorder[3500] <Debug>: Subscribing to owntracks/ggator/# (qos=2)
```

#### mosquitto.log
```
1497084129: Opening ipv4 listen socket on port 9993.
1497084180: New connection from 127.0.0.1 on port 9993.
1497084180: Client GgatorTest disconnected.
1497084180: New client connected from 127.0.0.1 as GgatorTest (c0, k60, u'jp@example.de').
1497084180: Sending CONNACK to GgatorTest (0, 0)
1497084180: Received SUBSCRIBE from GgatorTest
1497084180: 	owntracks/ggator/# (QoS 2)
1497084180: GgatorTest 2 owntracks/ggator/#
1497084180: Sending SUBACK to GgatorTest
```

**Comment by jpmens** [comment]
Closed for lack of reaction
