### ISSUE TITLE
View live map of single device?

### ISSUE THREAD

**Issue by aszymanik** [owntracks/recorder#199]
I'd like to view the live map of a single device. The live map presently shows all users and all devices but there are times when we're only interested in one device and the autozoom/autopan feature makes it harder to follow a single device. When the devices/users are far apart, the autozoom is too zoomed out to see any of the clients clearly. Finally, by being able to view only one device at a time, I can share a view URL without giving up the privacy of all users tracked.

Insecurely, I can modify ws_connect() of last/websock.js to filter devices in ws.onmessage but this is ugly and is hardcoded. Using jquery can clean this up a bit but from a privacy standpoint, all devices are still being transmitted to the web client and we have to trust he/she has not removed filtering (and thus locations of everyone else).

This issue could possibly be solved by allowing /ws/last to take a param and send to send_last() in http.c such that only one device is emitted.

Thanks

**Comment by jpmens** [comment]
You've certainly done your homework! :-) 

I cannot work on this, but if you're up to creating a pull request, I'd certainly look at it and take it. I agree that the last method you speak of (`/ws/last` takes a parameter) would be the cleanest; apart from privacy it's the way to limit the _amount_ of data going to the websocket, so that's what I'd prefer.

**Comment by vogelfreiheit** [comment]
Seconded!

**Comment by jpmens** [comment]
Closing as stale, and directing to OwnTracks Fronted.

**Comment by jmhunter** [comment]
For others interested in this, you can follow the discussion at https://github.com/owntracks/frontend/issues/5 which seems related
