### ISSUE TITLE
Export recorded Data

### ISSUE THREAD

**Issue by Hellmudth** [owntracks/recorder#200]
Is it possible to export already recorded data and import it in a new installation?

Thanky

**Comment by jpmens** [comment]
Yes, that's rather easy: from your "old" installation take, using _zip_ or _tar_ or similar program, the files you need from your `<storage>` directory. You should actually be able to take the *whole* directory and copy it to your "new" installation, ensuring that Unix file system permissions match.

**Comment by Hellmudth** [comment]
OK, that easy. 
Thank you for quick support.
