### ISSUE TITLE
use the OpenCage geocoder rather than Google for reverse geocoding

### ISSUE THREAD

**Issue by freyfogle** [owntracks/recorder#202]
Hi,
I'm one of the people behind the [OpenCage geocoder](https://geocoder.opencagedata.com). 
I'd love to add the option to use our geocoder rather than Google's for the reverse lookups. 
Main difference is that our data sources are open data, primarily OpenStreetMap. 

Before I dive in, is there some philosophical reason Google is currently the default and is there some objection to adding other service providers? I assume not, but thought I should first ask. 

Looking at the code, the reverse geocoding seems to be done in `geo.c`
It has been a long time since I worked in C and I'm still working to suppress some of the memories.
Does anyone out there want to help on this work? I do not anticipate it being particularly difficult, the model is exactly the same, an https request to api.opencagedata.com and then parse the JSON to get the relevant information. **I am happy to pay someone to help with this work**, as I suspect it will go exponentially faster than if I do it. 

There are two optional features that OpenCage offers that might be particularly relevant to OwnTracks users:

1. if you add the `no_record` parameter to the request the query is not logged on the OpenCage server
2. if you add the `abbrv` parameter the formatted address is abbreviated (ie "Main Street" becomes "Main St")

But the main reason I think people should be interested is that by using Google's reverse geocoder you are agreeing to Google's terms and conditions, which may not be what you want. For example, this implies you may only display the geocodes on a Google map. See the "[Displaying a map](https://developers.google.com/maps/documentation/geocoding/policies)" section of their policies. 

Please let me know if any objection to this work and if anyone would like to help. 
Thanks.

**Comment by freyfogle** [comment]
Great stuff @jpmens and thanks for the fast follow up. 

The Lua plugin approach sounds perfect - technically, and because it provides the emotional benefit of deleting C code!  Only negative is that I have no experience with Lua at all. Could be a good excuse to learn. As said though, happy to pay for someone with relevant experience to take this forward more quickly. As a separate, but related, matter I'm happy to pay anyone who wants to open source a stand alone Lua module (or whatever the equivalent concept in Lua is called) to add to [our libraries page](https://geocoder.opencagedata.com/code)). 

BTW - our address abbreviations are all open source if anyone wants to help contribute and add common abbreviations in their language. Please [have a look here](https://github.com/OpenCageData/address-formatting/tree/master/conf/abbreviations). As you can imagine, trying to cover the whole world is non-trivial.

**Comment by binarybucks** [comment]
Sorry for hijacking this thread, but you got me interested. 
I was looking to replace the Google Geocoding provider for the Android app aswell because it often fails with no reason. You don't happen to have a Java module that I oversaw?

**Comment by freyfogle** [comment]
My dear @binarybucks, ask and you shall receive! 

There are two different open sourced Java modules for the OpenCage geocoder:

https://github.com/moberwasserlechner/jopencage
https://github.com/hakan42/java-opencage-geocoder

I'm not a Java programmer myself, so hard for me to comment on the pros and cons of each. I do know jopencage is well maintained and the author seems very responsive. 

See the full list of libraries here: https://geocoder.opencagedata.com/code
I hope that's useful.

**Comment by rjp** [comment]
If no-one else wants to pick this up, I've got some Lua experience and might be able to work on this in the near future.

**Comment by freyfogle** [comment]
Hola @rjp, 

there have been no other takers. Happy to pay you (a bit, we're a small business, so please don't start planning your retirement just yet) to do this work. I see your email is on your github profile, I will send you a mail.

thanks for your help!

**Comment by jpmens** [comment]
Before you both get rich/poor respectively, I'd like to lay down some guidelines.

1. This is an Open Source project, and as such all code will become Open Source.
2. Whether or not we take the resulting pull request is up to us
3. I would very much like to see this happen, and will try to assist with information where I can.
4. I would like to see the Lua reverse-geo decoder usable with Google (as we do currently), Nominatim, and of course, OpenCage, etc.
5. The Lua function should get (at least) `lat`, `lon` and return a single string with a "not too long" address in it. We can also, say, have the function return a _simple_ JSON object with that string and maybe a few more details. (Some people have requested basic weather information; if the reverse geo provides it, we could reuse it.)

It's late here. I'm sure I've forgotten lots.

**Comment by freyfogle** [comment]
Fair points, all of them. We don't have weather data I'm sorry to say. We do have a fair amount of other data about each location that we also return - check out the list of [what we call annotations](https://geocoder.opencagedata.com/api#annotations).

**Comment by jpmens** [comment]
@rjp ping. Are you still up for this?

**Comment by freyfogle** [comment]
We emailed a bit a few months ago but then he went silent unfortunately. That said, I understand that sometime life throws higher priorities at you. 

Nevertheless, would be great to go forward with anyone else who wants to take on this project. 
Any takers? 

BTW - we continue to add useful ([or perhaps less useful](https://blog.opencagedata.com/post/new-annotation-flag), depending on your opinion) to our geocoding results.

**Comment by freyfogle** [comment]
Hi, 

an update. We now have [a lua library for accessing the OpenCage API](https://github.com/nmdguerreiro/lua-opencage-geocoder). Anyone  out there want to use that to take this forward?

**Comment by kukki** [comment]
I want to use OpenCage API as the Google rev-geo is incorrect in my country. But I am new to lua. Could you please guide me how to use it and integrate to ot-recorder?

**Comment by freyfogle** [comment]
Hi @kukki I wish I could guide you. I know neither Lua, nor do I have any understanding of the OwnTracks code. Would be happy to pay (in money or free geocoding) anyone who wants to put together a pull request that supports this. Sorry, wish I could do it myself.

**Comment by jpmens** [comment]
@freyfogle I believe this will please you: we now fully (and more! :-) support OpenCage in our Recorder [using Lua](https://github.com/owntracks/recorder/blob/master/doc/OPENCAGE.md) but also natively in C which has enabled us to turn OpenCage in a first-class citizen for us.

We have also updated the documentation (I hope consistently) to indicate we now definitely recommend OpenCage.

**Comment by freyfogle** [comment]
Bravo!!!! Great that it went so easily. I'm just heading to the airport for a long weekend away, but will publish a blog post about this on the OpenCage blog early next week. Well done!

**Comment by binarybucks** [comment]
@freyfogle might be delighted that I added a first working prototype for OpenCage support to the Android app

**Comment by freyfogle** [comment]
Current mood here at OpenCage HQ:

![zelte-hp](https://user-images.githubusercontent.com/351074/40052408-1d60f6ec-583e-11e8-908e-203e84f96189.jpg)

**Comment by binarybucks** [comment]
@freyfogle is there a way to receive a more brief response without e.g. `documentation`, `licenses`,`rate`,`stay_informed`, `thanks`,`timestamp`, `created_unix`?
A normal response is averaging at 1.1kb with one entry where I'm just interested in the `formatted` output.

**Comment by binarybucks** [comment]
Yes, it's 1.1k with no_annotations=1. 
I've sent you an email.

**Comment by jpmens** [comment]
A test on random location in Germany returns 1,868 bytes; the formatted address for this entry: 
82 bytes.

```json
{
  "formatted": "Stadtwerke Bonn, Theaterstra\\u00dfe 24, 53111 Bonn, Germany"
}
```

I was also going to ask because I see a bunch of advantages:
- less volume of data to transport
- less data to parse == faster
- less data for OpenCage to produce == faster

But of course I’m an #oldfart and I hate seeing bits wasted. :-)

**Comment by freyfogle** [comment]
yes, the formatted address length of course depends on the location.
Note you can also make it German by using the optional `language=de` parameter. 
Please see: https://geocoder.opencagedata.com/api#language

Re: the data volume to parse, surely the cost of parsing such a small amount of JSON is largely in setting up a parser. I would be surprised if plus or minus 1000 chars makes a difference of even a millisecond on any modern hardware.

Re: the data volume to transport, the response is of course gzip'd by the server if the client supports that, which every modern client does. 

Re: the data volume to produce, again I suspect the time savings would not even be measurable. These are mainly static fields we add to the structure.

We have to offset all these "wins" with our most expensive resource: engineering time. To build, document, and most of all to maintain (we already have several different output formats). Also of course the engineering time of other users in understanding what yet another optional parameter does. We try very hard to keep things as simple as possible for developers. 

So - after some internal discussion - our conclusion is this is a bit of a false optimization. We have decided better to just keep the response as is.  Hope you can follow our reasoning. Thanks for raising it though, please keep the ideas coming - that said, please do so by mail to support@opencagedata.com not just to me personally. Thanks.

**Comment by jpmens** [comment]
Thanks @freyfogle: we've actually read the fine manual :-)

**Comment by kproc** [comment]
Is it possible to use a non-google geocoder now?

**Comment by freyfogle** [comment]
yes, has been possible for several years now

**Comment by jpmens** [comment]
@kproc this is documented; a search for "opencage" in the README would have led you to https://github.com/owntracks/recorder/blob/master/doc/OPENCAGE.md
