### ISSUE TITLE
Can't install on debian wheezy

### ISSUE THREAD

**Issue by maxibelino** [owntracks/recorder#204]
can't install it on my Pi:

`sudo apt-get install ot-recorder
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ot-recorder : Depends: libsodium13 but it is not installable
E: Unable to correct problems, you have held broken packages.
`

any tip?
thanks
Max

**Comment by jpmens** [comment]
We no longer support packages on Wheezy for Recorder. You can probably build from source if you need it, after finding an appropriate libsodium -dev package.

Alternatively you could try our Docker image.

**Comment by juzam** [comment]
if you are going to build from source you could try these unofficial wheezy/armhf packages:
[0ptr Raspbian repo](http://0ptr.link/raspbian/pool/main/libs/libsodium/)
