### ISSUE TITLE
leaflet 1.0.2 CDN hosting causes 'nosniff' problems leading to no map on Firefox 54

### ISSUE THREAD

**Issue by rjp** [owntracks/recorder#206]
Because `https://unpkg.com/leaflet@1.0.2/dist/leaflet.js` is being served as `text/plain`, not `application/javascript`, and also has the `X-Content-Type-Options: nosniff` header, Firefox 54.0.1 rejects it.

Bizarrely, `https://unpkg.com/leaflet@1.2.0/dist/leaflet.js` is served as `application/javascript` - it might just be as simple as swapping to that version for a fix.

**Comment by jpmens** [comment]
Closed via #207
