### ISSUE TITLE
Cannot install on i386

### ISSUE THREAD

**Issue by pdupreez** [owntracks/recorder#208]
Following the install instructions, I get the following error:

Skipping acquire of configured file 'main/binary-i386/Packages' as repository "http://repo.owntracks.org/debian jessie InRelease' doesn't support architecture 'i386'

How do I get beyond this?

**Comment by jpmens** [comment]
We do not support i386 packages, but you can build from source as documented in the project's README.

**Comment by pdupreez** [comment]
Aah, that will be a way around. Thanks for the response
