### ISSUE TITLE
deb package for Stretch on raspberry pi (armhf) is missing from repo

### ISSUE THREAD

**Issue by Aquariu** [owntracks/recorder#209]
Issue;
On the repo [here](http://repo.owntracks.org/debian/pool/main/o/ot-recorder/)
Packages exist for Debian 7 and 8 on armhf, for Debian 8 and 9 on AMD64, but not Debian 9 on armhf.

Kind regards,

Olivier

**Comment by Aquariu** [comment]
Dear all,

Is there a way to get a precompiled armhf Debian Stretch package ? The issue above leads me to believe one package is missing from the repo.

Kind regards,

Olivier

**Comment by gdgeist** [comment]
Piling on here

**Comment by canoxnet** [comment]
I hope that someday there will be a deb package for Raspbian.

**Comment by campinoXL** [comment]
same here, would be very nice to get this package, thanks!

**Comment by jpmens** [comment]
Recorder version 0.7.3 for 9.1 armhf is now in the repository. We'd appreciate you testing.

**Comment by jpmens** [comment]
0.7.4 is available in the repository now. I had to fix dependency for libsodium (thanks to @juzam)
