### ISSUE TITLE
table view, last "face" added applies to all devices of user xxx

### ISSUE THREAD

**Issue by juzam** [owntracks/recorder#212]
scenario: user xxx has many owntracks devices with topics like:

- owntracks/xxx/device1
- owntracks/xxx/device2
etc

if one face is applied for `device1` and subsequently for `device2` recorder displays the same name and icon for all the devices of the `xxx` user

tested under docker (with latest sources from github)

**Comment by jpmens** [comment]
That is currently correct. This was [rolled back here](https://github.com/owntracks/recorder/commit/5d432c69a150b2d8bfaeca132e57b3327152dbea) but is not yet in packages. You can manually move the file from `cards/user/user.json` to `cards/user/device/user-device.json` to fix.

**Comment by jpmens** [comment]
After submitting my comment I read your updated issue. This ought to not be the case in actual sources, as shown in the link to the pertaining commit.

**Comment by juzam** [comment]
I stand corrected.  I've mistakenly mixed up my instances. the docker one is not compiled from source (I had one while I was testing stretch but that's no more the case) so your first comment applies. 

sorry for the wrong report.
