### ISSUE TITLE
Reverse Geo API Key

### ISSUE THREAD

**Issue by veames** [owntracks/recorder#214]
Hi, I cannot seem to find the config where I can  enter my Google API key for reverse Geocoding lookups, can someone help?

**Comment by ckrey** [comment]
Look for `--geokey` or `OTR_BROWSERAPIKEY` right here:

https://github.com/owntracks/recorder

**Comment by veames** [comment]
Thanks, --geokey works fine, however OTR_BROWSERAPIKEY and OTR_GEO key didn't.

**Comment by jpmens** [comment]
When you say `OTR_BROWSERAPIKEY` and `OTR_GEO` didn't work: what did you try and how did you try?

**Comment by veames** [comment]
edited config.mk, added 
`OTR_GEOKEY ?= MYKEY`
and
`OTR_BROWSERAPIKEY ?= MYKEY`

Neither of those options actually used my key for the geolookup, but when I use --geokey at the commandline it works.

**Comment by jpmens** [comment]
What did you type that into? I.e. where?

**Comment by jpmens** [comment]
They’re environment variables which should be set in the environment before the Recorder starts.

**Comment by veames** [comment]
My bad. Didn’t realize they were in environment. Thanks
