### ISSUE TITLE
leaflet 1.02 not available anymore from unpkg.com

### ISSUE THREAD

**Issue by ashmodai6** [owntracks/recorder#216]
version 1.02 is not available anymore online making the script fails when tying to display points on a map.

**Comment by jpmens** [comment]
Which script fails?

**Comment by ashmodai6** [comment]
from http://ip_adress:8080/owntracks/ select for exemple 12h history result in blank page
http://ip_adress:8080/owntracks/map/index.html?user=user&device=device?id&format=geojson&from=2017-12-05T07:34
Looking at the console I see that 
07:34:49 GET https://unpkg.com/leaflet@1.0.2/dist/leaflet.js net::ERR_ABORTED
It returns a 404

**Comment by jpmens** [comment]
It appears to me to be something specific to your environment:

```
$ curl -v -O https://unpkg.com/leaflet@1.2.0/dist/leaflet.js
...
< HTTP/1.1 200 OK
< Date: Tue, 12 Dec 2017 19:50:18 GMT
< Content-Type: application/javascript; charset=utf-8
< Content-Length: 137136

$ ls -l leaflet.js
-rw-r--r--  1 jpm  wheel  137136 Dec 12 20:50 leaflet.js
```

That version is available from here.

Please check the connectivity from your location to unpkg.com

**Comment by ashmodai6** [comment]
Indeed vers 1.2.0 is available but owntrack refers to version 1.0.2 ...

**Comment by jpmens** [comment]
It does not in the master branch: https://github.com/owntracks/recorder/blob/3aa37e828a094ee21518ddb40ff47507eebe029c/docroot/map/index.html#L39

**Comment by ashmodai6** [comment]
Thanks ! I see in GitHub that it was updated 4 months ago but it seems the packages which are pointed out in the installation guide on the same GitHub have not been updated since my install (dated 2 weeks ago) still points to the old leaflet.js version. I will recompile from sources then.
