### ISSUE TITLE
Google Maps offers SignedInNotSupported warning on LiveMap as signed-in is deprecated

### ISSUE THREAD

**Issue by MattWalston** [owntracks/recorder#217]
From Google's Docs:

The signed_in parameter has been deprecated and is not supported on the version of the Google Maps JavaScript API you are using. This won't prevent the Google Maps JavaScript API from working, but the behavior of your application may change, if you rely on signed-in features.

Not a functional concern but didn't want to loose track on it.  I'll be digging in this weekend and will probably offer a PR on this one after I identify what if any signed-in features are used.

**Comment by jpmens** [comment]
I don't think we use any signed-in features; you should be safe just removing the parameter.
