### ISSUE TITLE
"Incorrect protocol" error

### ISSUE THREAD

**Issue by tva164** [owntracks/recorder#219]
Hello, brand new to Recorder and this kind of stuff so please bear with me if I'm not seeing the obvious.  Installed ot-recorder on Raspbian Jessie, everything went smootly until I started the service. Messages as follows:

> sudo service ot-recorder status -l
● ot-recorder.service - OwnTracks Recorder
   Loaded: loaded (/etc/systemd/system/ot-recorder.service; enabled)
   Active: active (running) since Tue 2018-01-09 22:36:59 UTC; 12h ago
 Main PID: 589 (ot-recorder)
   CGroup: /system.slice/ot-recorder.service
           └─589 /usr/sbin/ot-recorder

> Jan 10 02:45:47 pimqtt ot-recorder[589]: ot-recorder[589]: Subscribing to owntracks/# (qos=2)
> Jan 10 03:10:46 pimqtt ot-recorder[589]: ot-recorder[589]: Disconnected. Reason: 0x1 [Connection refused: incorrect protocol version]
> Jan 10 03:10:46 pimqtt ot-recorder[589]: Disconnected. Reason: 0x1 [Connection refused: incorrect protocol version]
> Jan 10 03:10:46 pimqtt ot-recorder[589]: Disconnected. Reason: 0x1 [Connection refused: incorrect protocol version]
> Jan 10 03:10:46 pimqtt ot-recorder[589]: MQTT connection: rc=7 [The connection was lost.] (errno=0; Success). Sleeping...
> Jan 10 03:10:47 pimqtt ot-recorder[589]: ot-recorder[589]: Disconnected. Reason: 0x1 [Connection refused: incorrect protocol version]
> Jan 10 03:10:47 pimqtt ot-recorder[589]: ot-recorder[589]: MQTT connection: rc=7 [The connection was lost.] (errno=0; Success). Sleeping...
> Jan 10 03:12:02 pimqtt ot-recorder[589]: Subscribing to owntracks/# (qos=2)
> Jan 10 03:12:02 pimqtt ot-recorder[589]: ot-recorder[589]: Subscribing to owntracks/# (qos=2)
> Jan 10 10:39:09 pimqtt systemd[1]: Started OwnTracks Recorder.

I have updated /etc/default/ot-recorder with my config preferences.  OTR_CAFILE is commented out.  

Thanks in advance for helping.

**Comment by jpmens** [comment]
Please describe which MQTT broker you are using. I am seeing 

```
 Disconnected. Reason: 0x1 [Connection refused: incorrect protocol version]
```

**Comment by tva164** [comment]
Thanks for your quick response.  I am using cloudmqtt, and have updated OTR_HOST, OTR_PORT, OTR_PASS, OTR_QOS, OTR_HTTPPORT accordingly.

**Comment by jpmens** [comment]
If so, and if Recorder is receiving your publishes ... what's the problem?

**Comment by tva164** [comment]
Publisher to Broker is fine.  Broker to recorder is where I get the protocol error, in other words, ot-recorder which is sitting in a raspberry pi is not connecting to the broker and receiving messages.  I am not sure why, I have checked the config settings in /etc/default/ot-recorder are correct.  Thanks.

**Comment by jpmens** [comment]
cloudMQTT does funny things with port numbers, IIRC. I cannot help you with the specifics because we don't use public brokers. There might be a hint or two [in this](https://community.home-assistant.io/t/mqtt-working-mosquitto-cloudmqtt-bridge/1830/16) for you. Please note you might require a specific clientID for the Recorder to connect to cloudMQTT.

**Comment by tva164** [comment]
Thanks @jpmens I'll give it a go and if it becomes too painful, I'll just install a private mosquitto on the same Pi and go from there.  Hopefully that's simpler.

**Comment by jpmens** [comment]
I've just successfully connected to cloudMQTT using Recorder:

```
Jan 10 16:19:32  ot-recorder[39076] <Debug>: version 0.7.2 starting with STORAGEDIR=/tmp/JP3
Jan 10 15:19:32  ot-recorder[39076] <Info>: connecting to MQTT on xxxx.cloudmqtt.com:10682 as clientID otrpingping5 without TLS
Jan 10 15:19:33  ot-recorder[39076] <Info>: Using access log at JP/access.log
Jan 10 15:19:33  ot-recorder[39076] <Info>: HTTP listener started on 0.0.0.0:8086
Jan 10 15:19:33  ot-recorder[39076] <Info>: Using storage at /tmp/JP3 with precision 7
Jan 10 15:19:33  ot-recorder[39076] <Debug>: Subscribing to owntracks/# (qos=2)
- 15:20:44 owntracks/jpm/moto3                 t=u tid=JJ loc=48.85833,3.29513 [FR] D6, 77510 Bellot, France (u0d)
```

The shell script I used:

```
#!/bin/sh

export OTR_USER=xxxxxxxx
export OTR_PASS=yyyyyyyyyyyyy

exec ./ot-recorder \
        -S /tmp/JP3 \
        --http-host 0.0.0.0 \
        -i otrpingping5 \
        --port 10682 \
        --host xxxx.cloudmqtt.com \
        --port 10682 \
        'owntracks/#' 
```

**Comment by jpmens** [comment]
For the record: it works fine with TLS as well.

```
export OTR_USER=xxxx
export OTR_PASS=yyyy
export OTR_HOST=xxxx.cloudmqtt.com
export OTR_PORT=20682	# TLS
export OTR_CAFILE=...../ca-certificates.crt
```
