### ISSUE TITLE
delete data with lon 0 lat 0

### ISSUE THREAD

**Issue by chr55** [owntracks/recorder#220]
I added some data manually into owntracks recorder via MQTT. Unfortunately a few rows had lon 0 and lat 0 and now show on the map in the sea off Africa. 

using this:
ocat --device iphone --user chris --from 2012-12-02 --to 2012-12-03

I am able to return the bad data, 
{"lon":0,"lat":0,"t":"u","tst":1354458161,"_type":"location","tid":"CH","ghash":"7zzzzzz","isorcv":"2012-12-02T14:22:41Z","isotst":"2012-12-02T14:22:41Z","disptst":"2012-12-02 14:22:41"},{"lon":0,"lat":0,"t":"u","tst":1354458173,"_type":"location","tid":"CH","ghash":"7zzzzzz","isorcv":"2012-12-02T14:22:53Z","isotst":"2012-12-02T14:22:53Z","disptst":"2012-12-02 14:22:53"}

I got rid of the ghash using this 
ocat --dump | grep '7zzzzzz' | awk '{printf "%s DELETE\n", $1; }' | ocat --load

The locations remain on my map. Can anyone help me delete these bad locations from my database?

thank you!

**Comment by jpmens** [comment]
In the `<SPOOLDIR>` of the Recorder (if you installed from packages that ought to be `/var/spool/owntracks/recorder` you should find a directory called `store/rec/` under which you'll find your username and device, so `store/rec/chris/iphone`.

Therein you'll find files corresponding to year-month of the location publishes, e.g. `2012-12.rec`. Edit that file in a text editor (_nano_, _vim_, etc.), locate the offending lines and delete them, and save the file back.

It's a good idea for you to make. a backup copy of the file prior to starting the operation (`cp 2012-12.rec 2012-12.rec.copy` or something along those lines).

You'll find that if you then refresh your map, those points will have vanished.

**Comment by chr55** [comment]
Thank you! That worked.
