### ISSUE TITLE
Problems to compile on FreeBSD 11.1-p8

### ISSUE THREAD

**Issue by vsatmydynipnet** [owntracks/recorder#228]
I am running Owntracks on IOS against Mosquitto MQTT. Actually I am to stupid to compile Owntracks recorder on FreeeBSD 11.1

Even with installing the packages mentioned in config.mk and uncommenting the FreeBSD part on top it stops with multiple errors starting at line 23.

Would love to read any short step-by-step setup guide on FreeBSD.

Thank you so much.

**Comment by jpmens** [comment]
Thanks for your report. I really wonder what you think we're supposed to imagine by _multiple errors starting at line 23_. ? Pardon the sarcasm, but you should neatly format those as code here in Github (enclose between two lines of three backticks each) so that we can see what you see.

I don't think you're too stupid. Just help us to help you and we can all profit from that. :-)

**Comment by vsatmydynipnet** [comment]
Hi, sorry, i forgot to add my notes i made while trying to build it.

## Owntrack Recorder on FreeBSD problem

### System:

FreeBSD 11.1-RELEASE-p9 (GENERIC) #0

using pkg system, no ports tree on local system

## Running

Lan side Mosquitto of a secure bridged Mosquitto setup

Home Assistan .67

Owntrack reports to lan side mosquitto, which is bridged to lan side mosquitto, and tracked bey Home Assistnt to handle events, based on the location of the device.

So far so good, but there is no waypoints of the device, so i tried to compile Owntracks recorder on this box.

## Pre Setup

Cloned to local

https://github.com/owntracks/recorder.git

Install required packages:

pkg install lmdb curl libconfig

Uncomment FreeBSD entries in config.mk after copying from .in:

#
CC      = clang
CFLAGS += -I/usr/local/include
MORELIBS += -L /usr/local/lib
FREEBSD ?= yes
# -- end FreeBSD

Changed settings in config.mk

# Location of optional default configuraton file
# FreeBSD configs are in /usr/local/etc
CONFIGFILE = /usr/local/etc/ot-recorder

# Optionally specify the path to the Mosquitto libs, include here
# mosquitto libs/inc is in /usr/local ...
MOSQUITTO_INC = -I/usr/local/include
MOSQUITTO_LIB = -L/usr/local/lib
MORELIBS += # -lssl

# Running make as root (csh shell is default in freebsd)  resultis in:

Owntracks/recorder-master# make
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 23: Missing dependency operator
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 27: Need an operator
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 29: Need an operator
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 32: Missing dependency operator
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 36: Need an operator
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 38: Missing dependency operator
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 39: warning: duplicate script for target "ifeq" ignored
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 35: warning: using previous script for "ifeq" defined here
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 39: warning: duplicate script for target "(yes,yes)" ignored
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 35: warning: using previous script for "(yes,yes)" defined here
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 40: Need an operator
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 42: Missing dependency operator
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 43: warning: duplicate script for target "ifeq" ignored
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 35: warning: using previous script for "ifeq" defined here
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 43: warning: duplicate script for target "(no,yes)" ignored
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 26: warning: using previous script for "(no,yes)" defined here
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 44: warning: duplicate script for target "ifeq" ignored
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 35: warning: using previous script for "ifeq" defined here
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 44: warning: duplicate script for target "(no,yes)" ignored
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 26: warning: using previous script for "(no,yes)" defined here
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 45: warning: duplicate script for target "ifeq" ignored
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 35: warning: using previous script for "ifeq" defined here
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 45: warning: duplicate script for target "(no,yes)" ignored
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 26: warning: using previous script for "(no,yes)" defined here
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 46: Need an operator
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 48: Missing dependency operator
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 49: warning: duplicate script for target "ifeq" ignored
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 35: warning: using previous script for "ifeq" defined here
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 49: warning: duplicate script for target "(no,yes)" ignored
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 26: warning: using previous script for "(no,yes)" defined here
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 50: warning: duplicate script for target "ifeq" ignored
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 35: warning: using previous script for "ifeq" defined here
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 50: warning: duplicate script for target "(no,yes)" ignored
make: "/usr/home/ownuser/Owntracks/recorder-master/Makefile" line 26: warning: using previous script for "(no,yes)" defined here

**Comment by vsatmydynipnet** [comment]
SOLVED! PLEASE MARK THIS IN THE DOCU !!!
On FreeBSD you must install gmake and compile with gmake !!!!
Thank you!
