### ISSUE TITLE
FreeBSD 11.1 TLS /Client Certs ssl error

### ISSUE THREAD

**Issue by vsatmydynipnet** [owntracks/recorder#229]
I am sorry, there is one more problem.

I compiled ot-recorder now and basicly it looks good. Problem is connection to Moquitto which requires certificate and user+pass in my setup. I run my own CA and created a SHA512/4096 bit client certificate as I have done for all other clients.

If I use the certificate and the user/pass credentials with MQTTfx Software (Cool MQTT test and debugging software, connectivity is fine with tlsv1 and tlsv1.2. So pem formatted certs should be fine. There are a few more clients on this one including Home Assistant. All using the same cert creation method.

I created an FreeBSD start/stop script and edited the default configuration with ca and cert/key location - full path/filename and User/Pass credentials.

Starting ot-recorder brings up an error:

Starting service
ot-recorder[5743]: version 0.7.5 starting with STORAGEDIR=/var/spool/owntracks/recorder/store
ot-recorder[5743]: connecting to MQTT on localhost:8883 as clientID ot-recorder-ANONYM.com-5743 with TLS
ot-recorder[5743]: HTTP listener started on 127.0.0.1:8083
ot-recorder[5743]: Using storage at /var/spool/owntracks/recorder/store with precision 8
ot-recorder[5743]: MQTT connection: rc=8 [A TLS error occurred.] (errno=0; No error: 0). Sleeping...
^CGoing down on signal 2

##
My full syslog shows:

Apr 17 13:02:15 mqtt ot-recorder[5906]: connecting to MQTT on localhost:8883 as clientID ot-recorder-ANONYM.com-5906 with TLS
Apr 17 15:02:15 mqtt mosquitto[5423]: New connection from 127.0.0.1 on port 8883.
Apr 17 13:02:15 mqtt ot-recorder[5906]: HTTP listener started on 127.0.0.1:8083
Apr 17 13:02:15 mqtt ot-recorder[5906]: Using storage at /var/spool/owntracks/recorder/store with precision 8
Apr 17 15:02:15 mqtt mosquitto[5423]: OpenSSL Error: error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error
Apr 17 15:02:15 mqtt kernel: Apr 17 15:02:15 mqtt mosquitto[5423]: OpenSSL Error: error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error
Apr 17 13:02:15 mqtt ot-recorder[5906]: MQTT connection: rc=8 [A TLS error occurred.] (errno=0; No error: 0). Sleeping...
Apr 17 15:02:15 mqtt mosquitto[5423]: OpenSSL Error: error:140940E5:SSL routines:ssl3_read_bytes:ssl handshake failure
Apr 17 15:02:15 mqtt kernel: Apr 17 15:02:15 mqtt mosquitto[5423]: OpenSSL Error: error:140940E5:SSL routines:ssl3_read_bytes:ssl handshake failure
Apr 17 15:02:15 mqtt mosquitto[5423]: Socket error on client <unknown>, disconnecting.

ldd of ot-recorder shows linking agains libssl is done.

Any ideas are greatly appreciated.

**Comment by jpmens** [comment]
This bit looks surprising: `tlsv1 alert internal error`

Do you limit the TLS versions on the Mosquitto broker side? 
Have you correctly set `$OTR_CAFILE` respectively in the environment or in the defaults file? Is the PEM file readable by `ot-recorder`?

**Comment by vsatmydynipnet** [comment]
As mentioned, connection with these certs and credentials with MQTTfx works fine.

Certs are esported as pem files from my own CA.

I set the place for default file in config.mk and if i remove the file ot-recorder complains about it:
 Cannot read defaults from /usr/local/etc/ot-recorder/ot-recorder.default: No such file or directory

If file is OTR_PORT=8883
OTR_USER="anon"
OTR_PASS="anon"
OTR_CAFILE="/usr/local/etc/ot-recorder/Certs/MQTT.SBG.LAN.crt"
OTR_CERTFILE="/usr/local/etc/ot-recorder/Certs/otrecorder.crt"
OTR_KEYFILE="/usr/local/etc/ot-recorder/Certs/otrecorder.pem"
OTR_TOPICS="owntracks/#"in place the following settings are entered:

all files are 640 / root:wheel and ot-recorder is startet as root while testing
i can ls all files if i copy the addies to the shell

These 3 files works with MQTTfx test and debug software using tlsv1 and tlsv1.2
The way certs are created works with Home Assistant, MQTTfx and Owntracks on IOS and Android

The CA file is a full chain file containing 2 certs as full cjhain. same file is used with mosquitto and other clients

**Comment by jpmens** [comment]
Just checking: you are sure `ot-recorder` isn't running _suid_? Can you please show me an `ls -l .../ot-recorder`?

As background: we do this quite a lot, so I'm a bit stumped. I also can't test at the moment, as I'm on the road

**Comment by vsatmydynipnet** [comment]
ls -l /usr/local/sbin/ot-recorder
-rwxr-xr-x  1 root  wheel  283096 Apr 17 11:19 /usr/local/sbin/ot-recorder
It doesn't run suid, so root permitions should work.

**Comment by vsatmydynipnet** [comment]
I set my mosquitto to not require a certificate and removed 
##OTR_CERTFILE="/usr/local/etc/ot-recorder/Certs/otrecorder.crt"
##OTR_KEYFILE="/usr/local/etc/ot-recorder/Certs/otrecorder.pem"
from default config.
error also happens with CA file only:

Apr 17 17:14:59 mqtt kernel: Apr 17 17:14:59 mqtt mosquitto[7948]: OpenSSL Error: error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error
Apr 17 15:14:59 mqtt ot-recorder[7964]: MQTT connection: rc=8 [A TLS error occurred.] (errno=0; No error: 0). Sleeping...

**Comment by vsatmydynipnet** [comment]
#######################################
## SOLUTION BUT NEEDS TO BE CHECKED ##
#######################################

with this patch connection is possible and mosquitto log looks good. 
need to hard check diff PEER and NONE, thats why i don't close here.

--- recorder.c.ORIG	2018-02-13 12:44:40.000000000 +0100
+++ recorder.c.VS	2018-04-17 17:52:25.103723000 +0200
@@ -1669,7 +1669,7 @@
 			}
 
 			mosquitto_tls_opts_set(mosq,
-				SSL_VERIFY_PEER,
+				SSL_VERIFY_NONE,
 				NULL,                   /* tls_version: "tlsv1.2", "tlsv1" */
 				NULL                    /* ciphers */
 				);

**Comment by vsatmydynipnet** [comment]
It looks like the problem is the connection to localhost. teh cert for sure is for mydom.tld . I am checking that actually. Map is available now, reversed proxy is still to do, but looks ok now. Need to test if connection to domain.tls instad of localhost solves the problen with original recorder.c

**Comment by jpmens** [comment]
I think you said above you run your own CA, so you can create a Mosquitto server cert which has SAN (subjAltNames) in it, such as `DNS:mydomain.com,IP:127.0.0.1,IP:10.0.12.3,DNS:localhost` etc. in it. That will certainly fulfill our requirement.

**Comment by rajil** [comment]
@vsatmydynipnet Do you mind posting your FreeBSD rc.d scripts? I would like to set this up in a jail.

**Comment by jpmens** [comment]
Good idea: I'll gladly take an example script and we can put it in `contrib/`.

**Comment by vsatmydynipnet** [comment]
Enclosed the script:

FreeBSD notes:

- must use gmake
- place script in /usr/local/etc/rc.d/ot-recorder
- creates pid file out of $! to make restart and stop possible
- note regarding line: # REQUIRE: LOGIN mosquitto hass 
  remove mosquitto and hass if not setup on this box, but let LOGIN there
  if mosquitto runs on same box REQUIRE is a must! hass is Home Assistant

 #!/bin/sh

# $FreeBSD$
#
# PROVIDE: otrecorder
# REQUIRE: LOGIN mosquitto hass
# KEYWORD: shutdown
#
# Add these lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:

. /etc/rc.subr

name=otrecorder
rcvar=${name}_enable

start_cmd=${name}_start
stop_cmd=${name}_stop

load_rc_config $name
: ${otrecorder_enable:=NO}
: ${otrecorder_pidfile:=/var/run/otrecorder.pid}

command=/usr/local/sbin/ot-recorder
#command_args="--debug --norevgeo"
command_args="--debug --label MY-MAP"

otrecorder_start()
{
  if [ -f $otrecorder_pidfile ] && kill -0 $(cat $otrecorder_pidfile) >/dev/null 2>&1 ; then
    echo 'Service already running'
    return 1
  fi
  echo 'Starting service after 10 secs so mosquitto is up'
  sleep 10;
  $command $command_args &
  echo $! > ${otrecorder_pidfile}
  echo 'Service started'
}

otrecorder_stop()
{
  if [ ! -f $otrecorder_pidfile ] || ! kill -0 $(cat $otrecorder_pidfile) >/dev/null 2>&1 ; then
    echo 'Service not running'
    return 1
  fi
  echo 'Stopping service'
  kill $(cat $otrecorder_pidfile)
  while ps -p $(cat $otrecorder_pidfile) >/dev/null 2>&1 ; do sleep 1;done
  echo 'Service stopped'
}

run_rc_command "$1"
