### ISSUE TITLE
Points from one user/device from/to date listed as in TABLE of current locations

### ISSUE THREAD

**Issue by vsatmydynipnet** [owntracks/recorder#230]
Hi,

I found ocat listing 

ocat --user iphone1 --device iphone1 --format csv 

lists the track points of one device. Is there a ways to list this points in the way:

TABLE of current locations

lists the last locations. This listing would have all I want, but I need this one for --user x --device x from date to date.

I was reading the docu, but found no http way, only ocat export.

Thank you!

**Comment by jpmens** [comment]
I _assume_ you're asking whether this exists in the Web interface. No, it doesn't, but we would take a pull request which adds that.

**Comment by jpmens** [comment]
Closing for lack of reaction.
