### ISSUE TITLE
OTR_CAPATH env should enable TLS

### ISSUE THREAD

**Issue by MyIgel** [owntracks/recorder#232]
When defining OTR_CAPATH as an env variable the recorder connects without TLS
It would be useful if it could also enable TLS as OTR_CAFILE does

**Comment by jpmens** [comment]
I'd appreciate you testing this.

**Comment by MyIgel** [comment]
Thank you for the fast fix, it works!

**Comment by MyIgel** [comment]
@jpmens When will the 0.7.5 Version be released?

**Comment by jpmens** [comment]
Do you know what the typicall "Open Source response" to that question is? :-) 

> when it's ready

In this case the response is: when I'm home and have an hour to spare and I remember. Which will not be within the next fortnight.

**Comment by jpmens** [comment]
Packages for 0.7.6 have been built.
