### ISSUE TITLE
Google Geocoding Pricing Change

### ISSUE THREAD

**Issue by wasmitnetzen** [owntracks/recorder#233]
Google announced a pricing change for their API. The information is not very clear, but it seems to me that calls without an API key are not allowed anymore from June 11th on, and for requesting an API key, giving out credit card information is mandatory:

* https://cloud.google.com/maps-platform/pricing/sheet/
* https://news.ycombinator.com/item?id=16980166

Also, the new limit for free geocoding calls is now 40 000 calls per month (previously, it was 2500 per day, which is around 75 000 per month).

There are changes necessary as not providing an API key should probably throw an error. Also, this should be reflected in the documentation. An alternative could be throwing out the Google Geocoder, as per #202.

**Comment by jpmens** [comment]
Thank you for writing this issue. We're aware of this and are discussing how to best handle this change. Any suggestions are currently welcome.

**Comment by jpmens** [comment]
@wasmitnetzen we now fully support OpenCage as a reverse geocoder.
