### ISSUE TITLE
yum update fails as package is not signed

### ISSUE THREAD

**Issue by armhoge** [owntracks/recorder#239]
Running CentOS Linux release 7.5.1804

I am unable to update ot-recorder to 0.7.6-1 as it fails with

     Package ot-recorder_0.7.6_x86_64.rpm is not signed

Not really willing to update with --nogpgcheck

The etc files seem correct and contain

mosquitto.repo 

[home_oojah_mqtt]
name=mqtt (CentOS_CentOS-7)
type=rpm-md
baseurl=http://download.opensuse.org/repositories/home:/oojah:/mqtt/CentOS_CentOS-7/
gpgcheck=1
gpgkey=http://download.opensuse.org/repositories/home:/oojah:/mqtt/CentOS_CentOS-7/repodata/repomd.xml.key
enabled=1

owntracks.repo 

[owntracks]
name=OwnTracks
baseurl=http://repo.owntracks.org/centos/
gpgcheck=1
gpgkey=http://repo.owntracks.org/centos/RPM-GPG-KEY-owntracks
enabled=1

**Comment by jpmens** [comment]
You are quite right, and I apologize: it appears signing stopped at 0.7.5 for CentOS packages. I am investigating why that is.

**Comment by jpmens** [comment]
@armhoge I believe this is now fixed. Could you please try again?
