### ISSUE TITLE
Debian Jessie repo is still at 0.7.2

### ISSUE THREAD

**Issue by harbra** [owntracks/recorder#240]
I tried upgrading ot-recorder on my Raspberry Pi to the 0.7.6 release, however it seems the repo still contains 0.7.2. for the armhf package under Debian Jessie:
http://repo.owntracks.org/debian/dists/jessie/main/binary-armhf/

It would be great if the new version could be updated in the repo:-)

**Comment by jpmens** [comment]
Debian 9 was released almost exactly a year ago which is when [people pushed for Recorder on that](https://github.com/owntracks/recorder/issues/209) which we then did (you will see from that issue how much feedback we got on the effort of doing that...)

So, how are you going to entice us to set up a device with an old Raspbian version to build newer packages for it?

**Comment by harbra** [comment]
How about some thumbs-up?;-)
No, in all seriousness, I didn't realize Debian Jessie was already that old and was under the naive assumption that the binaries would be somehow built automatically without generating too much work on your end. However it certainly does not make sense to put additional manual work in binaries for an outdated OS and I will have to go down the route of building from source or finally upgrading my Raspberry Pi.
Would it make sense to put a comment in the documentation which repositories are still updated with the most recent released recorder binary to prevent questions like mine in the future?

**Comment by jpmens** [comment]
@harbra thank you for the idea; I have updated the documentation accordingly.
