### ISSUE TITLE
How to add speed information to map points?

### ISSUE THREAD

**Issue by edautz** [owntracks/recorder#241]
I made a GPS car tracker device that logs data to Ot-recorder.

The data is logged in the correct file : store/rec/eugene/auto and contains vel(ocity) data.

```
2018-06-15T08:44:41Z    *                       {"tst":1529052281.865,"_type":"location","lon":5.7983,"vac":10,"lat":51.0101,"vel":104.63,"bat
t":"--","conn":"l","tid":"1","topic":"owntracks/eugene/auto","username":"eugene","device":"auto","fulldate":"Fri Jun 15 2018 10:44:41 GMT+0200
 (CEST)"}
2018-06-15T08:55:16Z    *                       {"tst":1529052916.414,"_type":"location","lon":5.9291,"vac":10,"lat":51.1439,"vel":101.48,"bat
t":"--","conn":"l","tid":"1","topic":"owntracks/eugene/auto","username":"eugene","device":"auto","fulldate":"Fri Jun 15 2018 10:55:16 GMT+0200
 (CEST)"}
2018-06-15T08:57:16Z    *                       {"tst":1529053036.596,"_type":"location","lon":5.9656,"vac":10,"lat":51.1644,"vel":104.1,"batt
":"--","conn":"l","tid":"1","topic":"owntracks/eugene/auto","username":"eugene","device":"auto","fulldate":"Fri Jun 15 2018 10:57:16 GMT+0200
(CEST)"}
2018-06-15T08:58:16Z    *                       {"tst":1529053096.618,"_type":"location","lon":5.9826,"vac":10,"lat":51.1742,"vel":100.76,"bat
t":"--","conn":"l","tid":"1","topic":"owntracks/eugene/auto","username":"eugene","device":"auto","fulldate":"Fri Jun 15 2018 10:58:16 GMT+0200
 (CEST)"}
2018-06-15T09:02:46Z    *                       {"tst":1529053366.397,"_type":"location","lon":6.0237,"vac":10,"lat":51.2078,"vel":10.16,"batt
":"--","conn":"l","tid":"1","topic":"owntracks/eugene/auto","username":"eugene","device":"auto","fulldate":"Fri Jun 15 2018 11:02:46 GMT+0200
(CEST)"}
```

However this data is not show on the maps with the data points! It displays only address, lat,lon, and time.

I tracekd down this behaviour to the htdocs/map/functions.js file.

In this file  I added some statements to display the speed:

```
             // click dot on map to show info
        map.data.addListener('click', function(event) {
                var tst = event.feature.getProperty('tst');
                var dt = moment.utc(tst * 1000).local();
                var data = {
                        lat:   event.latLng.lat().toFixed(4),
                        lon:   event.latLng.lng().toFixed(4),
           ====> speed: event.feature.getProperty('vel'),
                        tst:   tst,
                        addr:  event.feature.getProperty('address'),
                        fulldate: dt.format("DD MMM YYYY HH:mm:ss"),
                };

      =====>   var t = "{{ addr }}<br/> {{ speed }}<span class='latlon'>({{ lat }},{{lon}})</span> {{ fulldate }}";
                if (typeof(tst) === 'undefined') {
                        t = "Position: {{lat}}, {{lon}}";
                }

                infowindow.setContent(Mustache.render(t, data));
                infowindow.setPosition(event.latLng);
                infowindow.open(map);
        });   
```

But nothings changes. I refreshed the webbrowser and the OT-recorder docker container, but that doesn't matter.

Can anyone help me out?

**Comment by jpmens** [comment]
(I have formatted the code between lines of three backticks each)

The only strange thing I see is the `tst` element which contains microseconds. Try and turn that into an integer, will you? We expect the Unix epoch time there (in seconds). I don’t think that hurts but please try.

**Comment by jpmens** [comment]
Make sure your `vel` element is actuallly set there with a `console.log(“vel=“ + vel);` or something which displays it in your browser’s debug console.

**Comment by edautz** [comment]
Modified the code a bit and commented the check for tst out, so my tst precision of milles wil not bother. I will fix that later to an integer.

        // click dot on map to show info
        map.data.addListener('click', function(event) {
                var tst = event.feature.getProperty('tst');
                var dt = moment.utc(tst * 1000).local();
                var speed = event.feature.getProperty('vel');
                var data = {
                        lat:   event.latLng.lat().toFixed(4),
                        lon:   event.latLng.lng().toFixed(4),
                        speed: speed,
                        tst:   tst,
                        addr:  event.feature.getProperty('address'),
                        fulldate: dt.format("DD MMM YYYY HH:mm:ss"),
                };

                var t = "{{ addr }}<br/>{{ speed }}<span class='latlon'>({{ lat }},{{lon}})</span> {{ fulldate }}";
                //if (typeof(tst) === 'undefined') {
                //      t = "Position: {{lat}}, {{lon}}";
                //}

                console.log("speed=" + speed);

                infowindow.setContent(Mustache.render(t, data));
                infowindow.setPosition(event.latLng);
                infowindow.open(map);

But                 var speed = event.feature.getProperty('vel'); doesn't work.

Console log:

dataURL = http://192.168.2.113:8083/api/0/locations?user=eugene&device=auto&format=geojson&from=2018-06-14T00:28
functions.js:94 

speed=undefined

Can you tell how to fix this?

**Comment by jpmens** [comment]
I'm being confused. You said you tracked it down to `map/functions.js`, but I don't have that file. It's in `last/`. Which of the maps are you looking at?

1. Live MAP of current locations
2. The Table
3. the individual points or track (e.g. last 7days)

The velocity is probably not being shown to you because we don't pass the data in. I have to know please what you're looking at and I'll try and fix it for you.

**Comment by edautz** [comment]
In my docker container (mapped to the host system):

rwxr-xr-x 2 root root 4096 Jun 16 08:13 .
drwxr-xr-x 7 root root 4096 Jun 11 21:41 ..
-rw-r--r-- 1 root root 2827 Jun 16 14:52 functions.js
-rw-r--r-- 1 root root 2662 May  3  2017 functions.js_org
-rw-r--r-- 1 root root 1398 May  3  2017 index.html
pi@raspberry-boven:~/docker/ot-recorder/htdocs/map $


I looked in 3: map of the individual pointe.

I use the docker container of robowntracks, may the directory configuration is different from a installed host version.

I hope this helps.

**Comment by jpmens** [comment]
That does not correspond to what you wrote 2h ago with `map.data.addListener('click', function(event) {`

**Comment by jpmens** [comment]
It works for the google live map now. You can test by building from source.

![jmbp-4509](https://user-images.githubusercontent.com/60706/41500097-37af67e2-718c-11e8-8c27-566c6c8a8c2e.png)

**Comment by jpmens** [comment]
What is “Robowntracks”?

**Comment by jpmens** [comment]
The geoJSON points map you refer to is the one that's been changed.

**Comment by edautz** [comment]
Thank you for your swift action.

Robowntracks is a docker container, with a preinstalled complete Ot-recorder installation.

https://hub.docker.com/r/robowntracks/owntracks-alpine/

But with an old version of Ot-recorder.

I am in the proces of making a new docker container with your latest version including this enhancement.

Thanks again.

**Comment by edautz** [comment]
My Rpi is running Raspbian Jessie. I saw your image is a Stretch based image, therefort I chose Robowntracks image.

I am coming up to speed with docker with my Rpi, so I created my own Alpine based image with your latest git version and modified the map_leaflet.js file to display the speed in the datapoint labels.

Works as a charm.

Thnxs.

**Comment by jpmens** [comment]
You _could_ contribute the changes you did to `map_leaflet.js` to us as a pull-request

**Comment by edautz** [comment]
Pull request done
