### ISSUE TITLE
Different locaction information via web sockets

### ISSUE THREAD

**Issue by avanc** [owntracks/recorder#245]
While using the live map, the first time all information with avatar is shown for a user. However, if an update arrives, the image is missing. It is not included in the location data from the websocket. Is this intended?

**Comment by jpmens** [comment]
I think that was intentional, but other than "why should we transfer all this again?" I cannot recall why I did it that way.

Care to explain your use-case and why you'd need the data for every point?

**Comment by avanc** [comment]
The first time the live map is loaded, the location is shown with a popup containing amongst other details the image of that person. However, after an update is received, the popup changes and does not show the image anymore. Instead, the ghash is shown. I wonder if this behaviour is intended.

However, I agree that it shouldn't be needed to transmit the image over and over again. I will check how it can be stored for that session in the browser.

**Comment by jpmens** [comment]
Let’s not overcomplicate. 

I hadn’t noticed what you describe on the first update of a location. If that really is the case, then it’s a bug; that should not happen. If you think this should be changed, I’ll take a PR (or look at it myself, but no guarantees when that will be)

**Comment by avanc** [comment]
It wasn't that hard to solve the problem:
https://github.com/owntracks/recorder/pull/244/commits/32a7c1f91c284e44f1db435eca36166152d5328b

Thus, no need to send the image over and over again.
