### ISSUE TITLE
Alternative homepage recorder

### ISSUE THREAD

**Issue by edautz** [owntracks/recorder#247]
I made a new homepage for OT-recorder with more advanced date & time selections:
Features:

- Date en time of current date and time are automatically filled in.
- Possibility to select time on local browser time or UTC time.
- Tested with several browsers: Chrome/Laptop Chrome/iPad, IE11/Laptop, Firefox/Laptop, Safari/iPad/iPhone. Works as intended.
- Like the original home page the users/devices are automatically created when loading the homepage.
- Written in pure javascript.

If you like it, I can issue a pull-request. 
 
iPad and iPhone view:

![img_0101](https://user-images.githubusercontent.com/11003867/42124109-5bc2acbc-7c5d-11e8-918e-898a48b01a06.JPG)

View of other devices: (Chrome, appearance can vary on browsertype)

![img_0104](https://user-images.githubusercontent.com/11003867/42124130-9ab2e108-7c5d-11e8-9f3c-abd0efe3deb7.JPG)

**Comment by jpmens** [comment]
That looks pretty good; yes, we'll gladly take your pull-request. :-)

**Comment by edautz** [comment]
Pull request made.
