### ISSUE TITLE
ot-recorder doesn't start at startup

### ISSUE THREAD

**Issue by emme-g** [owntracks/recorder#252]
Hello,
some weeks ago I installed and started to use with satisfaction ot-recorder in my Raspberry 3 running with Raspbian 8 (Jessy) following the instruction of the readme file. Everything works well now except the start process: I launch ot-recorder with
> sudo systemctl start ot-recorder.service

because without sudo it doesn't start. If I give the same command without sudo this is the answer I get in the terminal:
> Failed to start ot-recorder.service: Access denied

The main change I did respect to the default configuration is that I moved the data directory to an external drive attached via an usb cable to the Raspberry and mounted in /mnt/DATA (the storage directory is then /mnt/DATA/owtracks/recorder/store and all of the owntracks, recorder and store folders have owntracks:owntracks as owner).
At the same time, and this is my main problem, I experience problems at the boot of the system, because ot-recorder doesn't restart automatically at the startup even if I did exactly what has been specified in the readme file about the automatically start:
> systemd service
The packages we provide have a systemd unit file in /usr/share/doc/ot-recorder/ot-recorder.service which you can use to have the Recorder started automatically:
    Ensure you have a configuration file with the settings you require
    install -m444 /usr/share/doc/ot-recorder/ot-recorder.service /etc/systemd/system/ot-recorder.service
    Enable the service to run at startup: systemctl enable ot-recorder
    Launch the service systemctl start ot-recorder

If I ask in the terminal the status of the service after a reboot this is what I get:
> ot-recorder.service - OwnTracks Recorder
   Loaded: loaded (/etc/systemd/system/ot-recorder.service; enabled)
   Active: failed (Result: exit-code) since Sat 2018-07-28 12:54:06 CEST; 44min ago
  Process: 564 ExecStart=/usr/sbin/ot-recorder (code=exited, status=2)
 Main PID: 564 (code=exited, status=2)
Jul 28 12:54:03 hp-supervisionsystem systemd[1]: Started OwnTracks Recorder.
Jul 28 12:54:06 hp-supervisionsystem ot-recorder[564]: ot-recorder[564]: version 0.7.2 starting with STORAGEDIR=/mnt/DATA/owntracks/recorder/store
Jul 28 12:54:06 hp-supervisionsystem ot-recorder[564]: version 0.7.2 starting with STORAGEDIR=/mnt/DATA/owntracks/recorder/store
Jul 28 12:54:06 hp-supervisionsystem ot-recorder[564]: gcache_open: mdb_dbi_open for `topic2tid': MDB_NOTFOUND: No matching key/data pair found
Jul 28 12:54:06 hp-supervisionsystem ot-recorder[564]: gcache_open: mdb_dbi_open for `keys': MDB_NOTFOUND: No matching key/data pair found
Jul 28 12:54:06 hp-supervisionsystem ot-recorder[564]: gcache_open: mdb_dbi_open for `friends': MDB_NOTFOUND: No matching key/data pair found
Jul 28 12:54:06 hp-supervisionsystem ot-recorder[564]: connecting to MQTT on localhost:1883 as clientID ot-recorder-hp-supervisionsystem-564 without TLS
Jul 28 12:54:06 hp-supervisionsystem ot-recorder[564]: HTTP listener started on
Jul 28 12:54:06 hp-supervisionsystem ot-recorder[564]: ot-recorder[564]: gcache_open: mdb_dbi_open for `topic2tid': MDB_NOTFOUND: No matching key/data pair found
Jul 28 12:54:06 hp-supervisionsystem ot-recorder[564]: ot-recorder[564]: gcache_open: mdb_dbi_open for `keys': MDB_NOTFOUND: No matching key/data pair found
Jul 28 12:54:06 hp-supervisionsystem ot-recorder[564]: ot-recorder[564]: gcache_open: mdb_dbi_open for `friends': MDB_NOTFOUND: No matching key/data pair found
Jul 28 12:54:06 hp-supervisionsystem ot-recorder[564]: ot-recorder[564]: connecting to MQTT on localhost:1883 as clientID ot-recorder-hp-supervisionsystem-564 without TLS
Jul 28 12:54:06 hp-supervisionsystem ot-recorder[564]: ot-recorder[564]: HTTP listener started on
Jul 28 12:54:06 hp-supervisionsystem ot-recorder[564]: ot-recorder[564]: HTTP port is in use. Exiting.
Jul 28 12:54:06 hp-supervisionsystem systemd[1]: ot-recorder.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 28 12:54:06 hp-supervisionsystem systemd[1]: Unit ot-recorder.service entered failed state.

I've seen this old issue about startup problems:
https://github.com/owntracks/recorder/issues/175
but because it's quite old and it seems to me it's discussing not exactly my same problem I decide to open a new issue.
Do you have any suggestion about how to solve this problem and make that ot-recorder start automatically and correctly after a system reboot?

**Comment by jpmens** [comment]
it appears from a glance that you've moved the data directory and haven't initialized it. How you do this is described in the documentation.

**Comment by emme-g** [comment]
Yes, I did move the data directory but I didn't initialized because I installed ot-recorder using the repository's packages and reading the documentation page I intended it was needed just for the "Building from source" cases.
Anyway, after your suggestion, I initialized it using the code
> ot-recorder --initialize

but my problem was not solved: I still have to manually launch ot-recorder after a system restart because it doesn't launch automatically.
