### ISSUE TITLE
Memory leak when requesting geodata for a view over HTTP

### ISSUE THREAD

**Issue by ldruschk** [owntracks/recorder#254]
Issue: When repeatedly requesting the geodata for a view via ` http://.../view/example?geodata=1`, the memory consumption keeps rising, presumably because some memory is allocated but not freed.

How to reproduce: Create a view based on the example view which outputs at least a few points. Keep requesting the geodata using e.g. `for i in $(seq 10000); do curl -s http://localhost:8083/view/example?geodata=1 > /dev/null; done` and observe the memory consumption with e.g. `htop`.

With a .rec file which has  ~6000 entries, the memory consumption rises by around 10MB for each request in my tests.

The issue occurs with the official version from the apt repositories on Debian Stretch as well as a version compiled from source on Debian Stretch and Alpine Linux.

**Comment by jpmens** [comment]
Ouch. Thank you very much for your clear and concise report. 

I am aware of a few leaks in spite of having spent quite a bit of time on Valgrind to minimize them, but I know there are code-paths I did not check, and you found one of those. Indeed _views_ are something which is seldom used, probably a reason for not having been noticed earlier.

**Comment by ldruschk** [comment]
Ok, I found the issue and created a pull request with the fix. `geo_linestring` copies all coordinates from `locarray` by value, so `locarray` is no longer needed and not indirectly referenced in any other `json_delete`.
