### ISSUE TITLE
Please consider new binary package release to support opencage

### ISSUE THREAD

**Issue by mcphail** [owntracks/recorder#257]
Hi. Thanks for your hard work with this project.

Your README suggests the precompiled binary packages as the first port of call to use this app. It goes on to describe `"opencage:xxxxxxxxxxxxxx"` revgeo keys.

I added your repo and installed the package on Debian Stretch. I added my opencage key, as described, but was faced with:
```
revgeo: REQUEST_DENIED ({
   "error_message" : "The provided API key is invalid.",
   "results" : [],
   "status" : "REQUEST_DENIED"
}
)
```
After some detective work, I see the latest repo binary is `0.7.6`. That is also the newest git tag, but is very old and predates all the opencage integration. Thus, the documentation does not match the released version.

I'd be very grateful if you would tag and release a new version with the opencage additions.

**Comment by mcphail** [comment]
Many thanks!

**Comment by jpmens** [comment]
Packages have been built and pushed to the repositories for the platforms we currently support.

**Comment by mcphail** [comment]
Many thanks! Just grabbed the update.
