### ISSUE TITLE
date time calculations for last 12 hours, 7 days and 30 days are not correct

### ISSUE THREAD

**Issue by stehuebn** [owntracks/recorder#260]
Hello,

maybe I'm wrong but I think the calculation for the preset links (last 12 hours, 7 days and 30 days) is not completely correct.

The lines in the index.html are:

	var f12 = now.subtract(12, 'hours').utc().format('YYYY-MM-DDTHH:mm');
	var f7 = now.subtract(7, 'days').utc().format('YYYY-MM-DDTHH:mm');
	var f30 = now.subtract(30, 'days').utc().format('YYYY-MM-DDTHH:mm');`

This part of the javascript calculates at first the date/time value for the last 12 hours (and seems to be correct), but the f7 calculation subtracts 7 days from the f12 value, not from now. And the f30 value is the result of **now - 37 days and 12 hours**.

It seems to me that now.subtract(..) stores the result in now itself!

Please try:

        var f12     = moment(now).subtract(12, 'hours').utc().format('YYYY-MM-DDTHH:mm');
        var f7      = moment(now).subtract(7, 'days').utc().format('YYYY-MM-DDTHH:mm');
        var f30     = moment(now).subtract(30, 'days').utc().format('YYYY-MM-DDTHH:mm');

Best regards,

Steffen

**Comment by jpmens** [comment]
That's quite possible, thanks. Care to provide a pull request?

**Comment by stehuebn** [comment]
Ok, but it can take some days. Unfortunately the daily business has higher Prio! :-)

**Comment by cocker-cc** [comment]
Hi, @stehuebn, coincidently I had the same Finding, and created #271.

**Comment by jpmens** [comment]
Closed via #271. Thank you both.
