### ISSUE TITLE
Ubuntu 18.04 installation fails with dependency on libsodium18

### ISSUE THREAD

**Issue by RealGandy** [owntracks/recorder#262]
Trying to install recorder on Ubuntu 18.04 and get the following error:

gary@ubuntu-v:~$ sudo apt-get install ot-recorder
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 ot-recorder : Depends: libsodium18 but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by jpmens** [comment]
Please verify that the installation succeeds on Debian 9 which is what we support.

**Comment by RealGandy** [comment]
Installs fine on Debian 9... strange that Ubuntu latest is based on Debian 10.
