### ISSUE TITLE
google maps issues

### ISSUE THREAD

**Issue by ktpx** [owntracks/recorder#264]
Seems API stuff has changed, so the map now gives the "developer" version.

**Comment by jpmens** [comment]
As far as I can tell this happened around June/July; Google now expects an API key to be backed by a billing account, so that is something you would have to do for yourself if you want to continue using Google's maps.

**Comment by ktpx** [comment]
Yeah, I saw that that too in the logs.  I probably won't bother.  How about switching to openstreetmap?

**Comment by jpmens** [comment]
We already support OSM out of the box.

**Comment by ktpx** [comment]
I see that now in the documentation.  Says OSM is default, however I've not specifically enabled google maps....how do you set it to OSM?
