### ISSUE TITLE
Expire old .rec files

### ISSUE THREAD

**Issue by begleysm** [owntracks/recorder#266]
I looked through all the old issues, as well as the README.md, and a Google search and couldn't find an answer.

Is there a maximum age for the saved data?  If not that would be a good feature to add.

**Comment by jpmens** [comment]
Do you mean you want to expire old `.rec` files?
`/bin/rm` is the method of choice.

**Comment by begleysm** [comment]
Yes that is much more concise way to describe it.

I can certainly write a cronjob for this but it would be very convenient if this functionality were built into ot-recorder and there was a parameter in the config file to control the expiration age.  I think it should be considered as a feature for a future release.  I'll try to familiarize myself with the codebase and see if I can provide a pull request.

For anyone reading this looking for a similar capability I have a bash script that I wrote for a similar purpose [here](https://github.com/begleysm/ipcam-ftp-tools/blob/master/ftp_cleanup.sh).  The first parameter is the parent directory you want to work in (this directory won't be deleted but anything within it will).  The second parameter is the number of days you want to keep files for.  Setup a cronjob to have this run every week, or day, or hour, etc.

**Comment by jpmens** [comment]
One of the resons for the Recorder using individual `.rec` files for storage on a per/month basis is so that you are free to do with those files what you want. We will not complicate the code in order to perform such trivial tasks.

Thank you for your offer, but this is to inform you we will not take that PR. However we will accept most other improvements. :-)

**Comment by begleysm** [comment]
Just so I'm clear, the software is currently designed to collected data on, perhaps, many users at, possibly, rapid time intervals; and without any self employed mechanism to delete that stored information is able to fill up available storage to infinite.  And this is as intended and you aren't interested in an *option* to limit this behavior?

**Comment by jpmens** [comment]
We already have this option: a utility called `rm` is available on all machines the Recorder runs on.

**Comment by begleysm** [comment]
Wow.  Thanks for your reply.
