### ISSUE TITLE
Lat/Lon swapped in map_leaflet.js

### ISSUE THREAD

**Issue by cocker-cc** [owntracks/recorder#267]
Coordinates in map_leaflet.js are calculated and displayed in unusual Order "Lon,Lat" instead of "Lat,Lon"

**Comment by jpmens** [comment]
What are you trying to tell us? Is there a bug? What is the bug?

**Comment by cocker-cc** [comment]
The Bug is: Copy the Coordinates from the Popup, and put them in Search-Field of Google-Maps or Openstreetmaps, resulting in Lat and Lon in the wrong Order.
[Pull-Request 268](https://github.com/owntracks/recorder/pull/268)

**Comment by jpmens** [comment]
Thank you. Closed via https://github.com/owntracks/recorder/pull/268
