### ISSUE TITLE
Geo Lookup with opencage is failing

### ISSUE THREAD

**Issue by RealGandy** [owntracks/recorder#272]

**Comment by jpmens** [comment]
No it isn't

**Comment by RealGandy** [comment]
Just installed onto a shiny new Debian 9 guest and have added opencage geo lookup api into config file as required.

Running on command line with --debug, I see the following entries every time a new location is posted

`
+++++ [in hook_revgeo()]
curl_easy_perform() failed:
 Timeout was reached 
\- 17:42:53 owntracks/mandy/iPhone              t=c tid=M  loc=51.37512,-2.32523 [__] revgeo failed for (51.375122,-2.325227): HTTP status_code==0 (gcnk70d)
`

From this Debian guest I can run curl and hit the opencage api with these lat/long figures and get a valid response which takes between 2 and 4 seconds.

**Comment by jpmens** [comment]
Which seems to match what we say: the Recorder sets a timeout to `CURLOPT_TIMEOUT_MS, 2000L` (2000 ms, i.e. 2s) which is lower than what you observe.

Are you able build from source and change that constant in `geo.c` on line 325 to test?
