### ISSUE TITLE
Proxying from HTTP to MQTT

### ISSUE THREAD

**Issue by mikeage** [owntracks/recorder#274]
The README mentions:
> Gatewaying HTTP to MQTT
>
>It actually is possible to gateway location publishes arriving via HTTP into MQTT, though you should be careful not to create loops. You can accomplish this with one or more Lua hooks using MQTT from within Lua.

Is there an example of this? It seems like it should be a common use case, since the clients (at least Android does) recommend HTTP, but MQTT is far more useful on the backend (and also integrates quite nicely with Home Assistant)

**Comment by binarybucks** [comment]
```
cat /etc/ot-recorder/ot-recorder.lua
JSON = (loadfile "/etc/ot-recorder/JSON.lua")()

function otr_hook(topic, _type, data)
    otr.log("DEBUG_PUB:" .. topic .. " " .. JSON:encode(data))
    if(data['_http'] == true) then
        if(data['_repub'] == true) then
           return
        end
        data['_repub'] = true
        local payload = JSON:encode(data)
        otr.publish(topic, payload, 1, 1)
    end
end

function otr_putrec(u, d, s)
        j = JSON:decode(s)
        if (j['_repub'] == true) then
                return 1
        end
end

```
Compile ot-recorder with lua and add `OTR_LUASCRIPT = "/etc/ot-recorder/ot-recorder.lua"` to config. You also need [JSON.lua](http://regex.info/blog/lua/json) for that to work.

**Comment by mikeage** [comment]
Thank you! Will try that shortly.

**Comment by jpmens** [comment]
@mikeage you write

>  the clients (at least Android does) recommend HTTP

where did you read that Android recommends HTTP?

**Comment by mikeage** [comment]
https://owntracks.org/booklet/features/android/ says “It is highly recommended to use HTTP mode on Android 6 and higher.”

**Comment by jpmens** [comment]
Forgive me for not knowing our own documentation; somebody must have slipped that past me. ;-)

**Comment by mikeage** [comment]
This is working great for me. (I had to add stubs for otr_init, etc, but the content is perfect)

**Comment by compuguy** [comment]
Out of curiosity, does this script at `/etc/ot-recorder/ot-recorder.lua` still exist. I cant seem to find it in the docker image?

**Comment by jpmens** [comment]
There's a version at https://github.com/owntracks/recorder/blob/master/contrib/lua/http-to-mqtt-repub.lua

**Comment by compuguy** [comment]
Just saw that commit in the actual issue @jpmens. Thank you for pointing it out! Works great.
