### ISSUE TITLE
OTR_CERTFILE and OTR_KEYFILE are for?

### ISSUE THREAD

**Issue by deisi** [owntracks/recorder#275]
Not an Issue but a question. What exactly are these two options used for? 
Is it Authentication agains the mqtt broker or is it for https of the recorder web frontend itself?

**Comment by jpmens** [comment]
I've clarified the documentation; they are for the MQTT connection.

**Comment by deisi** [comment]
Okay, so there is no build in way to have ssl encryption. Instead a proxy should be used? If so I will add a section to the docker file to show how this can work.

**Comment by jpmens** [comment]
That's correct and by design; an example [proxy configuration](https://github.com/owntracks/recorder#reverse-proxy) is in the README.
