### ISSUE TITLE
Question: GeoCache re-use?

### ISSUE THREAD

**Issue by M-ax-G** [owntracks/recorder#279]
I installed ot-recorder on a new machine, and later decided I want to keep the old *.rec files from the previous system.

I wonder, whether I should simply delete the new data file in /ghash and /rec and forget the new data acquired during the last 10 days, and build upon the 'old' data files? Or can I merge these somehow? If so, how?

How does the caching mechanism work? Does it resolve a lat/long pair to a location when the data has been received, and then saves it to the data.mdb?

Are the keys some sort of hash for the lat/long pair, and hence, can be reused to resolve the same locations (e.g. for daily commutes), without having to make an external query?

Where could I find more information on the inner workings?

Any hints/pointers appreciated.

**Comment by jpmens** [comment]
You can safely copy `*.rec` files if you shutdown the Recorder so that you're sure nothing is clobbered if it receives a location publish while you are copying.

You can dump out your location cache with `ocat --dump` and load it with `ocat --load`, and yes you can pipe the former to the latter; this allows you to e.g. purge certain entries. The keys are a geohash of the lat,lon and this geohash has a precision which you configure in Recorder while building it or as a runtime option. 

I think most of this is described in our documentation, but if you think there is something missing, please either say so or better yet, contribute.

**Comment by M-ax-G** [comment]
Thank you! I do not think it is the documentation... it is me getting my head around it... :)
... and went back to read more docu...

Just realised the new set-up does not seem to do a reverse lookup (ocat --dump only lists keys and empty values), yet has no ghash/missing.
This means I can stop the ot-recorder service and copy the .mdb files from the old system, and be done with it.

However, how do I go about figuring out why there is no lookup happening?
The ot-recorder config has only two non-default values, which are the same on the old and new system:

sudo grep -E -v '(^$)|(^#)' /etc/default/ot-recorder
OTR_HTTPHOST="192.168.1.5"
OTR_TOPICS="owntracks/#"

My ot-recorder is an apt-get install on Rasbian Stretch.

**Comment by jpmens** [comment]
You are probably suffering from some google thing; our default was to use google as reverse geo provider. Meanwhile they've changed the rules of the game and I think you need an API key from them for which you also get only 2500 lookups per day .. sorry I forget the details.

Our documentation says quite a bit to that effect.

Be that as it may, please run Recorder in the foreground and publish a position, you should see at least some error message if there is one.

**Comment by M-ax-G** [comment]
Thanks; will see what I can come up with...
Can completely understand that newbie questions are quite a drag :)
Hence, my last question: Is there a OT and OTR forum you could point me too?

**Comment by jpmens** [comment]
Questions of this nature are good, and I try to help as do others. Don't hesitate to post them here.

We have a very low-volume Mattermost channel for discussing Recorder; I can invite you to it if you send me a request to do so at support@owntracks.org
