### ISSUE TITLE
Private mode against mosquitto: A TLS error occurred

### ISSUE THREAD

**Issue by padelt** [owntracks/recorder#28]
As expected, TLS is what breaks first.
I connect the iOS owntracks app in Private mode with activated TLS and authentication, so I have that going for me - which is nice.
MQTT setup was done using https://github.com/padelt/docker-owntracks-private-mqtt-broker , so mosquitto 1.4.2 is listening.
When recorder is connecting, it logs this:
```
2015-09-18 16:14:22,603 DEBG 'mosquitto' stdout output:
1442592862: OpenSSL Error: error:14094416:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown
1442592862: OpenSSL Error: error:140940E5:SSL routines:SSL3_READ_BYTES:ssl handshake failure
1442592862: Socket error on client <unknown>, disconnecting.

2015-09-18 16:14:32,633 DEBG 'mosquitto' stdout output:
1442592872: New connection from 178.201.xxx.xxx on port 1883.
```
Recorder repeatedly logs this:
```
Sep 18 16:12:21 pa15.local ot-recorder[4327] <Info>: MQTT connection: rc=8 [A TLS error occurred.]. Sleeping...
```
Config in `/usr/local/etc/ot-recorder.sh` is:
```
export OTR_HOST="my.host.name"     # MQTT hostname
export OTR_PORT="1883"     # MQTT port (set to 8883 for TLS and define OTR_CAFILE)
export OTR_USER="client2"           # broker user name
export OTR_PASS="whatever"            # broker password
export OTR_CAFILE="/Users/pa/owntracks/ca.crt"      # PEM CA certificate chain for broker

opts="${opts} --http-host 127.0.0.1 --http-port 8083 -D"

exec "/usr/local/sbin/ot-recorder" ${opts} "owntracks/#"
```
The CA certificat is what signed the mosquitto-server-certificate.

Mosquitto's config is basically this:
```
id_file /var/run/mosquitto.pid

persistence true
persistence_location /volume/data/

user mosquitto

port 1883

log_dest file /volume/log/mosquitto.log
log_dest stdout

cafile /volume/config/tls/ca.crt
certfile /volume/config/tls/server.crt
keyfile /volume/config/tls/server.key
require_certificate false

allow_anonymous false
password_file /volume/config/clients/passwd
```

How can I debug the actual cause of the failure?

I assumed that recorder takes the OTR_CAFILE contents to validate the certifcate presented by mosquitto. recorder does not get any certifcate itself, so it will not send one to mosquitto. That should be fine with mosquitto, since `require_certificate` is false.

Help!?

**Comment by jpmens** [comment]
TLS on port 1883? Are you doing that to confuse me or the enemy? :)

Your assumption is correct: `OTR_CAFILE` is used to validate the certificate presented by your broker. 
Are you quite sure that the common name (CN) of the server certificate or its Subject Alternate Name match the broker's hostname?

As certificates are public can you either send it to me privately (jpmens@gmail.com) or paste the output of `openssl   x509 -in server.crt -text -noout` here?

**Comment by padelt** [comment]
In fact, it is on port 21883 being forwarded to 1883 inside a docker container. ;-) I wasn't aware that MQTT over TLS is unusual on port 1883. Nevertheless, it works flawlessly.

The cleartext version of the certifcate is below. It is indeed "incorrect" in that neither CN nor "Subject Alternate Name" match the hostname that `recorder`is trying to connect to. If that is the problem, it means that `recorder` (or OpenSSL on its behalf) checks `OTR_HOST`against those fields, right?

So, next stop will be generating a new certificate for `mosquitto` and retry it. Once I did that, I'll update the issue.

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 16857198872093180544 (0xe9f0cd0f973ac280)
    Signature Algorithm: sha512WithRSAEncryption
        Issuer: CN=An MQTT broker, O=OwnTracks.org, OU=generate-CA/emailAddress=nobody@example.net
        Validity
            Not Before: Jun 17 15:30:04 2015 GMT
            Not After : Jun 12 15:30:04 2032 GMT
        Subject: CN=2f3a4f070ce4, O=OwnTracks.org, OU=generate-CA/emailAddress=nobody@example.net
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:b8:39:e7:3c:75:98:24:83:15:14:3d:33:ad:76:
                    1a:02:2f:de:5b:2a:10:57:32:2b:15:6b:4f:a1:55:
                    a7:d3:6f:88:94:2a:ce:72:03:04:55:2f:40:d9:c9:
                    df:e2:e6:45:d1:7e:d9:10:43:10:68:d3:89:e8:14:
                    c6:cf:b6:54:8e:26:8d:6d:f2:62:40:8f:8e:ac:75:
                    34:83:5b:74:18:94:74:6f:dc:0a:b7:86:82:f3:9a:
                    79:bf:78:d1:0e:05:6f:c0:0b:24:db:2d:91:a8:30:
                    34:be:a0:7c:0d:15:e5:cb:1b:cc:a2:8e:4e:ae:26:
                    4a:29:95:eb:8d:f2:aa:c5:0f:28:98:9c:08:57:6d:
                    9a:0b:f2:01:6d:cb:32:6c:1d:b1:42:b2:68:13:a4:
                    5a:a3:59:5d:06:1b:74:31:d4:4b:77:3f:b8:e6:05:
                    47:a6:55:f2:28:f8:3b:8f:c4:11:a8:d0:48:74:ab:
                    51:49:29:75:81:2f:15:b4:37:40:00:9a:b9:ea:10:
                    eb:7d:52:6b:69:12:e1:c8:13:e9:10:5f:eb:a1:22:
                    4a:d2:98:00:7c:f4:af:80:6b:da:1e:b3:a7:2e:9b:
                    c2:f0:bd:23:03:aa:68:13:c0:6d:bd:48:03:d7:ae:
                    24:0e:02:a9:2a:17:42:fa:59:97:1e:1a:b1:54:91:
                    57:99
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:FALSE
            Netscape Cert Type:
                SSL Server
            X509v3 Key Usage:
                Digital Signature, Non Repudiation, Key Encipherment
            Netscape Comment:
                Broker Certificate
            X509v3 Subject Key Identifier:
                A1:36:A0:E4:48:9B:EC:6D:EB:06:EE:5B:7E:D0:F4:73:C9:01:91:21
            X509v3 Authority Key Identifier:
                keyid:B5:B8:F5:D2:0B:C6:F9:C8:E4:7B:5A:58:F8:83:2E:82:53:03:B4:74
                DirName:/CN=An MQTT broker/O=OwnTracks.org/OU=generate-CA/emailAddress=nobody@example.net
                serial:D7:F3:9A:A3:54:68:C5:D2

            X509v3 Subject Alternative Name:
                IP Address:127.0.0.1, IP Address:0:0:0:0:0:0:0:1, DNS:localhost
            X509v3 Certificate Policies:
                Policy: 1.3.5.8
                  CPS: http://localhost
                  User Notice:
                    Organization: OwnTracks
                    Number: 1
                    Explicit Text: This CA is for a local MQTT broker installation only

    Signature Algorithm: sha512WithRSAEncryption
         2b:07:26:5e:9f:12:7c:c2:d2:62:0b:58:af:dc:c1:3b:73:f0:
         97:35:e8:4d:30:12:44:ce:04:ae:c1:6c:15:d7:2c:fb:8f:29:
         8e:06:74:69:ff:4a:31:8b:4d:05:28:b6:af:f7:60:84:98:3e:
         eb:4f:9d:89:48:1e:c5:7b:bc:4d:fe:2b:43:b1:7f:77:a3:e1:
         c5:5e:98:a0:ba:5b:70:10:b8:b1:2d:9e:73:b2:a8:32:c4:16:
         66:8e:1f:52:ed:8e:65:23:83:d9:33:38:ff:24:e5:c0:f9:06:
         07:a2:67:79:11:5d:df:46:9e:21:ee:e3:5b:9b:90:26:fb:2d:
         13:13:92:80:e8:b3:8c:11:25:1d:f0:f4:df:d2:e2:2d:d1:17:
         41:1e:98:5e:b3:9e:93:a2:83:07:ee:01:84:39:69:f6:ae:c7:
         91:42:07:b5:f2:14:5f:0c:92:09:af:1f:12:e0:32:2e:87:51:
         28:ca:9e:91:55:65:a2:f6:17:73:24:73:b9:a2:4f:f1:56:10:
         2f:3d:12:77:ea:77:05:40:56:22:6c:f6:2c:c4:e7:f9:ea:5c:
         85:6f:84:b9:1c:d2:b5:c9:6f:7a:c1:1b:33:ec:0d:89:f7:61:
         35:ea:fc:fb:0c:a7:c8:75:48:f9:2a:15:c0:3b:57:85:cf:cd:
         a0:bb:ca:a6
```

**Comment by jpmens** [comment]
Try this: on the host running the Recorder, create an `/etc/hosts` entry:

```
a.b.c.d  2f3a4fxxxx
```

where a.b.c.d is the IP of your broker, and 2f3axxxx (sorry, can't copy paste now stupidly) is the value of the Subject `CN` in the broker's certificate. Then set `OTR_HOST` to that name. It's ugly but it should work (though I'm not sure about the hostname starting with `2` ;-)

Recorder indeed sets TLS verify on connection and thus verifies that either subject CN or subjAltName match.

If *absolutely* necessary, I would add an option to disable that, but I don't really want to start lowering our standards. :-)

BTW, in our `owntracks/tools` repository is a generate TLS shell script which allows you to create a CA and server certificates with any number of subjAltNames in them.

**Comment by jpmens** [comment]
and that's the script you used.

**Comment by jpmens** [comment]
For the record: MQTT with TLS defaults to `TCP/8883`. No problem the way you do it -- just a bit unusual. :)

**Comment by padelt** [comment]
I just *love* working with people who know what they are doing! OpenSSL/TLS is not my area of interest, to put it mildly. ;-)

Basically all you write is spot on:
a) Yep it was your script I used and I absolutely should have read more of it:
```
# Set the following optional environment variables before invocation
# to add the specified IP addresses and/or hostnames to the subjAltName list
...
#       HOSTLIST="a.example.com b.example.com"
```
b) Putting the hostname in the `subjectAltName` did the trick. I used
```
HOSTLIST="my.host.name" ./generate-CA.sh my.host.name
```
to generate a new set of `.crt` and `.key` files needed for mosquitto. My first try without the HOSTLIST env variable did not work (same error). It had the host name as CN but not in `subjectAltName`. Not sure if I made a mistake in the process or if having the hostname in `subjectAltName` is actually strictly necessary.

So my certificate looks like that now:
```
Signature Algorithm: sha512WithRSAEncryption
        Issuer: CN=An MQTT broker, O=OwnTracks.org, OU=generate-CA/emailAddress=nobody@example.net
        Validity
            Not Before: Sep 18 19:43:23 2015 GMT
            Not After : Sep 13 19:43:23 2032 GMT
        Subject: CN=my.host.name, O=OwnTracks.org, OU=generate-CA/emailAddress=nobody@example.net
...
            X509v3 Authority Key Identifier:
                keyid:B5:B8:F5:D2:0B:C6:F9:C8:E4:7B:5A:58:F8:83:2E:82:53:03:B4:74
                DirName:/CN=An MQTT broker/O=OwnTracks.org/OU=generate-CA/emailAddress=nobody@example.net
                serial:D7:F3:9A:A3:54:68:C5:D2

            X509v3 Subject Alternative Name:
                IP Address:127.0.0.1, IP Address:0:0:0:0:0:0:0:1, DNS:my.host.name, DNS:localhost
            X509v3 Certificate Policies:
                Policy: 1.3.5.8
                  CPS: http://localhost
                  User Notice:
                    Organization: OwnTracks
                    Number: 1
                    Explicit Text: This CA is for a local MQTT broker installation only
```
c) [I should use port 8883.](http://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=mqtt)

Thanks a lot for helping me get this working and learning something!

**Comment by jpmens** [comment]
I'm very glad you got it going. Two remarks:

1. as you've already experienced, port 8883 is no absolute must; I just choked a little because I wasn't expecting TLS on 1883. :-)
2. regarding `subjAltName` in your certificate: I added that to the shell script because what I typically do is, say, add the "real" hostname, then maybe a couple of IP addresses, and things like `localhost`; that way I know the certificate will be verifyable almost irrespective of how I actually address the host. You can also (with some care) do something like `*.mens.de` to have a wildcard subjAltName.
