### ISSUE TITLE
Which operating system platform do you use for our Recorder packages?

### ISSUE THREAD

**Issue by jpmens** [owntracks/recorder#280]
We'd like to know which operating system platform you use for our packages (e.g. Recorder). Is it Debian, RedHat/CentOS, Ubuntu, Raspian, SLES, ... ?

In the comments that follow, you'll find individual distributions / platforms. Please `+1` the one(s) you use.

**Comment by holgerkoch** [comment]
CentOS

**Comment by joerggollnick** [comment]
## Alpine (docker image based on arm32v6/alpine:latest)

**Comment by avanc** [comment]
## Arch Linux 

https://aur.archlinux.org/packages/owntracks-recorder/

**Comment by rjbrown99** [comment]
CentOS 7, soon to be 8.
