### ISSUE TITLE
Add accuracy field to GeoJSON points parameters

### ISSUE THREAD

**Issue by aaliddell** [owntracks/recorder#282]
It would be useful to have the accuracy field passed as a parameter on the point objects when using the API to fetch a GeoJSON response, as the points can then be filtered on this field to remove low accuracy updates etc or updates could be drawn as circles with correct radii.

As a possible extension to this, it might be useful to have the set of parameters returned on the points be configurable as part of the API to allow users to specify which fields they need. e.g. `fields=tst,alt,acc`

**Comment by jpmens** [comment]
It probably would be useful.

Are you up to attempting that yourself? I'd accept a pull request which handles, in particular, the first part of your suggestion.

**Comment by aaliddell** [comment]
Sure, looks reasonable enough to add
