### ISSUE TITLE
Leaflet map and view wrap around antimeridian (±180°)

### ISSUE THREAD

**Issue by ckrey** [owntracks/recorder#293]
a.k.a. don’t fly from Fiji 🌸 to Hawaii 🌺 

When travelling across the antimeridian, leaflet wraps points and lines.
<img width="524" alt="points" src="https://user-images.githubusercontent.com/4027289/53330683-65eed180-38ef-11e9-8bcd-c64ee4e0f7a0.png">
<img width="528" alt="track" src="https://user-images.githubusercontent.com/4027289/53330684-671ffe80-38ef-11e9-92ba-7f562f456ecf.png">
<img width="519" alt="views" src="https://user-images.githubusercontent.com/4027289/53330685-68e9c200-38ef-11e9-9a9d-78c119ad44d1.png">

**Comment by ckrey** [comment]
To avoid this, longitudes need to be adjusted to be > 180 or < -180

**Comment by jpmens** [comment]
Thank you **very** much!
