### ISSUE TITLE
Lost points

### ISSUE THREAD

**Issue by langasg** [owntracks/recorder#295]
In my installation, I have detected that ot-recorder does not paint all the points that arrive at my mqtt broker, I have checked this comparing against the DB that stores the positions and only paints half of the stored positions.
I have also noticed that when I use my owntracks and the waze navigator simultaneously, the precision and frequency of the positions is much higher than when I only use my owntracks
![ot-recorder](https://user-images.githubusercontent.com/28660981/53920010-f8b80a80-406b-11e9-9687-0ea18d725a9c.PNG)

**Comment by jpmens** [comment]
You say

> paints half of the stored positions

What do you mean by "half"? Is this every second point, half from the beginning, half from the end, ... ? We've not noticed this yet, so we need help in getting to the bottom of this.

As for running OwnTracks together with a mapping software; it is known that this increases precision for OwnTracks, and I assume you are running on iOS.

**Comment by langasg** [comment]
On my MQTT server, I see two o three messages with different positions and  on the otrecorder only view one point/position.
When I am driving my car i use a Waze gps navigator, on this case otrecordet show more precision an d much  more positions.

**Comment by jpmens** [comment]
There's not much we can do with that information. What you could do is to collect a sample over a defined period of time (a few hours maybe) and send us

- MQTT broker logs
- data collected via mosquitto_sub
- recorder (`.rec`) file

to support@owntracks.org

**Comment by langasg** [comment]
OK, thanks.
