### ISSUE TITLE
No friends showing in OwnTracks when using recorder in HTTP mode

### ISSUE THREAD

**Issue by csmart** [owntracks/recorder#297]
I'm probably doing something wrong here... I'm running the latest recorder Docker image and am able to successfully post data (with curl and with OwnTracks app) which shows my two users.

However, inside OwnTracks the two users cannot see each other, i.e. there are no Friends.

Is there something I need to do to activate this? According to this I thought it should just work?:
https://github.com/owntracks/recorder#friends-in-http-mode

I did try the database command mentioned in the above link to dump friends database, but it doesn't return anything:

```bash
docker exec -it recorder /bin/sh
ocat -S /store --dump=friends
```

Thanks!

**Comment by jpmens** [comment]
Friends have to be set up recorder-side when using HTTP mode (another reason why we promote MQTT mode :-) 

You have to populate the friends database in order for this to work. To do so, create a file with

```
csmart-phone ["john/android", "jane/phone"]
```

(assume your user-device is `csmart-phone`) and add the JSON array of friends as indicated. Then load that file into the database:

```
ocat -S /store --load=friends < file.name
```

From this point onwards the _dump_ command you used above will print that out and you ought to be able to see the list of friends on your device, after pressing "publish" there.

**Comment by csmart** [comment]
Thank you @jpmens :-) I have been using MQTT mode for about a year or so on Android phones, but haven't been able to get it to work reliably... thought I'd try HTTP to see if that works better.

I'm sorry for the noise, now that I know what to look for I see that the info is clearly in the README page here https://github.com/owntracks/recorder#friends

Thanks and have a great weekend.

**Comment by Corbauf** [comment]
Hello, I have exactly the same problem. I am using a docker image from here : [https://hub.docker.com/r/jessestuart/owntracks](https://hub.docker.com/r/jessestuart/owntracks) since I need an ARM build.
When I do :
`sudo docker exec -it dbae6f93802f /bin/bash` 
to get in my docker container, then :
`ocat -S /store --dump=friends`
I get :
`Cannot open lmdb/friends at /store/ghash`

Also, how can I create a file like you explained since I am in a docker container and no text editor is available ?

Thank you for your help !

**Comment by prologic** [comment]
Hmm I'm having a lot of trouble with this. I can't seem to get this to work. Is the format of the `friends.txt` file:

```
<username>-<device> ["<username>/<device>", "<friend-username>/<fiend-device>"]
<friend-username>-<friend-device> ["<username>/<device>", "<friend-username>/<fiend-device>"]
```

??? What about the `owntracks/...` topic that the recorder is configured with by default? I've tried pretty much every combination and I can't seem to get two iphones to see each other.

**Comment by prologic** [comment]
Hmm I seem to be able to cause it to segfault quite easily :/

**Comment by jpmens** [comment]
You are commenting on a closed five year-old ticket. Please open a new one, describing versions and what you're doing.
