### ISSUE TITLE
Creating A Card In HTTP Mode?

### ISSUE THREAD

**Issue by metal450** [owntracks/recorder#299]
I'm interested in creating cards for my users.  The documentation (https://owntracks.org/booklet/features/card/) specifies how to generate them to stdout, but then says you "typically then publish the result as a retained message to your MQTT broker."

How do we add these if we're running in HTTP only mode (aka there's no MQTT broker)?

**Comment by jpmens** [comment]
There's a well-hidden comment in our example on the [HTTP page in the Booklet](https://owntracks.org/booklet/tech/http/) which alludes to what you do: basically your back-end emits the same JSON you would publish over MQTT during the HTTP connection.

**Comment by metal450** [comment]
Sorry, I still don't understand how to add these to the server.

So I have multiple Android clients, which are talking to the Recorder over HTTP.  I've used the cli to setup their friend relationships.  Now I'd like to add pictures for all these users.  The instructions say how to use the cli to generate cards to stdout...but...how do I get these into the server database & associated with the users, so it'll emit them to the clients?

**Comment by jpmens** [comment]
It's no small wonder you didn't understand my answer, as I was answering a question you didn't ask; sorry.

In _theory_ (but note: I've not done this very often, and you're right in that it's not documented), HTTP mode will search for a friend's CARD in

```
<STORAGEDIR>/cards/<user>/<user>json
```

So, If I'm your friend, your Recorder will load my JSON card on your machine from the path `<STORAGEDIR>/cards/jpmens/jpmens.json`. (The same card is loaded for all devices a user has.)

In `contrib/faces/` there are some small utilities which help you create CARDs, and please make sure to verify that the `.json` file you drop into that directory is readable by the Recorder and is valid JSON. (You can test that with `jq . < file.json` or `python -mjson.tool file.json`.)

**Comment by metal450** [comment]
Cool, looks like that did it, thanks!  You might consider adding it to the documentation, as I was spinning my wheels for nearly an hour searching around trying to figure out  what I was missing.  Also, a note: you have to change "md5" to "md5sum" in the scripts or they won't work.

Cheers :)

**Comment by jpmens** [comment]
Glad you got it sorted. I've added documentation and have amended `gravatar2card.sh` so that it uses  `md5sum` on platforms which have it. (`md5` is a macOS utility.)

**Comment by wir3z** [comment]
I know this is closed, but looking for clarity on this.  I'm using the docker image on OpenSUSE, and created a volume called "recorder_store".
From the documentation it says to store the cards here:
<STORAGEDIR>/cards/<user>/<user>.json"

If my user is "Bob" (with an uppercase), would the JSON be stored here:  'recorder_store/cards/Bob/Bob.json'

With case sensitivity?  Is this the correct storage path?  Do I need to do anything for friends in Recorder, or as long as the user is showing up on the live map, the card should be displayed?  I see both user location data, but no images using the above.

Thanks!  The Recorder is pretty awesome!

**Comment by ckrey** [comment]
[All user and device names are lower-cased](https://github.com/owntracks/recorder#getting-started)

**Comment by jpmens** [comment]
In addition to what @ckrey said, note that we have amended the documentation: the CARD is actually loaded from the path you specified, @wir3z, but it contains the device name, so using your example with Bob having an Android it would be `cards/bob/android/bob-android.json`

I've just tested this in HTTP mode and you ought to see the avatar in the map 

![rabbit-10518](https://github.com/owntracks/recorder/assets/60706/b3ed5634-5246-4a11-9fc9-2bc76aa14638)

and in the table

![rabbit-10519](https://github.com/owntracks/recorder/assets/60706/13f992bc-c639-4193-85c8-76cef8dd7565)

**Comment by wir3z** [comment]
Ok, I'm close, but still having issues.  When I look at the table, I get (for user 'Bob')
Name: `owntracks/Bob/panther`
User: `bob\panther`

I don't have a TID assigned?  Do I need one?  Or is the card matching to the "Name" field?

**Comment by jpmens** [comment]
I'm interpreting that as your user `bob` has a device `panther`, but your card is stored at `../recorder_store/cards/bob/bob-android.json` which should be `../bob-panther.json`.

Also, please validate that you really have valid JSON in the CARD file using, say, `jq` or `python3 -mjson.tool`

**Comment by wir3z** [comment]
Ok I figured out the miss on my side.  Adding in case others struggle with this.

Using the Docker image I did this:
- docker volume create recorder_store
- docker run -d --restart always -p 8083:8083 -v [recorder_store:/store](http://recorder_store/store) -e OTR_HTTPHOST=0.0.0.0 -e OTR_HTTPPORT-8083 -e OTR_PORT=0 -e e OTR_SERVERLABEL=OwnTracks owntracks/recorder

The `STORAGDIR` is actually `/recorder_store/_data`.  On OpenSUSE this translates to: `/var/lib/docker/volumes/recorder_store/_data`

Inside that folder, you will see folders of:
- ghash
- last
- rec

You add one more:
- cards

Inside there, you have 2 options to store the cards,  It can be universal for the user regardless of device, or device specific:
1. `<user>/<user>.json`
2. `<user>/<device>/<user>-<device>.json`

In my example, user `Bob` was using HTTP, had not defined a device, so the OwnTracks app used the Android version as a default `panther`.

For that example a card could be dropped in either folder and worked:
1. `/var/lib/docker/volumes/recorder_store/_data/bob/bob.json`
2. `/var/lib/docker/volumes/recorder_store/_data/bob/panther/bob-panther.json`

Works perfect now, thanks for the help!

**Comment by jpmens** [comment]
Glad you got it going.
