### ISSUE TITLE
Documentation: Usernames Are Always Lowercase

### ISSUE THREAD

**Issue by metal450** [owntracks/recorder#300]
Suggestion: it would probably be a good idea to add a prominent note to the documentation that on the Recorder, all usernames and device names are always considered lowercase, regardless of how they're entered on the clients.

I spent quite a long time pulling my hair out unable to figure out why friend relationships, cards, etc weren't working according to the instructions.  Turns out It's because although I'd entered names like Fred on all the clients, registering the same way on the server doesn't work.  You have to treat them as all lowercase, regardless of how they were entered on the clients: "Fred" on the clients is recognized as "fred" on the server.  A prominent note in the documentation could've saved a lot of frustration :)

**Comment by jpmens** [comment]
So [this](https://github.com/owntracks/recorder/blob/master/doc/DESIGN.md) isn't sufficient? :-)

**Comment by jpmens** [comment]
Valid point, thank you; I have made an appropriate note.

**Comment by jpmens** [comment]
Oh, and congratulations to the nice round issue number you created: `300`. :-)

**Comment by metal450** [comment]
:)
