### ISSUE TITLE
ocat error "no strptime"

### ISSUE THREAD

**Issue by wlauppe** [owntracks/recorder#302]
Hello, im using your fabulous owntracks recorder tool, but when i use "ocat" with a time setting, like: 

```
ocat --user owntracks --device mydevice --format gpx --from 2019-4-29 > output.gpx
```
i get the error

```
no strptime
```

i tried various libs (apt-get install build-essential) but without success, Can you point me to the library which is needed to be installed for the tool to work with time strings?

The System is "Debian GNU/Linux 9.8 (stretch)"

Thanks a lot.

**Comment by jpmens** [comment]
You are not missing anything; it's simply the value you're passing which isn't recognized. Please specify your month of April as `04`, so `2019-04-29`. 

I've fixed the misleading error message.
