### ISSUE TITLE
Activate TLS on docker

### ISSUE THREAD

**Issue by drjt87** [owntracks/recorder#303]
I've set up mosquitto as my broker, and used the certs from Letsencrypt to activate TLS. Working well on Owntracks.

I've just set up a docker container for otrecorder, but I don't think I've activated TLS on it. There didn't seem to be an environment option (other than specifying the CA file, while I don't want to bother with)

Is there a way to get the recorder to connect to mosquitto only by TLS? I am probably just missing some documentation....

**Comment by drjt87** [comment]
The recorder is running but doesn't seem to be connecting. I used the following command (obviously removed the host, user and password):

docker run --name=recorder -itd -p 8083:8083 -v recorder_store:/store -e OTR_PORT=8883 owntracks/recorder

**Comment by jpmens** [comment]
the recorder requires a CA file or else TLS will not happen.

**Comment by drjt87** [comment]
Thank you.
