### ISSUE TITLE
Endpoint response 200

### ISSUE THREAD

**Issue by fletchg** [owntracks/recorder#306]
What does this error mean ??

Thanks.

**Comment by jpmens** [comment]
I do not see that in our code. You'll have to explain what you are doing, how you've set up the Recorder and what you are attemting to do.

**Comment by withmorten** [comment]
It's not an error, it's an HTTP status code, indiciating success:

https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#2xx_Success

**Comment by fletchg** [comment]
Thank you. I believe the issue was somewhere else but needed to be sure. Owntracks is working again for the most part. Thanks
