### ISSUE TITLE
Compiling without MQTT and with HTTP results in error in recorder.c - 'uviewsdir' undeclared

### ISSUE THREAD

**Issue by withmorten** [owntracks/recorder#307]
This is the error output from make:

```
In file included from recorder.c:38:0:
recorder.c: In function ‘main’:
recorder.c:1244:15: error: ‘uviewsdir’ undeclared (first use in this function)
  utstring_new(uviewsdir);
               ^
utstring.h:79:4: note: in definition of macro ‘utstring_new’
    s = (UT_string*)calloc(sizeof(UT_string),1);            \
    ^
recorder.c:1244:15: note: each undeclared identifier is reported only once for each function it appears in
  utstring_new(uviewsdir);
               ^
utstring.h:79:4: note: in definition of macro ‘utstring_new’
    s = (UT_string*)calloc(sizeof(UT_string),1);            \
    ^
```

This happens because `UT_string *uviewsdir` is declared in an `#if WITH_MQTT` block at line [1194](https://github.com/owntracks/recorder/blob/master/recorder.c#L1194), but then referenced in an `#if WITH_HTTP` block at line [1244](https://github.com/owntracks/recorder/blob/master/recorder.c#L1244). I simply added the declaration below line [1206](https://github.com/owntracks/recorder/blob/master/recorder.c#L1206) to fix it, and then the compilation worked.

Should I just make a pull request for this? Seems to be an easy fix.

**Comment by jpmens** [comment]
If you can fix it, gladly.
