### ISSUE TITLE
"json.c: emit_string: Assertion `utf8_validate(str)' failed." when using with MQTT and viewing the Live map

### ISSUE THREAD

**Issue by multitain** [owntracks/recorder#310]
Same preamble as here: https://github.com/owntracks/recorder/issues/309

Just using a very simple setup, but this time ot-recorder is run with:

`ot-recorder --http-host example.com --host example.com 'owntracks/#'`

Pushing data via MQTT from the app works, we can again view the table. But opening the Live Map the error message `ot-recorder: json.c:1112: emit_string: Assertion `utf8_validate(str)' failed.` reproducably happens.

Here is the full (slightly redacted log, URL and IP changed): https://gist.github.com/withmorten/da02c6a735e476b5574406e48a6a1d2a

The odd thing is, that the Live map actually worked for a short while and I could see my current location on the map properly.

Any idea how this could happen? We are just using standard ASCII strings as far as we're aware, nothing special. We again don't know enough about the structure of the program to really dig into it.

**Comment by jpmens** [comment]
Please show us what you are publishing via MQTT (or POSTing via HTTP). If it's sensitive data, send it to support@owntracks.org.

**Comment by multitain** [comment]
Sorry for the delayed response. To clarify, you want an excerpt of what the owntracks app sends to the server (be it via HTTP or MQTT)?

If yes, how would we go about accessing that data?

While the server is started, and I force push the location from the app, this gets printed by the server, but I'm assuming that's not the full data:

`* 09:16:26 owntracks/admin/morten              t=u tid=mw loc=52.43124,13.20744 []  (u336k8c)`

**Comment by jpmens** [comment]
The Recorder has stored a `.rec` file (typically in `/var/spool/owntracks/recorder/store/rec/<username>/<devicename>/YYYY-MM.rec`. That's what I need to see privately please.

**Comment by multitain** [comment]
Ah yes, we actually had a look at that file. Currently I was pushing data via MQTT from the app though, does the recorder still store the data in /var/spool or in the MQTT database?

I'll send the .rec via email just in case.

**Comment by jpmens** [comment]
I recevied the data, thank you. There's nothing untoward I spot in there.

Please give us details about your environment: which OS/versions are you running, which MQTT broker (versions), and which of our apps (Android/iOS)?

**Comment by multitain** [comment]
OS is `Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-042stab139.1 x86_64)`.

ot-recorder is straight from git built with make.

App is the android app downloaded via playstore.

mosquitto was installed via apt-get, and version is `1.4.8-1ubuntu0.16.04.6`.

**Comment by jpmens** [comment]
I cannot reproduce what you've been experiencing.

Are you still observing crashes?

**Comment by jpmens** [comment]
Closing as stale.
