### ISSUE TITLE
Add packages to official repositories

### ISSUE THREAD

**Issue by makubi** [owntracks/recorder#311]
Hi,

it would be great to see the packages added to the official distribution repositories.

Thanks

**Comment by jpmens** [comment]
We will not do this, but you are free to.

**Comment by Draghtnod** [comment]
I can live with the inofficial repositories, but a Buster release would be nice. Is that much work?

**Comment by jpmens** [comment]
@Draghtnod so you're a Buster user? :-)

Once again: anybody is free to submit packages to repositories. We can assist in terms of when something goes wrong with our code (i.e. bug fixes) but we won't do the packaging.
