### ISSUE TITLE
compile error on i386

### ISSUE THREAD

**Issue by dlangille** [owntracks/recorder#314]
I don't run this on i386, but the FreeBSD project will build for it. As such, they encountered this error:

```
clang -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing  -I/usr/local/include -Wall -Werror -DGHASHPREC=7 -DWITH_MQTT=1 -I/usr/include -DWITH_PING=1 -DWITH_HTTP=1 -DJSON_INDENT=NULL -DSTORAGEDEFAULT=\"/var/spool/owntracks/recorder/store\" -DDOCROOT=\"/usr/local/www/ot-recorder\" -DCONFIGFILE=\"/usr/local/etc/ot-recorder/ot-recorder.conf\" -DGEOCODE_TIMEOUT=4000 -DGIT_VERSION=\"tarball\"   -c -o misc.o misc.c
misc.c:65:34: error: format specifies type 'long' but the argument has type 'time_t' (aka 'int') [-Werror,-Wformat]
        utstring_printf(us, "%ld %s\n", now, topic);
                             ~~~        ^~~
                             %d
```

re: http://beefy10.nyi.freebsd.org/data/112i386-default/507745/logs/ot-recorder-0.8.4_1.log

I am able to replicate the issue when building on i386.

I am not familiar enough with this to know how to patch this.  Happy to test patches.

**Comment by jpmens** [comment]
Can you try this please?

```
utstring_printf(us, "%ld %s\n", (long)now, topic);
```

**Comment by dlangille** [comment]
Success. That builds on both `amd64` and `i386`.  I will add that patch to the FreeBSD ports tree and remove it upon the next release.

Thank you.

**Comment by dlangille** [comment]
https://svnweb.freebsd.org/ports?view=revision&revision=507773
