### ISSUE TITLE
Cannot connect to web server

### ISSUE THREAD

**Issue by 4994james** [owntracks/recorder#319]
I have installed on Debian Stretch (Raspberry pi running openhabian actually).

I seem to be successfully publishing mqtt messages to the database.

However  I cannot connect to the webserver with say: http://192.168.1.13:8083 from a browser on my local network.  192.168.1.13 is the ip of openhabian.  I just get "refused to connect".

Is this a permissions problem?  I noticed that the config file has user "owntracks" however I am unable / don't know how to change user to this.

ocat -v yields:
```
This is OwnTracks Recorder, version 0.7.9
built with:
        WITH_MQTT = yes
        WITH_HTTP = yes
        WITH_LUA  = yes
        WITH_ENCRYPT = yes
        WITH_PING = yes
        WITH_KILL = yes
        CONFIGFILE = "/etc/default/ot-recorder"
        STORAGEDEFAULT = "/var/spool/owntracks/recorder/store"
        STORAGEDIR = "/var/spool/owntracks/recorder/store"
        DOCROOT = "/usr/share/owntracks/recorder/htdocs"
        GHASHPREC = 7
        DEFAULT_HISTORY_HOURS = 6
        JSON_INDENT = "NULL"
        LIBMOSQUITTO_VERSION = 1.4.10
        MDB VERSION = LMDB 0.9.16: (August 14, 2015)
        SODIUM VERSION = 1.0.11
        GIT VERSION = 0.7.9-0-gff00c83222
```

**Comment by jpmens** [comment]
Recorder binds to 127.0.0.1:8083 by default. 
Please look at the `host` (I think it is) option to specify Recorder should listen on the address you specify.

**Comment by 4994james** [comment]
Thank you.  That works (i.e. replacing the IP address in the config file).  I had thought that localhost would mean I should be able to connect using the pi address but clearly my understanding is not quite there yet.  

I have edit to the config file or start the process using sudo.  Can anyone explain the permissions to me as I can't change user to owntracks - it asks for credentials.

**Comment by jpmens** [comment]
What is `it`? Do you mean _sudo_ is asking you? If so, it's bound to be your own password.

**Comment by jpmens** [comment]
Closed as answered.
