### ISSUE TITLE
Debian Buster Support

### ISSUE THREAD

**Issue by dannycohn** [owntracks/recorder#320]
Is there a path to getting this working on Debian Buster?

**Comment by damionx7** [comment]
Ot-recorder depends on libcurl3 and libcurl3 is dropped in Debian Buster due to ssl issue. Guys please update the dependency. We cant install ot-recorder without it on debian buster. You guys are doing an amazing job.
<img width="515" alt="Screenshot 2019-09-23 at 9 11 36 PM" src="https://user-images.githubusercontent.com/6530843/65440676-bb1fa100-de46-11e9-9276-7d29172210f2.png">

**Comment by 420Dope** [comment]
Yes, please update for Buster. That were so nice!

**Comment by jpmens** [comment]
Packages for Debian 10 (Buster) on `amd64` are now available. We'd appreciate feedback whether they're ok for you.

**Comment by 420Dope** [comment]
Thanks for that.
Is it the same install process like with other debians? Only write instead of `stretch main`, `buster main` to add the repo?
Like
`curl https://raw.githubusercontent.com/owntracks/recorder/master/etc/repo.owntracks.org.gpg.key | sudo apt-key add -
echo "deb  http://repo.owntracks.org/debian buster main" | sudo tee /etc/apt/sources.list.d/owntracks.list > /dev/null
sudo apt-get update
sudo apt-get install ot-recorder`

Sorry for the "silly" question, but i am not so fimiliar with debian (or better to say, linux at all).

**Comment by jpmens** [comment]
I believe that is correct, and thank you for reminding me to update the [README.txt](http://repo.owntracks.org/README.txt), which I have now done. You should be able to follow the instructions from there.

**Comment by 420Dope** [comment]
Perfect, thank you!
I will try it our maybe next week if i have time.

**Comment by damionx7** [comment]
This works.

**Comment by thomasgresch** [comment]
I try to get owntracks running on a Raspberry Pi with Raspibian Buster, but currently http://repo.owntracks.org/debian doesn't have an armhf-package for Debian 10 (only an AMD64-package). Do you have plans to add the armhf-package soon? I would prefer having a package then installing it from source. Thanks!

**Comment by 420Dope** [comment]
I can give feedback from a Hyper-V Debian Buster machine.
Works great. Thanks for this!

**Comment by bmsleight** [comment]
(Repeat of the #320)
[buster-recorder.log](https://github.com/owntracks/recorder/files/4176761/buster-recorder.log)

On a very *minimal* buster installation libcurl4 was needed to install package. 
See lines 91 onwards of log of install attached. 
blob/master/debian/control

**Comment by thomasklein** [comment]
After following the steps and running `sudo apt-get install ot-recorder` I end up with:
```
E: Unable to locate package ot-recorder
```

**Comment by damionx7** [comment]
http://repo.owntracks.org/README.txt

> (Repeat of the #320)
> [buster-recorder.log](https://github.com/owntracks/recorder/files/4176761/buster-recorder.log)
> 
> On a very _minimal_ buster installation libcurl4 was needed to install package.
> See lines 91 onwards of log of install attached.
> blob/master/debian/control
Follow the proper instructions at 
http://repo.owntracks.org/README.txt

**Comment by dannycohn** [comment]
Even after following these steps I'm getting "Unable to locate package ot-recorder"

**Comment by jpmens** [comment]
@dannycohn please explain exactly what you did.

**Comment by dannycohn** [comment]
```
[10:32:37] root@openhab:/home/openhabian# wget http://repo.owntracks.org/repo.owntracks.org.gpg.key
--2020-02-20 10:32:49--  http://repo.owntracks.org/repo.owntracks.org.gpg.key
Resolving repo.owntracks.org (repo.owntracks.org)... 178.62.206.186, 2a03:b0c0:2:d0::9f:9001
Connecting to repo.owntracks.org (repo.owntracks.org)|178.62.206.186|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1691 (1.7K) [application/octet-stream]
Saving to: ‘repo.owntracks.org.gpg.key’

repo.owntracks.org. 100%[===================>]   1.65K  --.-KB/s    in 0s

2020-02-20 10:32:50 (80.0 MB/s) - ‘repo.owntracks.org.gpg.key’ saved [1691/1691]

[10:33:16] root@openhab:/home/openhabian# apt-key add repo.owntracks.org.gpg.key
OK
[10:33:17] root@openhab:/home/openhabian#
[10:33:17] root@openhab:/home/openhabian# echo "deb  http://repo.owntracks.org/debian buster main" > /etc/apt/sources.list.d/owntracks.list
[10:33:24] root@openhab:/home/openhabian# cat /etc/apt/sources.list.d/owntracks.list
deb  http://repo.owntracks.org/debian buster main
[10:33:45] root@openhab:/home/openhabian# apt-get update
Hit:1 https://repos.influxdata.com/debian buster InRelease
Get:2 https://packages.grafana.com/oss/deb stable InRelease [12.1 kB]
Ign:3 https://openhab.jfrog.io/openhab/openhab-linuxpkg stable InRelease
Hit:4 https://openhab.jfrog.io/openhab/openhab-linuxpkg stable Release
Hit:5 http://archive.raspberrypi.org/debian buster InRelease
Hit:6 http://repo.owntracks.org/debian buster InRelease
Get:7 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
Get:8 https://packages.grafana.com/oss/deb stable/main armhf Packages [14.4 kB]
Fetched 41.4 kB in 3s (15.3 kB/s)
Reading package lists... Done
[10:33:59] root@openhab:/home/openhabian# apt-get install ot-recorder
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package ot-recorder
```

**Comment by jpmens** [comment]
If you'd said `armhf` or `raspbian` we could have saved some time; I don't think we have packages for that architecture.

**Comment by dannycohn** [comment]
Sorry to have wasted your time.  

Is there a path forward to getting those images published?

**Comment by jpmens** [comment]
@dannycohn I think it’ll be easier and quicker if you build the Recorder on your Raspi yourself; it’s not difficult, and I think our documentation covers that quite well, but feel free to ask (in a new issue please) if you think something needs clarification.

Building packages for this platform will have to wait for me to have an appropriate Raspi, install the software and the prerequisites, set up the build environment appropriately, etc., and I do not see this happening soon.

**Comment by linusg** [comment]
I have zero experience with (Debian) packaging - but if someone can point me into the right direction I'd be happy to setup builds on a Raspberry Pi and upload them somewhere, preferably in an automated way.

While I appreciate the possibility to build a project from source, most of the time I prefer to `apt install` something, too...

**Comment by jpmens** [comment]
We run packaging as in `etc/debian/` using FPM (`fpm-make.sh`), so that’s not the problem. The packages then need to be signed with our key which is something I can currently do. I’ve been doing this for the other architectures/platforms, just don’t have the time right now.

As you’re a team member, if you have cycles left over and produce the `.deb`, handing it or a link to it to me over Mattermost, I would sign it and upload it.

**Comment by jpmens** [comment]
@dannycohn thanks to work done by @linusg we should now have the package you require. Can you please try installing that to see if it works for you?

```
apt-get update
apt-get install ot-recorder
```

should be along the lines of what you need.

**Comment by dannycohn** [comment]
I'm still getting `E: Unable to locate package ot-recorder`.  I followed the steps to add the source:

```
curl https://raw.githubusercontent.com/owntracks/recorder/master/etc/repo.owntracks.org.gpg.key | sudo apt-key add -
echo "deb http://repo.owntracks.org/debian buster main" | sudo tee /etc/apt/sources.list.d/owntracks.list > /dev/null
```

followed by 
```
apt-get update
apt-get install ot-recorder
```

Did I miss a step?

**Comment by jpmens** [comment]
@dannycohn you did not miss a step: I did. That's what happens when I try and "patch" in things which I should do properly to start with, but don't have time for.

If you try the installation again, it may now work.

**Comment by dannycohn** [comment]
Still no luck

**Comment by jpmens** [comment]
I'm really sorry -- we don't typically work this sloppily. I'm now 450 kms away from the scene
of the disaster so the only thing I can offer is for you to download

`http://repo.owntracks.org/debian/pool/main/o/ot-recorder/ot-recorder_0.8.4-0-deb10.2_armhf.deb` manually and do a

```
dpkg -i ot-recorder*.deb
apt-get update
```

(I'm not 100% sure of the latter; IIRC `dpkg` begins an installation which `apt` then completes.)

**Comment by machv** [comment]
Hi @jpmens, @linusg,
thank you very much for your help with this package, I've just tried to install the package manually using `dpkg` but I noticed this error:
```
# dpkg -i ot-recorder*.deb
Selecting previously unselected package ot-recorder.
(Reading database ... 41773 files and directories currently installed.)
Preparing to unpack ot-recorder_0.8.4-0-deb10.2_armhf.deb ...
Unpacking ot-recorder (0.8.4-0-deb10.2) ...
Setting up ot-recorder (0.8.4-0-deb10.2) ...
chown: cannot access '/usr/bin/ocat': No such file or directory
chown: cannot access '/usr/sbin/ot-recorder': No such file or directory
dpkg: error processing package ot-recorder (--install):
 installed ot-recorder package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 ot-recorder
```

So I checked the content of the `armf` package, and it'ss placing binaries to `/usr/local/(s)/bin/` folder, compared to `amd64` package, which is placing the binaries to `/usr/(s)bin/` folders. So probable because of the `postinst` script that is referencing to `/usr/(s)bin/` the installation is failing for `armf`?

I don't have any build environment available right now to prepare the updated package, can someone please look into this?

**Comment by dannycohn** [comment]
I encountered the same problem

**Comment by jpmens** [comment]
Sorry this has taken such a long time, but I think we've finally got it: packages for Raspbian (Buster 10) `armhf` should now be installable.
