### ISSUE TITLE
Ignore zero coordinates values?

### ISSUE THREAD

**Issue by glynhudson** [owntracks/recorder#321]
Is it possible for recorder to ignore zero coordinates values? 

It really messes up my data when occasionally my device posts a e.g 0.00000,000000 coordinate location. Obviously this should be fixable at the client device level, however it would be a useful to be able to sanitise incoming data at the recorder level.

**Comment by jpmens** [comment]
Can you say which device / version does that? I don't think we've seen that happen for a long time on our clients. It's also difficult to suppress, as 0.00,0.00 are valid coordinates :)

**Comment by glynhudson** [comment]
It's a custom integration I'm working on with [OVMS vehicle monitoring system](https://www.openvehicles.com) system. I'll work on fixing it at the device level. I'm confident 0.00,0.00 co-ordinates won't be needed anytime soon for my application!

**Comment by jpmens** [comment]
OVMS looks like Open Source, and it's great to hear you're adding OwnTracks capabilities to it. You are welcome to submit either just a link or a PR to our booklet (Clients page) when you've got something workable. :-)
