### ISSUE TITLE
CentOS Install Problem

### ISSUE THREAD

**Issue by myproxy1** [owntracks/recorder#323]
hi.
i want to install owntracks on centos7 but repo file removed from server

http://download.opensuse.org/repositories/home:/oojah:/mqtt/CentOS_CentOS-7/home:oojah:mqtt.repo

Resource is no longer available!

and when i run this command:
sudo yum install ot-recorder

show this error:

--> Processing Dependency: libmosquitto1 for package: ot-recorder-0.8.4-1.x86_64
--> Finished Dependency Resolution
Error: Package: ot-recorder-0.8.4-1.x86_64 (owntracks)
           Requires: libmosquitto1

**Comment by jpmens** [comment]
The repository you link to is not under our control. I think you should be able to follow Mosquitto installation from mosquitto.org

**Comment by ChrissW-R1** [comment]
Same issue here.

The repository is from the mosquitto.org website, but doesn't exist anymore. Mosquitto itself could installed from the EPEL repository, bur the ot-recorder package couldn't. It needs the package libmosquitto1, which is not in the EPEL repository.

**Comment by groovenectar** [comment]
Running into this as well

**Comment by jpmens** [comment]
We're no longer building packages for CentOS 7.

**Comment by jpmens** [comment]
We have just now published `0.9.0` for CentOS 7.
