### ISSUE TITLE
publish message

### ISSUE THREAD

**Issue by ha8sh** [owntracks/recorder#324]
hi.
i setup recorder and connect to sim808 for gps tracker.
i want publish a message to broker and get it using sim808 and trun off/on a relay.
how can i send publish using html in recorder?
i want send it just from recorder web panel not any other app.
thanks.

**Comment by jpmens** [comment]
You cannot send location publishes from the recorder's web panel.

I think you'll want your sim808 to publish something (via HTTP) to the recorder, but we cannot help with that.

**Comment by jpmens** [comment]
Closing as answered.
