### ISSUE TITLE
Disable syslog and/or configurable debug level

### ISSUE THREAD

**Issue by Thulinma** [owntracks/recorder#325]
Hey all!
This is something I'm pondering opening a pull request for. Before I get started on making the needed modifications, I'd like to check if there is interest in merging something like this at all.

I have the following changes in mind:
- Add an option to no longer log to syslog but instead to stdout or stderr (better integration with systemd, which expects logs on stdout/stderr)
- Add another option to configure the debug level - right now everything is always logged (though I suppose there is "--quiet" which helps a little), but as an example I really don't need every single HTTP request in the log messages. A configurable log level would help with this, so errors/warnings are still logged but normal usage messages could be suppressed.

If I implemented this, would you guys be interested in merging it?

**Comment by jpmens** [comment]
Thanks for your suggestion. I think it's a good idea, and yes, we would take it.

**Comment by jpmens** [comment]
Closing as stale.

**Comment by thornick** [comment]
I am running ot-recorder for years now. Recently I have added revgeo, which works nicely together.
But I noticed that now all the geocoded adresses are logged to syslog, which I'd like to suppress.
I found this issue looking after a similar option. But looks somehow abandoned. Is there any other way instead  commenting the related lines and recompiling?

**Comment by jpmens** [comment]
@thornick ot-recorder has always produced stdout/stderr which may or may not, depending on your configuration, be added to syslog/journal, so I'm not quite sure which data you speak of.

Can you provide an example, please?

**Comment by thornick** [comment]
Right ot-recorder always produced messages which I had no problems with. Until now, seeing geocoded data in there 

E.g.
Jan  7 08:42:36 srv ot-recorder[1217]: ot recorder[1217]: http: GET /api/0/locations
Jan  7 08:42:36 srv ot-recorder[1217]: http: GET /api/0/locations
Jan  7 08:48:59 srv ot-recorder[1217]: =33.652222444195 [DE] streetname 17, 373838 Bigtown Germany

**Comment by jpmens** [comment]
Ah, so until recently you didn't have geocodidng set up at all.

I _think_ you're probably seeing the verbose output which is on by default. You can silence that by adding `--quiet` to the invocation of `ot-recorder`. Does that work for you?
