### ISSUE TITLE
Start recorder with TLS and default system CA?

### ISSUE THREAD

**Issue by chrgro** [owntracks/recorder#326]
Hi. I'm using MQTT with a certificate that's signed with Letsencrypt. My mosquitto.conf is like this:
```
port 8883
require_certificate false
cafile /etc/letsencrypt/live/example.com/chain.pem
certfile /etc/letsencrypt/live/example.com/cert.pem
keyfile /etc/letsencrypt/live/example.com/privkey.pem
[...]
```

However when starting up the recorder, I seem to only be able to enable TLS on the recorder if I also specify the CA. I do this by invoking docker run like this:
```
sudo docker run \
        -p 8083:8083 \
        -v /var/owntracks/recorder/store:/store \
        -v /etc/letsencrypt/live/:/etc/letsencrypt/live/:ro \
        -v /etc/letsencrypt/archive/:/etc/letsencrypt/archive/:ro \
        -e OTR_HOST=example.com \
        -e OTR_PORT=8883 \
        -e OTR_USER=username \
        -e OTR_PASS=password \
        -e OTR_STORAGEDIR="/store" \
        -e OTR_CAFILE=/etc/letsencrypt/live/example.com/chain.pem \
        -e OTR_CERTFILE="" \
        -e OTR_KEYFILE="" \
        --name recorder \
        owntracks/recorder
```
I've tried a bunch of combinations with specifying CAFILE, CERTFILE, KEYFILE and so on. None if it works and I get assorted kind of cert errors. 
The recorder says: 
```
ot-recorder[7]: HTTP listener started on 0.0.0.0:8083
ot-recorder[7]: Using storage at /store with precision 7
ot-recorder[7]: MQTT connection: rc=8 [A TLS error occurred.] (errno=0; No error information). Sleeping...
```

While the mosquitto log says this:
```
1576012952: OpenSSL Error: error:14037418:SSL routines:ACCEPT_SR_KEY_EXCH:tlsv1 alert unknown ca
1576012952: OpenSSL Error: error:140370E5:SSL routines:ACCEPT_SR_KEY_EXCH:ssl handshake failure
```

Since I'm using a publicly accepted cert I don't think I should need to specify a CA file in the recorder setup. I don't have to do that for the owntracks android app, that cleanly authenticates with mosquitto by just enabling the TLS option. Is that correct? How can I start the recorder (preferably in docker) with TLS enabled but by relying on the OS default CAs?

**Comment by jpmens** [comment]
It is correct that you must specify the CA root certificate as that is used to validate the certificate of the MQTT broker: we don't use any defaults.

Your comparison with our Android app is valid, however, in the case of the app, we already have the root CA in  the Android certificate store provided by the OS so we can validate from that.

For the record, in your above invocation you can omit `OTR_CERTFILE` and `OTR_KEYFILE`; they default to none anyway.

**Comment by chrgro** [comment]
Thanks a lot of the information!

I'm still struggling to get the recorder to accept the certificate of the MQTT server.

My certificate is signed with this chain: 
![image](https://user-images.githubusercontent.com/1118158/70826495-5e99a580-1de7-11ea-9a14-c77e5def4546.png)

I've tried to copy out the CA details from both a browser targeting the same URL as well as the letsencrypt webpage for this CA directly: https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem.txt 

I have mounted storage with this cert and passed it with OTR_CAFILE (and no other CERT/KEY variables), but still no luck. Do I need the whole chain as the CA file or is there something else I'm missing?

**Comment by chrgro** [comment]
... and just as I post my comment, I was able to make it work :).

Turns out I needed the very root certificate in .pem format. I finally found this file on this page: https://letsencrypt.org/certificates/ by following the .pem link under "Cross signing". To be specific I needed this CA: https://letsencrypt.org/certs/trustid-x3-root.pem.txt

Thanks for the help :)

**Comment by jpmens** [comment]
I was just going to ask you whether you’re sure you are using PEM formatted certificates. Generally, in Unix, software expects PEM.

Glad you got it working.
