### ISSUE TITLE
HTTP code 200: JsonParseException

### ISSUE THREAD

**Issue by gardiol** [owntracks/recorder#332]
Hi!
just installed recorder (git master) on my server, compiled ok and started. 
I have installed OwnTrack on my android phone and configured the endpoint. 

I use HTTP endpoint, no MQTT. For these tests i am running only ot-recorder directly, no web server proxy.

The storage folder is there and it's populated with  two files under the ghash folder. (data.mdb and lock.mdb).

filesystem permissions seems correct.

Recorder does not record any points.

The android app says the enpoint is configured and 0 points are queued... so i would expect to see at least one point in the recorder web page... but none.

The android add has a "status" page where i see "endpoint state message" "HTTP 200  JsonParseEception". Which seems... strange. 200 means OK, so why an exception?

Is there a way to log incoming requests or enable debug output on screen?
How can i debug this?

thank you

**Comment by jpmens** [comment]
If you start the recorder on the console you should see requests as they appear. It would seem to me you've not correctly configured the HTTP endpoint on your Android OwnTracks client.

**Comment by gardiol** [comment]
It might be, can you give me an example?
I am using:

http://myserver,org:8889

i set up port 8889 on recorder OTR_HTTPPORT in my config.

**Comment by jpmens** [comment]
I believe this is documented.

**Comment by gardiol** [comment]
Yes, fixed... I was missing /pub at the end of the endpoint... Now it just works!!


Il 31 gennaio 2020 12:41:23 CET, JP Mens <notifications@github.com> ha scritto:
>I believe this is documented.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/owntracks/recorder/issues/332#issuecomment-580700659

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by jpmens** [comment]
glad you got it going.
