### ISSUE TITLE
Configuration lua hook

### ISSUE THREAD

**Issue by ExarchD** [owntracks/recorder#335]
I noticed that it seems to be impossible currently to use a lua hook to send configuration details as described here:
https://owntracks.org/booklet/tech/json/#_typecmd

The payload requires that there's a nested table, which is not currently supported by the code in hooks.c:
`{"_type":"cmd","action":"setConfiguration","configuration":{"_type":"configuration",...}`

I figured I could just add a new clause in the switch [here](https://github.com/owntracks/recorder/blob/master/hooks.c#L347), to look for a LUA_TTABLE object. That seems to work fine, but I don't know enough about looping through C/lua tables to actually process the nested information.

Is there any possibility this could be added?
Thanks!

**Comment by jpmens** [comment]
Can you elaborate as to what you would need this for, please?

**Comment by ExarchD** [comment]
My thought was that if I can send configuration changes from the recorder, I can create a smart or hybrid reporting mode. I could configure the owntrack app to switch into high accuracy mode when there's a significant change in location, and back to lower accuracy when the location has been stationary for a while.

**Comment by jpmens** [comment]
You should already be able to do this by detecting the change of data in your Lua script and then launching an external (Lua/shell/Python/etc) program which actually publishes/sends the required configuration change message with its payload.

Would that be a compromise?

**Comment by ExarchD** [comment]
I suppose that would work fine, I just thought that since otr_httpobject is designed to return a json object to the owntracks app, it would be the most appropriate method.

**Comment by jpmens** [comment]
Closing as solution given.
