### ISSUE TITLE
Connecting docker to a local install of mosquito

### ISSUE THREAD

**Issue by compusolve-rsa** [owntracks/recorder#341]
I got the recorder app (ot-recorder via ppa) running on ubuntu without docker. However when I tried to run the recorder (docker version) it gives no clue how to configure the docker container to the connect to the  installed mosquitto service on ubuntu.

Any pointers welcome.

**Comment by jpmens** [comment]
I believe this [is documented](https://github.com/owntracks/docker-recorder).

**Comment by compusolve-rsa** [comment]
Thank you.

**Comment by jpmens** [comment]
Closing as answered.
