### ISSUE TITLE
Owntracks Recorder complex views date filter

### ISSUE THREAD

**Issue by taggartist** [owntracks/recorder#342]
I've been absolutely loving Owntracks for the last month. I've setup Owntracks Recorder alongside the awesome frontend UI and I've already worked through some really nifty customizations (cards, friends, hooks and more). A huge thank you to all of you fine people for lending your time and energy to building and maintaining this awesome location sharing platform! 

My question relates to a feature of Owntracks Recorder: Views. Per the documentation, I understand there are two different ways to define a time filter in a view's JSON; either hard-code a "from" and a "to" which will bound the locations retrieved, or alternatively define "hours" (since now) for which to retrieve locations. Furthermore, I see that the default "from" is now minus 6H and the default "to" is now. 

I would like a view that shows:
- from now minus 30 days
- to now minus 7 days

By using the "hours" parameter, I can accomplish the first part ("hours" : "720") but I cannot figure out how to hide the last 7 days (168 hours) from this view. So my questions: Is there some way I could encode this using the view's JSON? Alternatively, how might I alter the default from/to values for all my views?

My reason for asking, I want to create a view that I can embed into my travel blog that shows where I've been recently but for safety/privacy reasons, I don't want the general public to see exactly where I am right this very instant. Unfortunately I'm not savvy enough to dig into the code and figure this out myself, but again I thank you all for your savviness and your help!

**Comment by jpmens** [comment]
@taggartist thanks for the kind words; glad you're liking it.

I don't think we can actually currently do what you wish other than by setting exact dates which is, I think what @ckrey was referring to:

```json
{
  "user"  : "jjolie",
  "device": "phone",
  "page"  : "vmap.html",
  "from"  : "2015-06-29",
  "to"    : "2015-07-15"
}
```

What we typically do is to create a mapping file as documented and "nail" `from` and `to` dates in that, i.e. in above example Jane is on tour from June 29th through July 15th. When she returns, the view will continue functioning but will display data until July 15th only.

If you want a sliding window, you'd have to currently automate the creation of the map file.

**Comment by taggartist** [comment]
Thank @jpmens and @ckrey for looking in to my question. I suspected it might not be possible out-of-the-box, but I greatly appreciate your explanation. I will explore ways to automate the alteration of the map file as you've described, such that the `from` and `to` dates follow the appropriate moving window. This should be pretty straightforward to implement on linux. If I come up with something elegant I'll share it here. 

Side note, this pandemic has really taken all the fun out of location tracking (/sarcastic). None of the dots on my maps are moving anymore! Hope you all are staying healthy and at home so we can get back on the map soon. Thanks again.
