### ISSUE TITLE
ot-recorder via docker

### ISSUE THREAD

**Issue by compusolve-rsa** [owntracks/recorder#344]
ubuntu 16.xx
docker 19.xx

The cli commands to run the recorder don't work for my server. As a workaround I installed ot-recorder from the ubuntu ppa to start testing. Any suggestions on how to get the docker image working correctly?

**Comment by jpmens** [comment]
“Don’t work for my sever” is not really very helpful, to be honest.

It might help if you detailed what you did, what you expected to happen, what errors you saw.

**Comment by compusolve-rsa** [comment]
Here are the steps I followed

```
sudo mosquitto -c /etc/mosquitto/mosquitto.conf
sudo docker volume create recorder_store
> recorder_store
sudo docker run -d -p 8083:8083 -v recorder_store:/store -e OTR_HOST=mqtt_broker owntracks/recorder
> e5613ed7e2ecffb69afcc4af01072c34062b7e807112ff61d944d166e5c87982
```
I then visit localhost:8083 and see the user-device interface. 
After that click on the LIVE MAP, but no map loads.
Table of current locations also no content
 
```
http://localhost:8083/last/index.html
http://localhost:8083/table/index.html
```
The webpage reports "Unable to connect" on both screens

**Comment by compusolve-rsa** [comment]
Perhaps a more expedient question is can a user install owntracks without synology? I do not know how to set the environment variable for recorder-store or OTR-HOST since I am on a pure ubuntu installation.

**Comment by compusolve-rsa** [comment]
Update. I have set etc/mosquitto/mosquitto.conf listener to 
```
listener 8883 127.0.0.1 
```
then followed it by
```
sudo docker run -d -p 8083:8083 -v recorder_store:/store -e OTR_HOST=127.0.0.1 owntracks/recorder
```
I can see see the device page, but clicking on the live map it is now a white screen with a small square near the top left corner. (no map)

The table page now shows.

**Comment by compusolve-rsa** [comment]
I am using kitematic to handle docker containers.
Have verified the environment variables, host and port, username and password. All good.
There is an issue with permissions when setting the /STORE folder via Volumes in kitematic
```
ot-recorder: /home/machine: Permission denied
ot-recorder[10]: gcache_open: /home/machine//owntracks/store/ghash is not a directory
ot-recorder[10]: Can't initialize gcache in /home/machine/owntracks/store/ghash
```
