### ISSUE TITLE
No Tracking data in Safari v13.1

### ISSUE THREAD

**Issue by Hulliee** [owntracks/recorder#346]
Hi,
I don't get tracking data and the table of current locations is empty in Safari v13.1. 
I do get the current location on the Live map. When I use Chrome on MacOs 10.15.4 or Windows 10 Chrome, I get to see all the data.
The same applies for my iPad and iPhone. Only the Live map is working.
I'm using docker latest v0.8.6.
Is there something I can to investigate?

**Comment by caocerberus** [comment]
same behaviour here

**Comment by jpmens** [comment]
This is an off-by-one error which appeared in #328. Sorry about that. Fixing right now.
