### ISSUE TITLE
Locations empty in Docker install

### ISSUE THREAD

**Issue by darkphoenix** [owntracks/recorder#347]
I am trying to run OwnTracks Recorder in Docker, and it successfully recorded data - there is a .rec file, and even ocat --dump gets all the data points.  Yet when I hit the locations API, open a map or try to use ocat --user <user> --device <device>, I only get an empty list every time.  What am I missing?

**Comment by jpmens** [comment]
Are you using Safari as a Web browser? If so, this bug [has been fixed](https://github.com/owntracks/recorder/issues/346) recently.

**Comment by darkphoenix** [comment]
I was having this issue in Chrome.

**Comment by darkphoenix** [comment]
So I've kind of let this rest as I was busy with other things, but now I'd really like to use some of the OwnTracks data to tog photographs, so it'd be useful if I could actually access it.  This doesn't appear to be a browser problem, but an internal one - I've been experimenting with ocat, and --last and --dump work, but everything else returns an empty list.  Does anybody actually care to help me figure out why that is?  Because I'm honestly at the end of my rope here, the data files seem correct as far as I can tell, but no matter which timespan I give (or even none, with --limit 10 for example) I just never get any results, despite the data clearly being there and --last giving a response.

**Comment by darkphoenix** [comment]
I've figured out, no thanks to your unhelpful help and documentation, that --last and --dump access ghash (reverse geodata) and specific "last" files, so they're not really related.  This leaves me with the following: I have rec files, that as far as I can tell are valid and contain location data, but ocat is apparently failing to parse them, giving me empty results even when I call it specifically on a single file with --limit 100 to avoid just getting no results because I added incorrect filters.  I have no idea why this is, there doesn't appear to be any way to make ocat give me a helpful log output or anything, so I'm stuck.  If this takes much more work to resolve it'll probably be easier to write my own recorder than it is to deal with this mess.

**Comment by jpmens** [comment]
> no thanks to your unhelpful help and documentation

**Comment by darkphoenix** [comment]
So I've resolved it, and it's possibly my own fault somehow, but you should probably document it more clearly - I was using a sub-topic for the location itself, <prefix>/%u/%d/location, and therefore ocat was ignoring that data.  Yaaaaay.  I would've closed this issue now, but I see you got there first.
