### ISSUE TITLE
Card generation from local image fails

### ISSUE THREAD

**Issue by viktak** [owntracks/recorder#349]
Hi,
I am trying to use the "Cards" feature for the first time based on [this page](https://owntracks.org/booklet/features/card/), using `image2card.sh`.

This is the actual command I issue:
```
./owntracks/recorder/contrib/faces/image2card.sh Pictures/viktor.jpg Viktor
```

The command fails with the following error message:
```
./owntracks/recorder/contrib/faces/image2card.sh: 44: convert: not found
{"_type":"card","name":"Viktor","face":""}
```

I have tried copying the picture to the same directory as the script, issuing the command from the same directory, using a png instead of a jpg, but I keep getting the same error message.

Any idea what went wrong?

**Comment by linusg** [comment]
`convert` is an ImageMagick command, which needs to be installed on your system for the script to work.

**Comment by viktak** [comment]
@linusg Thank you, that was it!
