### ISSUE TITLE
Webserver attempts to use chunked encoding even for HTTP/1.0 requests

### ISSUE THREAD

**Issue by nwf** [owntracks/recorder#350]
Like it says in the title: the embedded mongoose server is wired to always send `Transfer-Encoding: chunked` even when the request is `HTTP/1.0`.  This means that things almost work when `ot-recorder` is reverse-proxied behind `lighttpd` but the `api` endpoints get a `502 Bad Gateway`.

Would it be possible to fall back to computing the entire response up front for `HTTP/1.0` requests, or at least failing them with a more descriptive error message (e.g. `505 HTTP Version Not Supported`)?

**Comment by jpmens** [comment]
Thanks for your report. Am I understanding correctly that you're talking to `ot-recorder` with an `HTTP/1.0` client and that you cannot make it speak `1.1`?

That surprises me a bit as neither `Apache` nor `nginx` seem to have that problem, but I have not tried with `lighttpd`.

**Comment by nwf** [comment]
That's correct; until very recently (https://github.com/lighttpd/lighttpd1.4/commit/f7919c1ae39824f5cb965a476710677ffec0c4c2) `lighttpd` always sent `HTTP/1.0` requests to its proxy backends and couldn't parse `Transfer-Encoding: chunked` replies.

After noticing that patch, tho', and jumping up to `HEAD` on my webserver, I now observe that `ot-recorder` is emitting both `Transfer-Encoding: chunked` and `Content-Length` response headers (itself a kind of bogus outcome) and the `Content-Length` is wrong (much more bogus; it is, in particular, much too short) when replying from the `last` api endpoint.  I had to teach `lighttpd` to squash that header from responses, and then magically things worked.

**Comment by jpmens** [comment]
For the record, I believe we fixed the too short `Content-Length` header in https://github.com/owntracks/recorder/commit/31f453ccd3e18749e1f80798ef9249fff916a06e (the commit message inaccurately says "Safari only")

**Comment by jpmens** [comment]
Thank you for your report and help, @nwf. We're replacing the illegal `Content-Length` header by `X-Content-Length` where it might be used by our _Frontend_.

Before:

```
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Content-Length: 469
Transfer-Encoding: chunked
```

After:

```
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
X-Content-Length: 469
Transfer-Encoding: chunked
```

**Comment by nwf** [comment]
Thank you for the heads up, but I believe that the initial bug -- that the server speaks HTTP/1.1 in response to a HTTP/1.0 request -- still stands?

**Comment by jpmens** [comment]
Yes, that's part of the embedded mongoose server, and we cannot easily change that.
