### ISSUE TITLE
Adding location data points in bulk to ot-recorder

### ISSUE THREAD

**Issue by brickmasterj** [owntracks/recorder#351]
From a previous tracking method, I have quite a a lot of location data that I would like to integrate in my current ot-recorder setup. What is the best way to get this data into ot-recorder's store?

I tried formatting it with a Python-script into the format in the .rec-files, for example:

`2018-06-13T18:26:17Z    *                       {"_type":"location","acc":10,"alt":34,"batt":80,"conn":"m","lat":xxx,"lon":xxx,"t":"p","tid":"xxx","tst":1528914377,"vac":0,"vel":0,"_http":true}`

But simply creating a 2018-06.rec file and adding these lines to it (and restarting) does not produce any results. Are there any extra steps required to get ot-recorder to recognize these entries? Or is this totally the wrong way to go about it? I would prefer doing this in an editable fashion (i.e. directly into the database) as opposed to having Python send it all over HTTP requests to ot-recorder to make it easier to weed out conversion errors.

**Comment by jpmens** [comment]
What you’ve done looks good to me. Do note please that there are TABs as separators, at least between the * and the opening JSON brace.

**Comment by brickmasterj** [comment]
Turns out the tab's instead of spaces were the issue, my bad.
