### ISSUE TITLE
Please show accuracy in recorder maps point info pop up

### ISSUE THREAD

**Issue by SlrG** [owntracks/recorder#352]
Please make the recorder maps point info pop up show the gps accuracy information.
![point](https://user-images.githubusercontent.com/978967/95010381-3bb3d880-0629-11eb-9a37-60492f4b0236.png)
![point_acc](https://user-images.githubusercontent.com/978967/95010537-64889d80-062a-11eb-99de-7193360aa7e4.png)

**Comment by jpmens** [comment]
Yes, that's a good idea.

**Comment by jpmens** [comment]
Implemented for leaflet as 

![rabbit-6902](https://user-images.githubusercontent.com/60706/95011310-019a0500-0630-11eb-9ee0-9e76b9b662f9.png)

**Comment by SlrG** [comment]
Wow. Thank you very much! That was lightning fast. :1st_place_medal:
