### ISSUE TITLE
yum update is failing due to unsigned ot-recorder RPM

### ISSUE THREAD

**Issue by ddeighton** [owntracks/recorder#355]
I am running CentOS 7 and I'm unable to upgrade to the latest ot-recorder RPM. I am getting the following error when running `yum update`:

```
Package ot-recorder_0.8.6_x86_64.rpm is not signed
```

It may be the same issue as #239 .

**Comment by jpmens** [comment]
Packages are signed, but we will no longer be providing them for CentOs 7
