### ISSUE TITLE
Question: Any way to have the resolved adress in a mqtt payload ?

### ISSUE THREAD

**Issue by goldriver2** [owntracks/recorder#359]
I'm looking to use owntracks to send a physical adress by notification to specific user and was looking at a way not to use any scripting involving google api to resolve the adress. I see that the adress is already resolved in the app when coordinates are created, can the adree be sent in the mqtt payload along with all other parameters ?

**Comment by jpmens** [comment]
Our apps (Android, iOS) do not add the resolved address (Android: Google or OpenCageData, iOS: Apple) to the MQTT payload sent to the broker, but you could, with an own application, do so: the Recorder, for instance, would simply store that data with the payload.

**Comment by jpmens** [comment]
Closing as answered.
