### ISSUE TITLE
OTR_PORT unsupported in configuration file

### ISSUE THREAD

**Issue by grollinger** [owntracks/recorder#364]
It seems that, similar to #198, OTR_PORT is not taken from the configuration file but only from the environment, if present.

**Comment by jpmens** [comment]
`OTR_PORT` [is read from the config file](https://github.com/owntracks/recorder/blob/fd3f4631f16da09706eb1cde84a65322a24c31cb/misc.c#L141) if present, but it must be an integer value. Do you have quotes around its value? Can you show me the line from your configuration file please?

**Comment by grollinger** [comment]
I had quotes around it, yes.

```
OTR_PORT="1884"
```

without quotes it works. Thank you for the quick response.


```
OTR_PORT=1884
```
