### ISSUE TITLE
mandatory element "properties" missing in GeoJSON linestring export

### ISSUE THREAD

**Issue by ckrey** [owntracks/recorder#367]
RFC https://datatracker.ietf.org/doc/html/rfc7946 specifies "properties" as a mandatory element of the "feature" object.

`ocat -u user -d device -f linestring` output checked with either
- https://geojsonlint.com
- https://geojson.io

reports the problem

Adding `"properties":{}` to the output solves the problem

**Comment by jpmens** [comment]
Fixed, thanks.
