### ISSUE TITLE
Suspicious strncpy usage when geohashing

### ISSUE THREAD

**Issue by a-andreyev** [owntracks/recorder#368]
Hello and thank you for the project!

With GCC 11 I'm getting this compilation error (trying git version in Arch Linux):

```
In function ‘strncat’,
    inlined from ‘get_neighbor’ at geohash.c:110:5:
/usr/include/bits/string_fortified.h:135:10: error: ‘__builtin___strncat_chk’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
```

Here's the mentioned line: https://github.com/owntracks/recorder/blob/a3a518a24da6abf1cf2d28bc9197536ff213f8f1/geohash.c#L110

Didn't managed to handle it yet, going to contribute if will find the solution (not familiar with the code yet).

**Comment by jpmens** [comment]
Fixed and closed via #369
