### ISSUE TITLE
user/device messages stored but not returned by ocat

### ISSUE THREAD

**Issue by paynor** [owntracks/recorder#372]
Freshly installed ot-recorder on debian 10 (from repo.owntracks.org/debian buster). 
Mosquitto broker tested functional with mosquitto_sub and mosquitto_pub in terminal on same host.
Mock location messages sent on terminal are verified stored in a *.rec file in the relevant folder /var/spool/owntracks/recorder/store/rec/norbert/mydevice
Example: 
`mosquitto_pub -h localhost -p 1883 -t "owntracks/norbert/mydevice" -m "_type":"location","tid":"NP","lat":0.1234,"lon":5.6789,"batt":77}" -u "norbert" -P password`
shows up in the *.rec file in the above folder as :
`2021-11-27T02:59:18Z	*                 	{_type:location,tid:NP,lat:0.1234,lon:5.6789,batt:77}`

When served through nginx on the same server, the owntracks recorder webpage seems to be functioning correctly - live map and table options display ok. But the table displayed is empty and no location data is shown on the global map.

Ocat commands in a terminal show that the user and device are registered, but no location data is returned :
`$ocat --list`
`{"results":["norbert","test"]}`
`$ocat --list --user norbert`
`{"results":["mydevice"]}`
`$ocat --user norbert --device mydevice`
`{"count":0,"locations":[]}`

Is there a problem with my mock location message format?
Other suggestions?

**Comment by ckrey** [comment]
You seem to have a problem quoting the message on command line. Try:

```
mosquitto_pub  -u norbert  -t 'owntracks/norbert/mydevice' -m '{"_type":"location","tid":"NP","lat":0.1234,"lon":5.6789,"batt":77}' -P password
```

or - more elegantly - use `jo` (`sudo apt install jo`) and include a timestamp `tst`:

```
jo _type=location tid=NP lat=0.1234 lon=5.6789 batt=77 tst=`date +%s` | mosquitto_pub -u norbert -t 'owntracks/norbert/mydevice' -P password -l
```

**Comment by jpmens** [comment]
@paynor what you're publishing from the command line isn't valid JSON: for one the braces `{`/`}` are missing, and the shell is swallowing your double quotes, and that's what you then get in the `.rec` file.

Proceed as @ckrey has shown you, and you should be good to go.

**Comment by paynor** [comment]
Thanks, you were right, just was a problem with the format of the published. Correcting the JSON using the jo tool did the job, now the test spoofed locations arrive fine and are shown in table view on the web interface.

One more problem though: when LIVE is selected, the world map (osm) is displayed, but with no devices. When selecting historical data (12h etc.) the locations and / or tracks are shown correctly in the OSM view,
When historical data is shown I see this on the output of  ot-recorder 'owntracks/#' :
`ot-recorder[1256]: http: GET /map/index.html
ot-recorder[1256]: http: GET /static/apikey.js
ot-recorder[1256]: http: GET /api/0/locations`
and the various location or tracking data is displayed corrrectly.
When  the live view is selected, I see this on the output :
`ot-recorder[28921]: http: GET /static/apikey.js
ot-recorder[28921]: http: GET /last/pista-micro.png`
and no device positions are shown on the map.

Suggestions?

**Comment by jpmens** [comment]
Are you keeping the live view page open long enough for a device to report its position?

Select live view and then submit a position from your device. Is that displayed?

**Comment by paynor** [comment]
Nothing displayed, even with the device on for a few hours reporting its position, positions confirmed received in the rec file and the browser continually open on the live page.
In the documentation, it says that the owntracks/recorder `a directory called ghash/` must exist.
No such directory in my installation

**Comment by paynor** [comment]
Have identified the problem:
With developer console activated in Chrome, it displays the following error:
`websock.js:18 Connecting to websocket at wss://mysite.com/owntracks/ws/last
websock.js:20 Refused to connect to 'wss://mysite.com/owntracks/ws/last' because it violates the following Content Security Policy directive: "default-src https: data: 'unsafe-inline' 'unsafe-eval'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.`
By temporarily activating the Chrome extension Disable Content-Security-Policy, the live view now shows the position of my device. Apparently other modern browsers give the same blocking result, not just Chrome (have tried Edge and Brave too).
How to correct this error at the server end?
Also, the console shows a 404 on owntracks/last/pista-micro.png. Is this by design or should the file exist?

**Comment by jpmens** [comment]
> Also, the console shows a 404 on owntracks/last/pista-micro.png. Is this by design or should the file exist?

That was a bug, thank you. I've renamed the resource and have added the missing image.

**Comment by jpmens** [comment]
> `wss://mysite.com/owntracks/ws/last`

I can't reproduce that here with Chrome (96.0.4664.55) nor with Safari (15.0) or Firefox (94.0.1).
Can you show your nginx reverse proxy configuration?

**Comment by paynor** [comment]
> Can you show your nginx reverse proxy configuration?

Just to be completely clear - mysite.com is not the real domain. 
As you will see, a few different things are running on the same virtual host.
Here is the nginx configuration, with the real domain name replaced by mysite.com. ,and with the header to allow  'unsafe-inline'
#------------------------------------------------------------------------------------------
server { 
    listen 443;
    ssl on;
    root /usr/share/nginx/MYSITE.COM;
    index index.php index.html index.htm;
    server_name MYSITE.COM www.MYSITE.COM;
    ssl_certificate /etc/letsencrypt/live/MYSITE.COM-0001/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/MYSITE.COM-0001/privkey.pem;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA;
    ssl_prefer_server_ciphers on;
   
   location  ^~ /owncloud/ {
    proxy_pass http://127.0.0.1:8080/;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_redirect off;
    proxy_buffering off; 
    access_log /var/log/nginx/service-access.log;
    error_log /var/log/nginx/service-error.log debug; 
   }

    location /owntracks/ {
        proxy_pass      http://127.0.0.1:8083/;
        add_header Content-Security-Policy "default-src 'self' 'unsafe-inline' https: data:; base-uri 'self';";
        proxy_http_version  1.1;
        proxy_set_header    Host $host;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header    X-Real-IP $remote_addr;
    }

    # Proxy and upgrade WebSocket connection for OWNTRACKS
    location /owntracks/ws {
        rewrite ^/owntracks/(.*)    /$1 break;
        proxy_pass      http://127.0.0.1:8083;
        proxy_http_version  1.1;
        proxy_set_header    Upgrade $http_upgrade;
        proxy_set_header    Connection "upgrade";
        proxy_set_header    Host $host;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # OwnTracks Recorder Views
    location /owntracks/view/ {
         proxy_buffering         off;            # Chrome
         proxy_pass              http://127.0.0.1:8083/view/;
         proxy_http_version      1.1;
         proxy_set_header        Host $host;
         proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header        X-Real-IP $remote_addr;
    }
    location /owntracks/static/ {
         proxy_pass              http://127.0.0.1:8083/static/;
         proxy_http_version      1.1;
         proxy_set_header        Host $host;
         proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header        X-Real-IP $remote_addr;
    }

    # HTTP Mode
     location /owntracks/pub {
        auth_basic              "OwnTracks pub";
        auth_basic_user_file    /usr/local/etc/nginx/owntracks.htpasswd;
        proxy_pass              http://127.0.0.1:8083/pub;
        proxy_http_version      1.1;
        proxy_set_header        Host $host;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Real-IP $remote_addr;#

        # Optionally force Recorder to use username from Basic
        # authentication user. Whether or not client sets
        # X-Limit-U and/or uses ?u= parameter, the user will
        # be set to $remote_user.
        proxy_set_header        X-Limit-U $remote_user;
    }

    location / {
        try_files $uri $uri/ /index.php;
    }

    location ~ \.php$ {
        fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        include snippets/fastcgi-php.conf;
    }
}
