### ISSUE TITLE
invalid strptime format 

### ISSUE THREAD

**Issue by vantino** [owntracks/recorder#373]
Since a few day I get an error msg in my syslog file and some tracks are not displayed.
Here's a typical line:
Nov 30 07:56:50 pi4 ot-recorder[2024]: invalid strptime format on invalid strptime format on invalid strptime format on invalid strptime format on invalid strptime format on invalid strptime format on           

```
t=  tid=rs loc=47.78770,9.42795 []  (u0qxye3)
```

**Comment by jpmens** [comment]
This means that the data the recorder got for a particular position (I have formatted the output you provided above) doesn't contain a valid timestamp on it. If you can narrow down when that ocurred then you can show  us the particular segment from your `.rec` file. (Best not post it here, but send it to support@owntracks.org please, referring to this issue 373.)
