### ISSUE TITLE
Wrong argument type to `gmtime`

### ISSUE THREAD

**Issue by nwf** [owntracks/recorder#375]
As per https://pubs.opengroup.org/onlinepubs/009696799/functions/gmtime.html, `gmtime` takes a `const time_t *`, which is not always synonymous with a `const long *`.  Thus 
https://github.com/owntracks/recorder/blob/dff2e87d1b5bec50be63d54054752def967c3d97/hooks.c#L523 and https://github.com/owntracks/recorder/blob/dff2e87d1b5bec50be63d54054752def967c3d97/hooks.c#L532 are incorrect and can produce errors like
```
hooks.c: In function 'otr_strftime':
hooks.c:532:34: error: passing argument 1 of 'gmtime' from incompatible pointer type [-Werror=incompatible-pointer-types]
  532 |                 if ((tm = gmtime(&secs)) != NULL) {
      |                                  ^~~~~
      |                                  |
      |                                  long int *
In file included from hooks.c:24:
/opt/build/staging_dir/toolchain-arm_xscale_gcc-11.2.0_musl_eabi/include/time.h:57:20: note: expected 'const time_t *' {aka 'const long long int *'} but argument is of type 'long int *'
   57 | struct tm *gmtime (const time_t *);
      |                    ^~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

I believe the correct fix is to declare `secs` as a `time_t` (which is defined, by https://pubs.opengroup.org/onlinepubs/009696799/basedefs/sys/types.h.html, to be an integer or real-floating type) and to insert a cast  to `time_t` on https://github.com/owntracks/recorder/blob/dff2e87d1b5bec50be63d54054752def967c3d97/hooks.c#L529

Yes?

**Comment by jpmens** [comment]
Thank you for noticing. If you feel like submitting a fix, we’ll gladly take it.

**Comment by jpmens** [comment]
Let me know, please, whether you'll be submitting a pull-request for the fix.
