### ISSUE TITLE
DockerHub Tagged Release For 0.8.7?

### ISSUE THREAD

**Issue by metal450** [owntracks/recorder#378]
I just noticed that although the latest tagged release on DockerHub is 0.8.6-12, there's actually a newer 0.8.7 available. Any plans to make this a tagged release available on DockerHub too?

(I never pull from "latest", so that all images have a predictable version, & I can update explicitly/at-will.  The lack of an 0.8.7 tagged release means that I'm stuck on 0.8.6).

Thanks in advance :)

**Comment by jpmens** [comment]
Docker is now on 0.8.8.
