### ISSUE TITLE
Config file equivalent for --norec option

### ISSUE THREAD

**Issue by kri164** [owntracks/recorder#379]
Has ot-recorder a config file equivalent for option --norec?
Something as $OTR_NOREC=true ?
It is more easy to edit config file than systemd unit file.
Thanks

**Comment by jpmens** [comment]
`--norec` disables writing of REC files, so no location history or other similar publishes are stored. This was originally created for experimental purposes only, so no, there is no equivalent config file setting; you'll have to edit the systemd unit file.
