### ISSUE TITLE
Debian 11 "bullseye" support

### ISSUE THREAD

**Issue by downingar** [owntracks/recorder#381]
I was wondering if there were plans to officially support Debian 11 from your repo. What I assume is the main dependency, Mosquitto, is in Debian 11 already: https://packages.debian.org/bullseye/mosquitto. I can of course build from source, but a package in a repo is always nicer.

Appreciate your time!

**Comment by downingar** [comment]
As a followup, liblmdb-dev is missing from the required libraries on the "install from source" guide in the README. I'd be happy to open a PR to address this if that's desired!

**Comment by jpmens** [comment]
We're way behind in packaging, I know, but there's not much I can do about this right now.

Glad you got it installed from source, and if you feel like doing the documentation PR, we'll gladly accept it.

**Comment by olivluca** [comment]
FWIW, on a bullseye armel box I could build a deb after changing one Build-Depends from libconfig8-dev to libconfig-dev

```
diff --git a/debian/control b/debian/control
index eee1911..2517741 100644
--- a/debian/control
+++ b/debian/control
@@ -2,7 +2,7 @@ Source: ot-recorder
 Priority: optional
 Section: net
 Maintainer: JP Mens <jpmens@gmail.com>
-Build-Depends: debhelper (>= 9), libcurl3-dev, libmosquitto-dev, liblua5.2-dev, libconfig8-dev, libsodium-dev, liblmdb-dev
+Build-Depends: debhelper (>= 9), libcurl3-dev, libmosquitto-dev, liblua5.2-dev, libconfig-dev, libsodium-dev, liblmdb-dev
 Standards-Version: 3.9.6
 Vcs-Git: https://github.com/owntracks/recorder
 Vcs-Browser: https://github.com/owntracks/recorder
```
