### ISSUE TITLE
Is it possible to import a gpx file?

### ISSUE THREAD

**Issue by zeko9381** [owntracks/recorder#382]
I want to move from Phonetrack to Owntrack and transfer the data. Phonetrack has an option to export session to gpx, but I can't find a way to import this data to the recorder database.

**Comment by jpmens** [comment]
We don't have a utility with which to do that, unfortunately.

However, if you were interested in dabbling at the task and getting your hands dirtyish, it should not be particularly difficult. :-) 

GPX is an XML format which consists of track points which look like this:

```xml
    <trkseg>
      <trkpt lat="41.6776404842901" lon="-88.0525061810303">
        <ele>213.8</ele>
      </trkpt>
    ...
```

Using Python and something like [https://github.com/tkrajina/gpxpy](gpxpy) you could parse the locations (`lat`/`lon`) from the GPX file and write out the necessary minimal JSON into the `.rec` files.

Let us know if that's something you could envision.

**Comment by zeko9381** [comment]
I can certainly try. I always love a learning opportunity.

**Comment by zeko9381** [comment]
Ok, it works now. Thank you very much. Can I somehow contribute my script to this repo?

**Comment by jpmens** [comment]
Very gladly. Either you have your own repository and we’ll link to it from our Booklet or you can create a pull-request to this (Recorder’s) repository for a directory in, say, `contrib/gpx-to-rec/`.

In the latter case, a `README.md` would be good in which you document what the program does, how to install it, etc.

**Comment by zeko9381** [comment]
I will create a pull request once I have some spare time. Thanks again for your help.

**Comment by jpmens** [comment]
closed via https://github.com/owntracks/recorder/pull/383
