### ISSUE TITLE
Unable to read Device ID with trailing number from database of encryption keys

### ISSUE THREAD

**Issue by atjn** [owntracks/recorder#384]
Hi :) Thanks for making this awesome project!

When I set up my first device, I gave it the device id `galaxy7`. I tested my setup, and concluded that everything worked correctly. The recorder received new location data, which it saved and was able to show on a map.

I then set up [payload encryption](https://owntracks.org/booklet/features/encrypt/#payload-encryption), and was confused to see the following error message in my logs:
```
ot-recorder[14]: no decryption key for atjn-galaxy7 in owntracks/atjn/galaxy7
```
This error message showed up despite the fact that I had correctly added the decryption key with `ocat`.

After a few hours of troubleshooting, I tried to change my device id from `galaxy7` to `galaxy`, and then everything started working again.
I assume that the trailing number is tripping up some RegEx in your code, or something like that.

**Comment by jpmens** [comment]
This should definitely not be regex related, but I'm wondering whether a newline character or something else has been added to the key you added.

Could you please 

```
ocat --dump=keys
ocat --dump=keys | od -cb
```

for yourself (do not show us here, of course) and make sure there is nothing special being printed out in the octal dump? 
I would expect the first  command to show two words: the first is your username/device (`atjn-galaxy7`) and the second the key you chose.

If you need help interpreting the output you can send us the relevant information by email (support@owntracks.org).

**Comment by jpmens** [comment]
> because I switched back and forth between the galaxy and galaxy7 entries a few times

this worries me a bit, but I'm going to have to assume the system is basically working; if it didn't, the payload would not be able to be decrypted and you'd not get the data shown in Recorder.

Background: from the moment you set an encryption key in Android/iOS, the _next_ location publishes will be encrypted and hopefully decrypted on the Recorder end. Depending upon when the key is actually entered/changed on the device and depending on when the device name is changed on the device, this can of course influence how/when the appropriate key is used on the Recorder end.

As you got it working, I will now close this issue, but please do not hesitate to add info if you find you really have an issue.

**Comment by atjn** [comment]
> Background: from the moment you set an encryption key in Android/iOS, the next location publishes will be encrypted and hopefully decrypted on the Recorder end. Depending upon when the key is actually entered/changed on the device and depending on when the device name is changed on the device, this can of course influence how/when the appropriate key is used on the Recorder end.

I did make sure to wait about 20 seconds and check that the correct device id and encryption key was used when swtiching between the two. (my device was sending updates in 10 seconds intervals).

But yeah, let's assume it was a bitflip from a cosmic ray ;)
