### ISSUE TITLE
Add sanity checks to user input

### ISSUE THREAD

**Issue by atjn** [owntracks/recorder#385]
While setting up the recorder for the first time, I encountered several hard-to-debug issues because I was inputting strings that the recorder was not able to properly parse. One example was that the recorder couldn't connect to my MQTT broker because I used special characters in the passwords (but it didn't tell me what was wrong). Another example was #384.

My experience would have been a lot smoother if something had warned me when I used those strings. Therefore I propose making some sort of `sanity_check` function that you pass all user input to. It will then check if the string contains any special characters, spaces, or leading/trailing numbers, and if any of those are present, it simply logs a warning message to let the user know that this string could cause weird problems. I believe that would have made me able to completely avoid all the random issues I had, and it probably would have saved me hours :)

**Comment by jpmens** [comment]
I'm sorry you had a suboptimal experience there. Can you please say how you specified the password? The Recorder doesn't _do_ anything with it except just connect. However, if you specify a password on the shell command line it (the shell) can and will interpret certain metacharacters unless you quote the whole password within `'` single quotes `'`.

I don't think we can start warning people that their passwords contain funny bits ;)

**Comment by atjn** [comment]
I defined the password in the `recorder.conf` file:
```
OTR_PASS = "@#89ygng4tkP#jes^AVS45!SKC*45Py$"
```
This is just a randomly generated password that is generated the same way I generated the original password, which I don't have anymore.
My generator does not use `'` and `"`, so it shouldn't be possible for the recorder to parse it incorrectly.

The recorder did not show any obvious signs that something was wrong, but also didn't log device positions. My broker logged this: 
```
Client <unknown> disconnected due to malformed packet.
```

**Comment by atjn** [comment]
> I don't think we can start warning people that their passwords contain funny bits ;)

That is up to you, this is just a suggestion. But I don't see why you couldn't warn people if it helps minimize random bugs and issues?

**Comment by jpmens** [comment]
> `Client <unknown> disconnected due to malformed packet`

Am I right in thinking you're using Mosquitto? Would it be possible that you configured the Recorder to talk to a Websocket port on Mosquitto instead of on the MQTT port?

**Comment by atjn** [comment]
> Am I right in thinking you're using Mosquitto? Would it be possible that you configured the Recorder to talk to a Websocket port on Mosquitto instead of on the MQTT port?

I don't think that could be the case, given that everything started working as soon as I removed all special characters from the password.

But I'm sorry, I didn't save a lot of debug info because I figured it out pretty quickly and just wanted to move on.

**Comment by jpmens** [comment]
Using your example password from above, and an additional log message showing the password, I don't see a problem. 

```console
$ cat .../owntracks.conf
OTR_PASS = "@#89ygng4tkP#jes^AVS45!SKC*45Py$"

$ ot-recorder ...
...
Apr 12 12:51:09  ot-recorder[23762] <Debug>: Using password: [@#89ygng4tkP#jes^AVS45!SKC*45Py$]
..
Apr 12 12:51:09  ot-recorder[23762] <Info>: Disconnected. Reason: 0x5 [Connection refused: bad username or password]

$ cat mosquitto.log 
...
1649767814: New client connected from 192.168.1.140 as otrosm5 (p2, c0, k60, u'jpm').
1649767814: No will message specified.
1649767814: Sending CONNACK to otrosm5 (1, 0)
1649767814: Received SUBSCRIBE from otrosm5
1649767814:     owntracks/jjolie/# (QoS 2)
1649767814: otrosm5 2 owntracks/jjolie/#
1649767814: Sending SUBACK to otrosm5
1649767823: Received DISCONNECT from otrosm5
1649767823: Client otrosm5 disconnected.

```

In addition that message issued by Mosquitto does not relate to an incorrect password, as can be seen from the program output.

**Comment by jpmens** [comment]
Mosquitto definitely differentiates between [MOSQ_ERR_MALFORMED_PACKET](https://github.com/eclipse/mosquitto/blob/4be56239e99ab4ef47c5ad6089f4a4e7f8ef97f8/src/loop.c#L326)  and authorization error [MOSQ_ERR_AUTH](https://github.com/eclipse/mosquitto/blob/4be56239e99ab4ef47c5ad6089f4a4e7f8ef97f8/src/loop.c#L335)

**Comment by atjn** [comment]
Well, I guess a higher power must just have decided that I shouldn't have it easy today. Sorry for wasting your time :)

**Comment by jpmens** [comment]
It's not a waste of time if you think you've found an error, particulary with a system such as this one which is quite complex to set up as one has to set up all the bits oneself. That's a drawback when striving for data privacy, but we hope it's worth your while. :-)
