### ISSUE TITLE
OTR_HTTPHOST ignored

### ISSUE THREAD

**Issue by plague-doctor** [owntracks/recorder#388]
From the version 0.8.8 the variable OTR_HTTPHOST is getting ignored...
```
# env | grep OTR
 
OTR_PASS=<edited>
OTR_HOST=<edited>
OTR_USER=<edited>
OTR_HTTPHOST=0.0.0.0      <----------- please note
OTR_STORAGEDIR=/store
OTR_TOPIC=owntracks/#
```
but when starting, I get:
```
ot-recorder[10]: version 0.9.0 starting with STORAGEDIR=/store
ot-recorder[10]: connecting to MQTT 
ot-recorder[10]: HTTP listener started on 127.0.0.1:8083
ot-recorder[10]: Using storage at /store with precision 7
ot-recorder[10]: Subscribing to owntracks/# (qos=2)
```
This prevents `ot-recorder` to work properly in Docker.

**Comment by grheard** [comment]
I don't know if I'm right or not, but my interpretation of the README.md section regarding configuration options, the only values that can be passed as environment variables are the ones with a Y in the $ column. OTR_HTTPHOST does not have a Y in that column. Putting OTR_HTTPHOST="0.0.0.0" in the recoder.conf file works in my docker configuration.

**Comment by jpmens** [comment]
Right. @grheard is correct on both counts: `$OTR_HTTPHOST` does not (yet) mean anything, and we've not yet got around to doing #380 

Closing this as answered.
