### ISSUE TITLE
owntracks-recorder Docker Image - "setConfiguration" directly trough Lua Script (otr_httpobject)

### ISSUE THREAD

**Issue by shadowwaking** [owntracks/recorder#389]
Question / Feature Request

Environment:
* owntracks-recorder as Docker Container in pure HTTP Mode (no MQTT at all)
* owntracks app on Android (in HTTP Mode)
* everything is at the latest release

Hello there,

is it possible to integrate an option to respond with a client configuration change trough a lua script (otr_httpobject) ?
At the moment i dont find a way to set the required key / values inside the lua script.

Example:

required String for config change:
`{"_type":"cmd","action":"setConfiguration","configuration":{"_type":"configuration","locatorInterval":222}}`

example.lua (sure, this does not work, it is just to explain the problem)
```
function otr_init()
end

function otr_hook(topic, _type, data)
end

function otr_exit()
end

function otr_httpobject(user, device, _type, data)

	resp = {}
	
	resp["_type"] = "cmd"
	resp["action"] = "setConfiguration"
        resp["configuration"] = {}
        resp["configuration"]["_type"] = "configuration"
        resp["configuration"]["locatorInterval"] = "222"
        
	return resp
end
```

It seems that this is the same issue like  [#335](https://github.com/owntracks/recorder/issues/335).
But in my case i dont find a way to use a external script to do the JSON part without adding extra tools to the container. (eg. php..)

Thank you.

**Comment by jpmens** [comment]
We will not implement this because we favor MQTT over HTTP. If somebody picks this up and feels like taking on the task, we will review it.

Closing for now.
