### ISSUE TITLE
Cyclic docs

### ISSUE THREAD

**Issue by UlisseMini** [owntracks/recorder#391]
![image](https://user-images.githubusercontent.com/26258618/175791108-e3cf8a63-ed20-49ac-a40e-34a07967a82c.png)

Links to

![image](https://user-images.githubusercontent.com/26258618/175791114-1b82d6af-1811-42f6-9856-61c95aa43399.png)

Where are the docs? this is a cycle

**Comment by jpmens** [comment]
the docs are at the location the second red underline points to: [https://github.com/owntracks/docker-recorder](https://github.com/owntracks/docker-recorder).

**Comment by jpmens** [comment]
closed as answered
