### ISSUE TITLE
Add hook for monitoring

### ISSUE THREAD

**Issue by jpmens** [owntracks/recorder#4]
One of these?

* `touch` a file with timestamp of last received message
* Open listening socket which prints "I'm alive"

We need to be able to monitor whether _recorder_ is still alive.

**Comment by binarybucks** [comment]
May I chime in and suggest you touch a Redis key with the current timestamp instead of hitting the FS consistently? 

Also, you could let Systemd do the monitoring so you don't need to send ping messages on a socket. Or do you have a tool in mind that listens for heartbeat messages on a socket?

**Comment by jpmens** [comment]
Good idea.

However: I'm making Redis optional (for those who don't want to install it) which is why the file system. Redis will be preferable

**Comment by binarybucks** [comment]
then write to FS when no Redis is installed and to Redis if it is?

On Sat, Aug 15, 2015 at 10:23 AM, JP Mens <notifications@github.com> wrote:

> Good idea.
>
> However: I'm making Redis optional (for those who don't want to install
> it) which is why the file system. Redis will be preferable
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owntracks/recorder/issues/4#issuecomment-131314743>.
>



-- 
Mit freundlichen Grüßen / With kind regards
Alexander Rust

**Comment by jpmens** [comment]
```
redis 127.0.0.1:6379> hgetall ot-recorder-monitor
1) "time"
2) "1439637395"
3) "topic"
4) "owntracks/holger/xxxx"
```

```
cat monitor
1439636514 owntracks/xxxx/35888
```
