### ISSUE TITLE
Typo in ocat --dump=luadb

### ISSUE THREAD

**Issue by tiptronic** [owntracks/recorder#40]
Using "=" doesn't work:

Correct:
ocat --dump luadb

**Comment by jpmens** [comment]
Not with the version of `getopt_long()` in use here. Optional arguments need to be separated from the option with a `=`.

**Comment by jpmens** [comment]
Which OS/version did you do this on?

**Comment by tiptronic** [comment]
I installed the homebrew-version 0.4.0

**Comment by jpmens** [comment]
You will notice a difference between

```
ocat --dump luadb
```

and

```
ocat --dump=luadb
```

The first dumps the geohash database. The second the content of `luadb`.

**Comment by tiptronic** [comment]
For me the latter says:

ocat --dump=luadb
ocat: option `--dump' doesn't allow an argument

**Comment by tiptronic** [comment]
btw: 
<pre>
Usage: ocat [options..] [file ...]
</pre>
doesn't list the 'dump' option

**Comment by jpmens** [comment]
Kindly keep track of the difference between what's on Github and in Homebrew. Thank you. I don't think it fair to use README on git and code in a "release" :-) 
(And I apologize of course, for not keeping track of what was in homebrew 0.4.0.)

**Comment by jpmens** [comment]
The version you are using says `--dump-ghash` (which shortens to `--dump`)

**Comment by tiptronic** [comment]
Sorry for reading all readme's (after I failed poorly with that earlier) ;)

Since I installed the homebrew version I didn't think about there might be a difference

**Comment by jpmens** [comment]
Please *never* apologize for reading! :-)
The thing is, I don't turn every commit into a homebrew release. (Time is short enough as it is!) If you want bleeding-edge (which you appear to), stick to `git pull` and build yourself.

**Comment by jpmens** [comment]
FYI, I have just built 0.4.1 for you. After update/install, please run:

```
/usr/local/bin/ocat --load=luadb < /dev/null
/usr/local/bin/ocat --load=topic2tid < /dev/null
```
