### ISSUE TITLE
Container Image Tags on Docker Hub

### ISSUE THREAD

**Issue by tobru** [owntracks/recorder#400]
It would be wonderful if there are tags corresponding the recorder release on the Docker Hub. Currently, there is only the "latest" tag and 0.8.6 and older tags available.

**Comment by jpmens** [comment]
I hadn't noticed that's not occuring; I thought multiple tags are permitted:

```console
docker build \
	--build-arg recorder_version=$recorderversion \
	--no-cache \
	--pull \
	-t owntracks/recorder:latest \
	-t "owntracks/recorder:${recorderversion}-${dockerversion}" \
	.
```

I'll see if I can find what I'm doing incorrectly.

**Comment by jpmens** [comment]
Fixed.

**Comment by tobru** [comment]
Thank you very much :rocket:
