### ISSUE TITLE
Cannot compile when WITH_MQTT=no

### ISSUE THREAD

**Issue by atjn** [owntracks/recorder#401]
It is currently impossible to compile the recorder without MQTT support because the new tours code calls the MQTT `publish` function. 

This patch resolves all compilation errors, but I am not sure if it is a good solution:
```patch
--- a/recorder.c
+++ b/recorder.c
@@ -495,7 +495,9 @@ void do_request(struct udata *ud, UT_string *username, UT_string *device, char *
 		}
 
 		if ((js = json_stringify(resp, "  ")) != NULL) {
+#ifdef WITH_MQTT
 			publish(ud, UB(fulltopic), js);
+#endif
 			free(js);
 		}
 		json_delete(resp);
@@ -559,7 +561,9 @@ void do_request(struct udata *ud, UT_string *username, UT_string *device, char *
 		}
 
 		if ((js = json_stringify(resp, "  ")) != NULL) {
+#ifdef WITH_MQTT
 			publish(ud, UB(fulltopic), js);
+#endif
 			free(js);
 		}
 
-- 

```

**Comment by jpmens** [comment]
That is a bug. Thank you, @atjn, for bringing this to our attention; it is indeed something I did not test during implementation. Most of us use OwnTracks and the Recorder in MQTT mode. :-)

Your patch is not incorrect, but I’d wrap the `ifdef` before and after the `json_stringify()`.

I will address this shortly, but it’ll be a few days.

**Comment by jpmens** [comment]
@atjn I have committed a patch which illustrates what I meant and compiles/links cleanly when MQTT is not defined.

I think this should work, but I’d like your confirmation.

**Comment by atjn** [comment]
Awesome! I ran a quick test and everything seems to work.
