### ISSUE TITLE
[SOLVED] Owntracks on raspberry - error gcache_open: mdb_env_open: Cannot allocate memory

### ISSUE THREAD

**Issue by stdestro** [owntracks/recorder#404]
EDIT: I figured it out
as I read in another post adding `Environment="OTR_LMDBSIZE=125829120" `to `/etc/systemd/system/ot-recorder.service` fixed the error `gcache_open: mdb_env_open: Cannot allocate memory`

The service stopped because the mosquitto port in my machine was different. I solved disabling Mosquitto or changing the port
--------------------------------------------------------------------------------------------------------------------------
So, I'm trying to install Owntracks recorder on a Raspberry.
Docker is not an options since there's only a 64bit image.
I tried to install it from packages but after launching the service it fails and I get this error "gcache_open: mdb_env_open: Cannot allocate memory"
I cannot find any solution, any chance someone could point me in the right direction?

```
systemctl status ot-recorder
● ot-recorder.service - OwnTracks Recorder
     Loaded: loaded (/etc/systemd/system/ot-recorder.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2022-10-13 21:41:32 CEST; 14min ago
    Process: 22695 ExecStartPre=/bin/sleep 15 (code=exited, status=0/SUCCESS)
    Process: 22916 ExecStart=/usr/sbin/ot-recorder (code=exited, status=14)
   Main PID: 22916 (code=exited, status=14)
        CPU: 127ms

Oct 13 21:41:32 openhabian ot-recorder[22916]: storage_init(): gc is NULL
Oct 13 21:41:32 openhabian ot-recorder[22916]: gcache_open: mdb_env_open: Cannot allocate memory
Oct 13 21:41:32 openhabian ot-recorder[22916]: gcache_open: mdb_env_open: Cannot allocate memory
Oct 13 21:41:32 openhabian ot-recorder[22916]: gcache_open: mdb_env_open: Cannot allocate memory
Oct 13 21:41:32 openhabian ot-recorder[22916]: gcache_open: mdb_env_open: Cannot allocate memory
Oct 13 21:41:32 openhabian ot-recorder[22916]: gcache_open: mdb_env_open: Cannot allocate memory
Oct 13 21:41:32 openhabian ot-recorder[22916]: connecting to MQTT on localhost:1883 as clientID ot-recorder-openhabian-22916 without TLS
Oct 13 21:41:32 openhabian ot-recorder[22916]: Error: Connection refused
Oct 13 21:41:32 openhabian systemd[1]: ot-recorder.service: Main process exited, code=exited, status=14/n/a
Oct 13 21:41:32 openhabian systemd[1]: ot-recorder.service: Failed with result 'exit-code'.
```

**Comment by jpmens** [comment]
Sorry to hear you're having trouble. Let's see if this fixes it.

Please delete the ghash/*.mdb files in the STORAGE directory which is safe to do as you've not yet collected data I assume.

Then, ensure the environment variable OTR_LMDBSIZE=10485760 is in your environment (you'll want to export it). Then initialize the database with `ot-recorder --initialize` which should complete silently.

If that works, then please modify the systemd Unit file to ensure the above environment variable is set before launching the service. I see the file is at `/etc/systemd/system/ot-recorder.service'). If need be, restart the system in order for systemd to pick up the changes.

**Comment by stdestro** [comment]
Thank you @jpmens as you can see I edited my post with the solution I found after the original post.

**Comment by jpmens** [comment]
Ah, no I hadn’t seen that as I was looking and responding via mail. Anyway, glad you got it sorted.

**Comment by artlog** [comment]
Even if it obvious,
the line to add in /etc/systemd/system/ot-recorder.service right after `[Service]` is 

`Environment="OTR_LMDBSIZE=10485760"`
