### ISSUE TITLE
Issues with logging when no TTY present

### ISSUE THREAD

**Issue by tobru** [owntracks/recorder#408]
The change (aka magic) introduced in https://github.com/owntracks/recorder/commit/d673de82bfcc69cb2f464f71bc56ca8d90d863c8 caused a _little_ headache. I'm running the recorder on Kubernetes (yes, absolutely works fine) and recently upgraded to the latest recorder version. Suddenly, no logs appeared anymore, and I was searching like hell what the issue could be. I even wondered if the earth started to rotate the other way around :earth_africa: 

Turns out: By default there is no TTY when running a process in a Kubernetes Pod and also no syslog facility. Because of that, no logs appeared. After setting `tty: true` on the Pod spec, the logs appeared again. Yay.

May I propose to remove this magic from recorder and introduce a command line flag to explicitely configure the log destination? Either `stdout` or `syslog`. I :heart: being explicit, rather than assumption based.

That would be awesome :balloon:

**Comment by jpmens** [comment]
You seem to have solved the problem with setting `tty: true` so at best we'll put this on the back burner; I can't imagine there are many people running the Recorder on Kubernetes ... ;)

**Comment by tobru** [comment]
Thanks for taking care of my issue :+1: I agree that there is no need for a hurry, especially because a workaround exists. And at least it's documented now in this issue, so _should_ there be any other stranger out there running recorder on Kubernetes, it's here.

**Comment by tobru** [comment]
I confirm that I could remove the `tty: true` workaround in the Pod spec and still get logs. Thanks a lot for taking care of this.
