### ISSUE TITLE
Docker image for arm64

### ISSUE THREAD

**Issue by windsource** [owntracks/recorder#411]
Currently the docker image owntracks/recorder in Docker Hub is only available for amd64. It would be nice to have an image for arm64 as well in order to install owntracks recorder on the new cheap Arm64 CAX-Servers on Hetzner cloud.

**Comment by windsource** [comment]
I just saw that there is already an issue https://github.com/owntracks/docker-recorder/issues/68.

**Comment by jpmens** [comment]
if all went well, there is now an image for ARM:

![rabbit-10504](https://github.com/owntracks/recorder/assets/60706/e24f7eaa-cfee-4a15-b489-17ad82478ff2)

I'd appreciate you letting us know if it works for you.

**Comment by windsource** [comment]
I have tested the image and it works. Thanks a lot!

**Comment by jpmens** [comment]
Thanks for reporting back!
