### ISSUE TITLE
Ideas for missing points/straight lines due to no GPS reception

### ISSUE THREAD

**Issue by gitc23** [owntracks/recorder#412]
Hey guys,

have been using OwnTracks together with Owntracks Frontend for over a week now and really like it! Especially looking at the history of all points is an amazing feature.

When checking out the track/linestring I noticed that all points get connected (which makes sense if you always have your recording device on you). However, in areas with bad to no GPS connection such as in the subway there are no points being recorded. The recorder then proceeds to connect them which leads to long straight lines across the map. Here I was wondering if there would be some way around this.

Maybe there could be some setting that interpolates points at a certain distance threshold? I.e., if the distance between two points is greater than X meters, add a point at every 30m. However, this would only make sense if there also would be an edit mode which allowed people to drag the points to the correct location which would then update the location in the `.rec` file.

The other option would be to incorporate an open source public transit routing API such as [GraphHopper GTFS](https://github.com/graphhopper/graphhopper/blob/master/reader-gtfs/README.md#quick-start) which would supply the route between the two points.

Happy to hear your thoughts on this! If I find the time I'll fork the project and try to add one of the options.

**Comment by linusg** [comment]
Personally I'm strictly against adding 'fake' data, YMMV. In OT Frontend this is solved with the [`map.maxPointDistance`](https://github.com/owntracks/frontend/blob/main/docs/config.md#mapmaxpointdistance) config option.

**Comment by jpmens** [comment]
I agree with @linusg, and I don't think we'd want to inject fake data. My recommendation would be for you to use our [Frontend](https://github.com/owntracks/frontend) solution which, as @linusg mentions, solves the issue.

The other option you mention, incorporating a 3rd-party API, suggests data leakage, which we also wouldn't want to have.

**Comment by gitc23** [comment]
Thank you for your input, I somehow didn't think of checking the Frontend options. Will look into `maxPointDistance`.
