### ISSUE TITLE
routines:OPENSSL_internal:TLSV1_ALERT_INTERNAL_ERROR

### ISSUE THREAD

**Issue by ippocratis** [owntracks/recorder#416]
Spinned up owntracks recorder and mosquitto docker containers
Want to use owntracks with client certificate mutual tls authentication

My docker-compose

```
version: '3'
services:
    mosquitto:
        image: eclipse-mosquitto:openssl
        container_name: mosquitto
        restart: unless-stopped
        ports:
            - "1884:1884"
            - "8883:8883"
            - "8083:8083"
        volumes:
            - "./mosquitto/config:/mosquitto/config"
            - "./mosquitto/data:/mosquitto/data"
            - "/run/media/ippo/TOSHIBA/owntracks-recorder/new/v2/ca.crt:/ca.crt"
            - "/run/media/ippo/TOSHIBA/owntracks-recorder/new/v2/server.crt:/server.crt"
            - "/run/media/ippo/TOSHIBA/owntracks-recorder/new/v2/server.key:/server.key"
            - "./mosquitto/log:/mosquitto/log"
        environment:
            - TZ=Europe/Amsterdam
        user: "1000:1000"
    otrecorder:
        image: ot-arm:latest
        ports:
            - 8083:8083
        volumes:
            - ./config:/config
            - ./store:/store
        restart: unless-stopped
```

My mosquitto.conf

```
persistence true
persistence_location /mosquitto/data/
require_certificate true
use_identity_as_username true
listener 8883
cafile /ca.crt
certfile /server.crt
keyfile /server.key
```

My recorder.conf

```
OTR_TOPICS = "owntracks/#"
OTR_HTTPHOST = "0.0.0.0"
OTR_HOST = "192.168.1.24"
```

Openssl version installed on host

`openssl version`
OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)

Created certs following

https://mosquitto.org/man/mosquitto-tls-7.html

And created the client pkcs#12 cert following

https://owntracks.org/booklet/features/tlscert/

Owntracks android client throws error importing it

```
TLS setup failed: error constructing 
MAC: java.security.InvalidKeyException: 
No installed provider supports this key: com.android.org.bouncycastle.jcajce.PKCS12
```

I guess a general android 13 version for certificates created with openssl v3  as importing it to android's user cert store also fails (can't  read the cert pass)

Converted the PKCS#12 cert to legacy

`openssl pkcs12 -nodes < cert.p12 > temp.pem`

And

`openssl pkcs12 -export -legacy -in temp.pem > legacy.p12`

lecagy.p12 import to android and to owntracks app

owntracks still cant authentice client

Throws error

```
2023-07-07 21:06:28.047 I MQTTReconnectWorker: MQTTReconnectWorker started on threadID: Thread[androidx.work-2,5,main]
2023-07-07 21:06:28.166 E MessageProcessorEndpointMqtt: Failed to reconnect to MQTT broker
org.owntracks.android.services.MqttConnectionException:  (0) - javax.net.ssl.SSLHandshakeException: Read error: ssl=0xb4000077069860c8: Failure in SSL library, usually a protocol error
error:10000438:SSL routines:OPENSSL_internal:TLSV1_ALERT_INTERNAL_ERROR (/usr/local/google/home/prb/src/boringssl/ssl/tls_record.cc:594 0xb40000776e7d7d88:0x00000001)
	at org.owntracks.android.services.MessageProcessorEndpointMqtt.connectToBroker(SourceFile:243)
	at org.owntracks.android.services.MessageProcessorEndpointMqtt.reconnect(SourceFile:46)
	at org.owntracks.android.services.MessageProcessorEndpointMqtt.lambda$reconnect$1(Unknown Source:0)
	at org.owntracks.android.services.MessageProcessorEndpointMqtt.$r8$lambda$3UR4gQL2b_UbF_ekJLIMhafolpU(Unknown Source:0)
	at org.owntracks.android.services.MessageProcessorEndpointMqtt$$ExternalSyntheticLambda0.run(Unknown Source:18)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by:  (0) - javax.net.ssl.SSLHandshakeException: Read error: ssl=0xb4000077069860c8: Failure in SSL library, usually a protocol error
error:10000438:SSL routines:OPENSSL_internal:TLSV1_ALERT_INTERNAL_ERROR (/usr/local/google/home/prb/src/boringssl/ssl/tls_record.cc:594 0xb40000776e7d7d88:0x00000001)
	at androidx.work.impl.utils.WorkForegroundUpdater$1.run(SourceFile:433)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: javax.net.ssl.SSLHandshakeException: Read error: ssl=0xb4000077069860c8: Failure in SSL library, usually a protocol error
error:10000438:SSL routines:OPENSSL_internal:TLSV1_ALERT_INTERNAL_ERROR (/usr/local/google/home/prb/src/boringssl/ssl/tls_record.cc:594 0xb40000776e7d7d88:0x00000001)
	at org.conscrypt.SSLUtils.toSSLHandshakeException(Unknown Source:13)
	at org.conscrypt.ConscryptEngine.convertException(Unknown Source:14)
	at org.conscrypt.ConscryptEngine.unwrap(Unknown Source:369)
	at org.conscrypt.ConscryptEngine.unwrap(Unknown Source:28)
	at org.conscrypt.ConscryptEngine.unwrap(Unknown Source:11)
	at org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(SourceFile:70)
	at org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(Unknown Source:0)
	at org.conscrypt.ConscryptEngineSocket.doHandshake(Unknown Source:90)
	at org.conscrypt.ConscryptEngineSocket.startHandshake(Unknown Source:36)
	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(Unknown Source:83)
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketSecureNetworkModule.start(SourceFile:1)
	at androidx.work.impl.utils.WorkForegroundUpdater$1.run(SourceFile:174)
	... 1 more
Caused by: javax.net.ssl.SSLProtocolException: Read error: ssl=0xb4000077069860c8: Failure in SSL library, usually a protocol error
error:10000438:SSL routines:OPENSSL_internal:TLSV1_ALERT_INTERNAL_ERROR (/usr/local/google/home/prb/src/boringssl/ssl/tls_record.cc:594 0xb40000776e7d7d88:0x00000001)
	at org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
	at org.conscrypt.NativeSsl.readDirectByteBuffer(Unknown Source:16)
	at org.conscrypt.ConscryptEngine.readPlaintextDataDirect(Unknown Source:6)
	at org.conscrypt.ConscryptEngine.readPlaintextData(Unknown Source:21)
	at org.conscrypt.ConscryptEngine.unwrap(Unknown Source:253)
	... 10 more
```

Remarks:
- I'm running owntracks on my local LAN atm until I manage to configure it

- android app connects fine if I disable tls

- running this on a raspberryPi 400 with manjaro

- builded recorder for arm from
 https://github.com/owntracks/docker-recorder/blob/master/Dockerfile

Any ideas appreciated

Thanks

**Comment by ippocratis** [comment]
Maybe the same?

https://github.com/owntracks/android/issues/1225

**Comment by ippocratis** [comment]
Also looks like bouncycastle removed from android 13

https://developer.android.com/about/versions/12/behavior-changes-all#bouncy-castle

**Comment by jpmens** [comment]
Are you able to connect to your Recorder using, say, `mosquitto_sub` with your TLS cert? (`[--cert file] [--key file]`)

**Comment by ippocratis** [comment]
I have also tried to create the certs with the generate-CA.sh script from the owntracks tools
Changed host=192.168.1.24 for it to run

Same errors

**Comment by jpmens** [comment]
I don’t see you using client cert and key in the two sub examples, and the second has a space between two dashes

**Comment by ippocratis** [comment]
Looks like mosquitto_sub returns this error when it cant open the files?

https://stackoverflow.com/a/69138711

**Comment by jpmens** [comment]
File not found is quite self explanatory. 

The trouble is docker isn’t finding your files. See docker documentation about mount options (I think that’s what they’re called) and ensure your cert, CA file, and key can be found.

**Comment by ippocratis** [comment]
> File not found is quite self explanatory. 
> 
> The trouble is docker isn’t finding your files. See docker documentation about mount options (I think that’s what they’re called) and ensure your cert, CA file, and key can be found. 
> 

I have "maped"

- "./ca.crt:/ca.crt"
- "./192.168.1.24.crt:/server.crt"
- "./192.168.1.24.key:/server.key"

In the docker-compose.yml on the mosquitto service

Earlier I thought mosquitto_sub command should be provided with the certs filepath on the host

Providing the filepaths in the mosquitto container returns

`docker exec -it mosquitto mosquitto_sub --cafi
le /ca.crt --cert /server.crt --key /server.key  -h 0.0.0.0 -p 8883 -t "#"`
Error: Protocol error

`docker exec -it mosquitto mosquitto_sub --cafile /ca.crt --cert /server.crt --key /server.key  -h 192.168.1.24 -p 8883 -t "#"`
Connection error: Connection Refused: not authorised.

**Comment by jpmens** [comment]
The last command looks ok to me, however the console output you show doesn't _look_ like it belongs to that one ... Could you please double check?

You'll likely also require `--insecure` on `mosquitto_sub` as you're using an IP to connect to the broker instead of its name; TLS verification cannot proceed.

**Comment by ippocratis** [comment]
Ok
I have come to a working state for the mosquitto container

`docker exec -it mosquitto_container mosquitto_sub -d -h 192.168.1.24 -p 8883 --cafile mosquitto/config/certs/ca.crt --cert mosquitto/config/certs/server.crt --key mosquitto/config/certs/server.key -t '#' -i client`

Client client sending CONNECT
Client client received CONNACK (0)
Client client sending SUBSCRIBE (Mid: 1, Topic: #, QoS: 0, Options: 0x00)
Client client received SUBACK
Subscribed (mid: 1): 0

My settings for the certificates
IP="192.168.1.24"
SUBJECT_CA="/C=SE/ST=Greece/L=Athens/O=ippo/OU=CA/CN=$IP"
SUBJECT_SERVER="/C=SE/ST=Greece/L=Athrns/O=ippo/OU=Server/CN=$IP"
SUBJECT_CLIENT="/C=SE/ST=Greece/L=Athens/O=ippo/OU=Client/CN=$IP"

I am reverse proxying example.com to 192.168.1.24:8883

On the owntracks android app my connection settings are

Mode mqtt
Host example.com
Port 8883
Client ID 192.168.1.24
Tried both with websockets and without withe appropiate protocol mqtt or websockets under mosquitto.conf

Identification
Tried with the CN 192.168.1.24 Username and without
password empty
Device ID phone
Tracker ID YN

Security
TLS toggle is on
Selected the ca cert
and the legacy p12 cert (still the non legacy p12 cert is not accepted) and entered the legacy  p12 cert password

Logs:

MessageProcessorEndpointMqtt: Caused by: java.net.ConnectException: failed to connect to example.com/123.456.789 (port 8883) from /192.168.1.158 (port 45262) after 30000ms: isConnected failed: ECONNREFUSED (Connection refused) 


I think I'm missing something very basic Connecticut to the mosquitto server using the owntracks app

Any help appreciated

**Comment by ippocratis** [comment]
More on this

I was using port 443 with my dynamic dns address and then reverse proxulying it to localhost:8883 where mosquitto was runnig

So I openen 8883 on my router and disabled proxy so I can use directly example.com:8883

Even raw public_ip:8883 and LAN_ip:8883

Even installed the 2.4.10 beta 2 version of the app

In all cases I got error

MessageProcessorEndpointMqtt: Failed to reconnect to MQTT broker
org.owntracks.android.services.MqttConnectionException:  (0) - javax.net.ssl.SSLPeerUnverifiedException: Host: xxxxxx, Peer Host: xxxxxx
	at org.owntracks.android.services.MessageProcessorEndpointMqtt.connectToBroker(SourceFile:243)
	at org.owntracks.android.services.MessageProcessorEndpointMqtt.reconnect(SourceFile:46)
	at org.owntracks.android.services.MessageProcessorEndpointMqtt.lambda$reconnect$1(Unknown Source:0)
	at org.owntracks.android.services.MessageProcessorEndpointMqtt.$r8$lambda$3UR4gQL2b_UbF_ekJLIMhafolpU(Unknown Source:0)
	at org.owntracks.android.services.MessageProcessorEndpointMqtt$$ExternalSyntheticLambda0.run(Unknown Source:18)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by:  (0) - javax.net.ssl.SSLPeerUnverifiedException: Host: xxxxxx, Peer Host: xxxxxxx
	at androidx.work.impl.utils.WorkForegroundUpdater$1.run(SourceFile:433)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Host: 192.168.1.24, Peer Host: 192.168.1.24
	at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(Unknown Source:151)
	at androidx.work.impl.utils.WorkForegroundUpdater$1.run(SourceFile:174)
	... 1 more



O God this got so much in to me
It cant be that hard to configure the android app
is it?

**Comment by jpmens** [comment]
Glad you got Mosquitto running, and nice to see you appear to be able to subscribe to it using your client certificate!

It's not possible to proxy MQTT over TLS (port 8883 typically) over an HTTP server. What ought to work is using Websockets, but you explicitly say you've not configured that in Mosquitto.

My reccomendation, now that you know Mosquitto/mosquitto_sub work, is to try and connect your Android directly to the broker (without proxy). You say your broker is listening on 192.168.1.24 so that's the IP of the MQTT host you configure in the phone, with Port 8883.

(Note: in at least two instances above, you specify `clientID 192.168.1.24`; the MQTT clientID is an identifier of a client, eg. `ippocratis001`, and we can ignore that for now.)

The, under _More on this_, you say you're open port 8883 on router (good!) and are trying to use `example.com:8883`. Note that this is unlikely to succeed: your TLS certificaet is 

```
SUBJECT_CA="/C=SE/ST=Greece/L=Athens/O=ippo/OU=CA/CN=$IP"
```

i.e. it has a common name (CN) of $IP, so that's the name you use during connection to your Mosquitto, unless you've configured it to be `insecure`, which we strongly reccomend you do not do.

Care to give it another shot? And: sorry you've having such trouble, part of which, sadly, is due to the docker stuff.

**Comment by ippocratis** [comment]
Thank you for your patience 

I have come to a working state and managed to connect using my dynDNS subdomain e.g. example.duckdns.org

I had to configure SAN in the server certificate

My "settings" atm

docker-compose.yml

```
version: '3.5'

services:
  mosquitto:
    container_name: mosquitto_container
    image: eclipse-mosquitto:openssl
    volumes:
      - ./config:/mosquitto/config/
    ports:
      - '8883:8883'
    networks:
      - default
    restart: unless-stopped

networks:
  default:
```

config/mosquitto.conf

```
listener 8883

cafile /mosquitto/config/certs/ca.crt
certfile /mosquitto/config/certs/server.crt
keyfile /mosquitto/config/certs/server.key
require_certificate true
use_identity_as_username true
protocol websockets
```
For the creation of the server certificate the commands were

`SUBJECT_SERVER="/C=SE/ST=Greece/L=Athens/O=ippo/OU=Server/CN=$IP"`

`openssl req -nodes -sha256 -new -subj "$SUBJECT_SERVER" -keyout server.key -out server.csr`
                      
`openssl x509 -req -sha256 -in server.csr -CA ca.crt -extfile v3.ext -CAkey ca.key -CAcreateserial -out server.crt  -days 365`

The contents of the v3.ext extfile are

 ```
authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE                               keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment                                  subjectAltName=DNS:example.duckdns.org, DNS:localhost IP:192.168.1.24                                     issuerAltName = issuer:copy
```

For the CN field I didnt have to use it as a username on the app to connect
Maybe that is used as otr user on the recorder? 
App settings:

Connection:
mode mqtt
host example.duckdns.org
Port 8883 (open port on router)
Client ID random name
Websockets toggle enabled

Identification:
Username empty
Password empty
Device ID random name
Tracker ID random name


Security:
TLS enabled
CA cert empty (installed the CA cert in the device user store under settings > security)
Password protected client cert selected
Password filed
Still had  to create the cert and then convert it to legacy (thats another issue maybe?)


I havent configure owntracks recorder for TLS yet 


[Source1](http://www.steves-internet-guide.com/mosquitto-tls/)
[Source2](https://medium.com/himinds/mqtt-broker-with-secure-tls-and-docker-compose-708a6f483c92)

Thanks

**Comment by jpmens** [comment]
> come to a working state and managed to connect 

Am I understanding correctly that you have successfully connected with your Android OwnTracks client?

BTW, and I don't think I've mentioned this yet, some of us believe that using client certificates are quite an amount of overkill; we typically use TLS connections with user/password schemes (protected in transit with TLS) and be done with it.

**Comment by ippocratis** [comment]
> Am I understanding correctly that you have successfully connected with your Android OwnTracks client?
> 


Yes I managed to connect with mtls to the android app using my dynDNS domain as host

>using client certificates are quite an amount of overkill;
>

I've been using owntracks over http amd reverse proxy with username and password for a long time
 Seting up mtls with mqtt always kept me away as I never fully understud the  procedure (I'm a simple user who likes to selfhost,  my networking understanding is pretty basic)

Please don't close the issue yet as I still  have to configure the owntracks recorder 

This is the recorder repo after all (probably this issue was more fitted in the android repo,  sorry)

**Comment by jpmens** [comment]
That's quite all right, and I congratulate you on getting this far. I hope your experience wiring the Recorder to your MQTT broker will be smoother, and let us know if we can help.

There's one thing I'd like to explicitly point out:

```
openssl x509 -req -sha256 -in server.csr -CA ca.crt -extfile v3.ext -CAkey ca.key -CAcreateserial -out server.crt  -days 365
```

This command, as you likely know, has produce a server certificate with a validity of 365 days, so beware that you'll have to revisit that in a year!

**Comment by ippocratis** [comment]
There is probably something wrong with my builded recorder container for my raspberry (?)
Maybe an error I did not catch up on build time
The issue I'm having with it is it does not seem to store any locations
e.g if I launch the webui localhost:8083 no tracks are there,  neither on the livemap

The store dir only contained a ghash folder
`docker exec -it --user root 6-otrecorder-1 ocat list`
failed to open file 'list'
{"locations":[]}

 But the container throws the same error even after I manually create the store/last and store/rec folders

`docker exec -it --user root 6-otrecorder-1 ocat -v`
```
This is OwnTracks Recorder, version 0.9.3
built with:
        WITH_MQTT = yes
        WITH_HTTP = yes
        WITH_TOURS = yes
        WITH_LUA  = yes
        WITH_ENCRYPT = yes
        WITH_PING = yes
        CONFIGFILE = "/config/recorder.conf"
        DOCROOT = "/htdocs"
        DEFAULT_HISTORY_HOURS = 6
        JSON_INDENT = "NULL"
        LIBMOSQUITTO_VERSION = 2.0.14
        MDB VERSION = LMDB 0.9.29: (March 16, 2021)
        SODIUM VERSION = 1.0.18
        GIT VERSION = 0.9.3-0-gced0a401f7
```

The config/recorder.conf is missing and if I manually try to create and fill it the container is "exiting"

Could it be file permissions?
The store and config dir are mounted as volumes in my docker-compose

The recorder produces no console output if I run the docker-compose.yml without the  -d parameter

If I run it-recorder on the live container it throws

`docker exec -it --user root 6-otrecorder-1 ot-recorder`
```
ot-recorder[15]: Skipping open defaults file /config/recorder.conf: No such file or directory
ot-recorder[15]: version 0.9.3 starting with STORAGEDIR=/store
ot-recorder[15]: connecting to MQTT on 192.168.1.24:8883 as clientID ot-recorder-534034c16240-15 with TLS
ot-recorder[15]: HTTP listener started on , without browser-apikey
ot-recorder[15]: HTTP port is in use. Exiting.
```

I guess "HTTP port is in use" is normal as the recorder is alread running?

I have seen https://github.com/owntracks/recorder/issues/258
The user created a missing owntracks/mosquitto/mosquitto.acl in his container 
I don't have an owntracks folder in my container and if I search for a mosquitto folder I see an /etc/mosquitto one

`docker exec -it --user root 6-otrecorder-1 find / -type f -iname '*mosquitto*' 2>/dev/null`
```
/etc/mosquitto/mosquitto.conf
/usr/bin/mosquitto_passwd
/usr/bin/mosquitto_ctrl
/usr/bin/mosquitto_rr
/usr/lib/mosquitto_dynamic_security.so
/usr/lib/libmosquitto.so.1
/usr/sbin/mosquitto
```

Do I need a mosquitto.acl? 
Should I create it under /etc/mosquitto/mosquitto.acl
under /mosquitto/mosquitto.acl
What should it contain?

My guess is that the container loads defaults from /config/recorder.conf as the recorder outputs when I run `docker exec -it --user root 6-otrecorder-1 ot-recorder`

I have passed environmental variable in the docker-compose but maybe those need to be passed in the recorder.conf instead?

yml```
version: '3.5'

services:
  mosquitto:
    container_name: mosquitto_container
    image: eclipse-mosquitto:openssl
    volumes:
      - ./mqtt-config:/mosquitto/config/
    ports:
      - '8883:8883'
    restart: unless-stopped
    networks:
      - default

  otrecorder:
    image: ot-arm:latest
#    image: ensjens/owntracksrecorder
    ports:
      - 8083:8083
    volumes:
      - ./config:/config
      - ./store:/store
#      - ./etc/default/ot-recorder:/etc/default/ot-recorder
    restart: unless-stopped
    environment:
      - OTR_HOST=192.168.1.24
      - OTR_PORT=8883
      - OTR_USER=owntracksippo.duckdns.org
#      - OTR_PASS=
      - OTR_STORAGEDIR=/store
      - OTR_CAFILE=/config/ca.crt
#      - OTR_TOPICS=owntracks/owntracksippo.duckdns.org/phone
      - OTR_TOPICS=owntracks/#
    networks:
      - default
volumes:
  store:
  config:
```

I'm out of ideas at the moment
I'll re-build the recorder container and watch closer for console errors
maybe start from scratch alltogether


Thanks

p.s.
I'm aware for the certificate expiration
I plan to create a clean install with longer certs when (if?) I manage to short all up

**Comment by jpmens** [comment]
Stop the Recorder.

Launch it one-time with the `--initialize` flag which should create the files it requires.

Then launch it normally, preferably in such a way you you see it's output, as you did above.

You ought to then, from your mobile, publish a location and that should show up in `<recorder-store>/rec/<username>/<device>/2023-MM.rec`.

**Comment by ippocratis** [comment]
> Stop the Recorder.
> 
> Launch it one-time with the `--initialize` flag which should create the files it requires.
> 
> Then launch it normally, preferably in such a way you you see it's output, as you did above.
> 
> You ought to then, from your mobile, publish a location and that should show up in `<recorder-store>/rec/<username>/<device>/2023-MM.rec`.
> 
Thanks for keeping up with the issue

I'm struggling to bring the ot-recorder container to running state again

I've tried everything from scratch certs, Dockerfile, yml files, conf files and it is not running

It is constantly exiting now 

I'll come back when i'm back to that state

**Comment by jpmens** [comment]
Have you been able to solve the issue?

**Comment by ippocratis** [comment]
> Have you been able to solve the issue?

I've managed to come to a state where I connect externally using my dens domain name with mosquitto using mtls. 
But
I cant use TLS on the recorder-mosquitto connection. 
I quite OK with this setup for now as this connection happen inside my LAN. 
Did not find the time to troubleshoot this more.
