### ISSUE TITLE
How write intensive is Recorder for my disk?

### ISSUE THREAD

**Issue by stlinkgangs** [owntracks/recorder#418]
Say for instance that I have 20 tags in OwnTracks and MQTT publishes 20 messages per minute, If I would use Recorder for storing every single message, would the LMDB database be able to handle it? Is that bad practice for my SSD? What about other forms of storage, like flash drives or micro SDs? Has anyone made some experience regarding this?

**Comment by jpmens** [comment]
LMDB will have no problem as the actual position records are stored in text files. Whether or not this will cause problems with your SSD is really something that we have not investigated. You're talking 400 writes per MINUTE which is rather trivial an operation for a disk subsystem.

**Comment by stlinkgangs** [comment]
Thanks, that's good to know
