### ISSUE TITLE
Better data browsing

### ISSUE THREAD

**Issue by jp-bennett** [owntracks/recorder#419]
It's a bit of a pain to look up location data for a specific day. I'd love to see something like the Google Maps timeline, where the user could easily flip through the map of points/track data a day at a time.

**Comment by jpmens** [comment]
Have you seen our [Frontend](https://github.com/owntracks/frontend) to the Recorder?

**Comment by jp-bennett** [comment]
@jpmens I had not! That's almost exactly what I was looking for. Thanks!

**Comment by jp-bennett** [comment]
And unsurprisingly, there's an issue on the Frontend repo, asking for exactly this feature. Though the frontend is already quite nice. Cheers!
