### ISSUE TITLE
http server doesnt start when connecting via mqtt

### ISSUE THREAD

**Issue by Gugi264** [owntracks/recorder#420]
When I put in the wrong address for the mqtt service the Http server of the recorder starts as expected.

But when i put in the correct address (atleast I hope its correct, it works from android), the http server doesnt start:

`ot-recorder[7]: version 0.9.3 starting with STORAGEDIR=/store
ot-recorder[7]: connecting to MQTT on example.xyz:8083 as clientID ot-recorder-ada832f2c9cf-7 without TLS
Error: Operation timed out
ot-recorder[7]: version 0.9.3 starting with STORAGEDIR=/store`

**Comment by jpmens** [comment]
>ot-recorder[7]: connecting to MQTT on example.xyz:8083 as clientID ot-recorder-ada832f2c9cf-7 without TLS

8083 is the default HTTP port of the Recorder.
For the MQTT broker I assume you'll want the default of 1883.

**Comment by Gugi264** [comment]
The instant I post this issue, I get it to work with other settings..
I think the biggest problem I had that it was not as verbose as I would like, as I was not sure if it connected to the MQTT broker or not
