### ISSUE TITLE
Question about the store

### ISSUE THREAD

**Issue by lupoalberto12** [owntracks/recorder#421]
Hi.
After three days finding the reason why the docker didn't connect to the broker while the service worked like a charm (today I finally fount that OTR_HOST need "" but OTR_PORT not and "exit 0" error was for bad permission at the certificate files), 
I started the old script in the repo "tools" for Google Location History import, "import-location-history.py": it still works even if in August is changed the json format but I noticed this: 
- in MQTT server (I'm using Mosquitto) the timestamp is correct
- in rec files the timestamp is the moment when the OTRecord read the event, not the timestamp of the event

The question is: is the timestamp in the OTRecord the moment when the service read the event?
If it works in this way, the script is very useless.
And, again, if it works in this way, can it possibile write directly in the rec files?

Thanks.

**Comment by jpmens** [comment]
The script you refer to was contributed in 2017, and I'm not familiar with what it does. If you say it doesn't work, then maybe you'd like to try to fix it, or otherwise we should probably remove it from the repository. Let us know please.

The Recorder stores `_type: location` records with the `tst` timestamp from the location publish, but records which don't have a `tst` are stored with "now" (i.e. reception) time.

**Comment by lupoalberto12** [comment]
Hi jpmens, 
thank you for the response.
The script seems working but the JSON, in the last months, changed:
the old dates were in this format:
```
{
    "latitudeE7": 516518,
    "longitudeE7": 161615,
    "accuracy": 42,
    "source": "wifi",
    "timestamp": "2011-08-24T13:15:04.690Z"
  }
```

now:
```
{
    "latitudeE7": 5618631530,
    "longitudeE7": 18165321,
    "accuracy": 16,
    "velocity": 1,
    "heading": 20,
    "altitude": 247,
    "verticalAccuracy": 2,
    "source": "WIFI",
    "deviceTag": 650220709,
    "platformType": "ANDROID",
    "locationMetadata": [{
      "wifiScan": {
        "accessPoints": [{
          "mac": "657567568798",
          "strength": -72,
          "frequencyMhz": 2412
        }, {
          "mac": "8798978656",
          "strength": -77,
          "frequencyMhz": 2442
        }, {
          "mac": "4564675678",
          "strength": -79,
          "frequencyMhz": 2427
        }, {
          "mac": "89797765456",
          "strength": -82,
          "frequencyMhz": 2437
        }, {
          "mac": "5644345435678",
          "strength": -83,
          "frequencyMhz": 2417
        }, {
          "mac": "576434678690",
          "strength": -84,
          "frequencyMhz": 2457
        }, {
          "mac": "567587690'089",
          "strength": -84,
          "frequencyMhz": 2457
        }, {
          "mac": "'989675443",
          "strength": -87,
          "frequencyMhz": 2457
        }, {
          "mac": "567589780",
          "strength": -89,
          "frequencyMhz": 2462
        }, {
          "mac": "9809896757",
          "strength": -89,
          "frequencyMhz": 2432
        }, {
          "mac": "567657867898",
          "strength": -90,
          "frequencyMhz": 2412
        }]
      },
      "timestamp": "2023-09-07T14:09:50.662Z"
    }],
    "activeWifiScan": {
      "accessPoints": [{
        "mac": "36578768",
        "strength": -50,
        "frequencyMhz": 2412
      }, {
        "mac": "4563452",
        "strength": -55,
        "isConnected": true,
        "frequencyMhz": 5220
      }, {
        "mac": "345365789",
        "strength": -71,
        "frequencyMhz": 2412
      }, {
        "mac": "5435234267",
        "strength": -75,
        "frequencyMhz": 2442
      }, {
        "mac": "23436457568",
        "strength": -80,
        "frequencyMhz": 2427
      }, {
        "mac": "86564563",
        "strength": -84,
        "frequencyMhz": 2437
      }, {
        "mac": "45766575876",
        "strength": -85,
        "frequencyMhz": 2417
      }, {
        "mac": "756743453453",
        "strength": -86,
        "frequencyMhz": 2462
      }, {
        "mac": "4346456",
        "strength": -86,
        "frequencyMhz": 2432
      }, {
        "mac": "453543534543",
        "strength": -87,
        "frequencyMhz": 2412
      }, {
        "mac": "564646433534",
        "strength": -89,
        "frequencyMhz": 5260
      }, {
        "mac": "5345435345",
        "strength": -90,
        "frequencyMhz": 5260
      }]
    }
```

Now Google saves also WiFi SSID information (I think), but the variables are the same ("latitudeE7", "longitudeE7", "accuracy", "source", "timestamp").


With the second information (_The Recorder stores _type: location records with the tst timestamp from the location publish, but records which don't have a tst are stored with "now" (i.e. reception) time._), I understand that the variable _tst_ maybe it didn't well populated, while latitude e longitude were ok: it seems the script didn't read correctly the timestamp.
I'll try with less data and I'll update asap.
Thanks.
Regards.

**Comment by lupoalberto12** [comment]
I found the problem with timestamp:
the code check for "timestampMs":
`		if 'timestampMs' in location_keys:
			payload['tst'] = int(location['timestampMs']) // 1000`

but the variable name in the JSON is "timestamp":
`{
    "latitudeE7": ,
    "longitudeE7": ,
    "accuracy": ,
    "source": "",
    "timestamp": ""
  }`

I'll edit the script and I'll add some sleep for the broker.
I update this after test the script.

**Comment by lupoalberto12** [comment]
Hi.
I changed the line 36 and 37 of the script from this:
```
		if 'timestampMs' in location_keys:
			payload['tst'] = int(location['timestampMs']) // 1000
```
to this
```
                if 'timestamp' in location_keys:
                        payload['tst'] = location['timestamp']
```

in this way, the variable "payload['tst'] " is correctly filled, and I'm sure for the reason that I add a "print" of the variabile; 
I added also a print of messages that:
```
                messages.append(
                        {
                                'topic': args.topic,
                                'payload': json.dumps(payload),
                                'qos': 2
                        }
                )
                print (messages)
```
and the result is this:
`[{'topic': 'mytopic', 'payload': '{"_type": "location", "tid": "Go", "tst": "2021-03-22T11:11:03.690Z", "lat": 66.8421, "lon": 25.56854, "acc": 42}', 'qos': 2}]
`

but in OwnRecord, in the rec file, the result is a file named "1970-01.rec" and the dates are:
`1970-01-01T00:33:31Z    *                       {"_type":"location","tid":"Go","lat":66.8421,"lon":25.56854,"acc":42,"tst":2011}`

I didn't check what is published on Mosquitto: maybe there is a problem with the protocol.

@jpmens can you tell me which is the correct JSON format for OTRecord?
Thanks.
Regards.

**Comment by lupoalberto12** [comment]
I checked the broker:
![image](https://github.com/owntracks/recorder/assets/6494809/5b213954-c755-4a21-96b9-950237dad956)

The JSON seems correct.
It seems that OTRecord not read correctly the message.

Thanks.

**Comment by ckrey** [comment]
In Owntracks, “tst” is always an integer as unix epoch time, not a string containing ISO format. See here: [booklet](http://owntracks.org/tech/json/)

**Comment by lupoalberto12** [comment]
> In Owntracks, “tst” is always an integer as unix epoch time, not a string containing ISO format. See here: [booklet](http://owntracks.org/tech/json/)

              In Owntracks, “tst” is always an integer as unix epoch time, not a string containing ISO format. See here: [booklet](http://owntracks.org/tech/json/)

_Originally posted by @ckrey in https://github.com/owntracks/recorder/issues/421#issuecomment-1714363532_
            
Hi ckrey, 
thank you for the answer.
The link goes in 404, can you send me the correct one?

Anyway, now I understand why the OTrecord cannot record the correct time: it isn't a integer and in the JSON file it isn't in ms format.

I looking for transform the date in integer (if it possible, I don't know Python, I'm not a developer).

Thanks.

**Comment by lupoalberto12** [comment]
> > In Owntracks, “tst” is always an integer as unix epoch time, not a string containing ISO format. See here: [booklet](http://owntracks.org/tech/json/)
> 
> ```
>           In Owntracks, “tst” is always an integer as unix epoch time, not a string containing ISO format. See here: [booklet](http://owntracks.org/tech/json/)
> ```
> 
> _Originally posted by @ckrey in [#421 (comment)](https://github.com/owntracks/recorder/issues/421#issuecomment-1714363532)_
> 
> Hi ckrey, thank you for the answer. The link goes in 404, can you send me the correct one?
> 
> Anyway, now I understand why the OTrecord cannot record the correct time: it isn't a integer and in the JSON file it isn't in ms format.
> 
> I looking for transform the date in integer (if it possible, I don't know Python, I'm not a developer).
> 
> Thanks.

I found, I can use: 
`now.strftime("%Y%m%d%H%M%S")`

I try asap and then report here!
Thanks.

**Comment by jpmens** [comment]
The [JSON in the OwnTracks Booklet](https://owntracks.org/booklet/tech/json/)

**Comment by lupoalberto12** [comment]
> The [JSON in the OwnTracks Booklet](https://owntracks.org/booklet/tech/json/)

Hi jpmens, 
thanks for the link.

I cannot check yet to convert the test in int, but my last message was wrong (it doesn't convert, it is just the date).

Thanks.

**Comment by lupoalberto12** [comment]
Hi.
I corrected the script and I'm using it.
I created a fork of the repo, edit it and create a request pull.
The file is this:
https://github.com/lupoalberto12/owntracks_tools/blob/master/Google/import-location-history.py

You can close this issue.
Thanks
