### ISSUE TITLE
No logs in Docker output

### ISSUE THREAD

**Issue by mbrennan** [owntracks/recorder#426]
Hello,

I was able to get the Recorder to successfully connect to my broker after struggling for quite some time.  It turned out the problem was I am using the websockets protocol on my Mosquitto broker which was not compatible with the Recorder.  I opened up another listener on a different port in Mosquitto with protocol 'mosquito' and had the Recorder connect to the new listener.  This seemed to connect successfully as I can see output in the mosquitto logs for my Recorder user and running `ocat --list` shows: `{"results":["me"]}`

However, I still don't see any data in my Recorder when I visit the web interface and look at the table.  I tried to see if there are any interesting things in the log in the Recorder but the log is empty.  When I run the recorder from the Docker image's command line directly, I can see some output but all seems well.  I don't know why I can't see the output in the Docker log (the logs work fine for the 43 other containers I'm running.

How can I get the Recorder to output the logs correctly to stdout?  It seems like it has something to do with the ``--logfacility`` switch.  Why can't I see any data in my Recorder?

**Comment by jpmens** [comment]
Regarding the missing data: could you please launch the container with a console `docker run ... -it`, publish a location, and report what you see on the console?

**Comment by jpmens** [comment]
We have released 0.9.5 and docker images have been published which hopefully solve the issue with the logs; `docker logs` should now show the Recorder's log

**Comment by jpmens** [comment]
0.9.6 is out.

**Comment by jpmens** [comment]
I am closing this now as this issue concerns mainly docker logging.

Please open a new issue if you require help with "missing data". Thanks!
