### ISSUE TITLE
Debian Bookworm Support

### ISSUE THREAD

**Issue by TheGreyDiamond** [owntracks/recorder#427]
Is there any timeframe for Debian Bookworm support via apt-repo?

**Comment by jpmens** [comment]
Thanks for the wake-up call, and there is a timeframe for Debian Bookworm support: NOW.

We've just released packages `0.9.6` for Debian 12 AMD64, ARM64, ARMHF.

Enjoy.

**Comment by jpmens** [comment]
Closing as completed.

**Comment by TheGreyDiamond** [comment]
Thank you very much!
