### ISSUE TITLE
OTR_STORAGEDIR vs STORAGEDEFAULT

### ISSUE THREAD

**Issue by dlangille** [owntracks/recorder#429]
Are `OTR_STORAGEDIR` and `STORAGEDEFAULT` related?

I ask because updating from `0.9.2` to `0.9.6` is giving `Can't initialize gcache in /var/spool/owntracks/recorder/store/ghash`

I see that is a default value in `ot-recorder.conf`

On FreeBSD, the value for `STORAGEDEFAULT` is `/var/db/owntracks/recorder/store` and is achieved by patching `config.mk.in` - [1]

If the two variables are the same values, I will update my `/usr/local/etc/ot-recorder/ot-recorder.conf` and adjust `OTR_STORAGEDIR` from

`/var/spool/owntracks/recorder/store`

to

`/var/db/owntracks/recorder/store`

I didn't want to make that change before verifying that is correct for fear of mucking up my data.

I can also patch the FreeBSD port for this.

1 - https://cgit.freebsd.org/ports/tree/www/ot-recorder/files/patch-config.mk.in#n33

**Comment by jpmens** [comment]
The `OTR_STORAGEDIR` configuration setting (e.g. from `recorder.conf`) is initialized from the value of `STORAGEDEFAULT` which is set via the `Makefile`, probably from `config.mk`.

**Comment by dlangille** [comment]
This was my own fault. I borked my updates to `files/patch-config.mk.in` - thanks for setting me straight.
