### ISSUE TITLE
How can I update an empty geohash with an address?

### ISSUE THREAD

**Issue by yobyot** [owntracks/recorder#430]
I wonder if someone might be able to help me understand how to obtain a text address for a specific geohash in both the web server UI and, especially, when exporting via the API. 

I am exporting `.rec` files as shown below to a `.csv` file in a PowerShell script. 

`curl http://10.69.0.58:8083/api/0/locations?from=2023-11-04&user=myClientt&device=myDevice&fields=isotst,disptst,tid,addr,acc,lat,lon`

I am using a Google Maps API key in both `OTR_GEOKEY` and `OTR_BROWSERAPIKEY`. 

On output, a street address is not passed in `addr`. Oddly, the OwnTracks iOS app _does_ show the street address.

An `ocat --dump` shows the geohash associated with the position as `{}`. IOW, empty.

I wonder if I could delete it somehow and have Recorder "refresh" itself with the address from Google. Or, better, if I could edit the ghash directly.

Any suggestions are appreciated.

**Comment by jpmens** [comment]
The recorder performs optional reverse-geo lookups when the data arrives, but the data is not automatically associated with the actual location as it's stored in the `.rec` files. It is, however, emitted together with location data when searched for in the API as you have done above, for example:

```json
{
  "count": 193,
  "data": [
    {
      "isotst": "2023-11-01T00:38:04Z",
      "tid": "am",
      "addr": "Hotel Victoria, Calzada Niños Héroes de Chapultepec Km 545, Oaxaca de Juárez, 68070 Oaxaca, OAX, Mexico",
      "acc": 112,
      "lat": 17.072477,
      "lon": -96.729489
    },
```

If you aren't seeing the data it is likely that reverse-geo lookups aren't working. The best way to debug this is to perform a publish from the app and keep an eye on the Recorder console: it will show the address if it can obtain one. (If you're using docker we recently fixed logging -- `docker logs -f` should now do what it always ought to have done.)

The fact you say `ocat --dump` isn't showing addresses corroborates that there's something awry with lookups. It should be showing you something like this:

```console
$ ocat --dump
...
9g51ngg {"cc":"MX","addr":"Hotel Victoria, Calzada Niños Héroes de Chapultepec Km 545, Oaxaca de Juárez, 68070 Oaxaca, OAX, Mexico","tst":1698798996,"locality":"Oaxaca"}
```

The OwnTracks iOS app performs lookups itself, as does the Android app, but this data is  used for display in the app only, i.e. it is not transferred to the backend.

**Comment by yobyot** [comment]
Thanks, @jpmens.

Assume that there _was_ a problem with reverse-geo lookups that was fixed. But while the issue was in effect, Recorder created an empty ghash for a location. Let's further assume that's it a common location for a device that Recorder has subscribed to. IOW, one would expect that device to often be in that location.

My question is, short of removing `/var/spool/owntracks/recorder/store/ghash/data.mdb` and `/var/spool/owntracks/recorder/store/ghash/lock.mdb`, is there a way to delete a specific ghash in the database so that, once fixed, Recorder will re-calcluate the ghash and associated an address with it?

IOW, I want to edit that database to remove a failed entry (or manually update that entry) _without_ having to delete all the other ghashes by starting over. I don't see a way to edit or remove just one entry in the location database maintained by Recorder without starting from scratch.

**Comment by jpmens** [comment]
>is there a way to delete a specific ghash in the database so that, once fixed, Recorder will re-calcluate the ghash and associated an address with it?

You can remove a specific geohash from the LMDB database by loading that specific hash with a DELETE value. This is explained at https://github.com/owntracks/recorder#the-lmdb-database

The next time this particular geohash is calculated, the Recorder will re-query the reverse-geo provider to try to populate it.

**Comment by yobyot** [comment]
> You can remove a specific geohash from the LMDB database by loading that specific hash with a DELETE value. This is explained at https://github.com/owntracks/recorder#the-lmdb-database

Perfect. I missed that. Thanks.
