### ISSUE TITLE
Is it possible to have custom map?

### ISSUE THREAD

**Issue by etoimene** [owntracks/recorder#433]
From what I saw, I'd say recorder is using Google maps.
Is it possible to put some of our own ... tiled images, OpenStreetMap, anything?

Any pointer appreciated!

Thanks!

**Comment by jpmens** [comment]
Actually by default we meanwhile use OpenStreetmap in the Recorder and also in our [Frontend](https://github.com/owntracks/frontend). 

In order to use Google maps, as per our documentation:

> In order to use Google Maps, you have to obtain a [Google API "Browser key"](https://developers.google.com/maps/documentation/javascript/get-api-key). You then pass this key to your Recorder by configuring it in the defaults configuration file

**Comment by etoimene** [comment]
Brilliant!
Is it possible to upload custom bitmap maps?

**Comment by jpmens** [comment]
Frontend is much more capable than Recorder's very basic Web interface, though it also needs Recorder for actual backend data (i.e. your app writes to Recorder which delivers API for Frontend).

We have no support for custom bitmaps in Recorder.

**Comment by etoimene** [comment]
Ok. Thanks! I have to check the Frontend first.
You can close the ticket.

**Comment by jpmens** [comment]
(you can also close issues you opened :-) )

Closing as answered.
