### ISSUE TITLE
Osmand trip recording, online tracking option support

### ISSUE THREAD

**Issue by Terramoto** [owntracks/recorder#436]
Hello,

Osmand app on android has a plugin to record trips which contains a online tracking option and provides a HTTP request sort of ping function, i was wondering if it's possible to use this with owntracks recorder to record position?
![Imagem WhatsApp 2023-12-31 às 16 51 12_f19fd016](https://github.com/owntracks/recorder/assets/5443354/12565a57-fbaf-4c6e-8c51-4171586b489c)

**Comment by jpmens** [comment]
That’s not currently possible as our Recorder expects a different data format. 

If you enjoy tinkering it should be quite possible to program a service in, say PHP or Python, etc. , which takes osmand data, converts it to the JSON Recorder expects, and POSTs it on.

**Comment by jpmens** [comment]
Closing as answered.
