### ISSUE TITLE
Cannot view 12h points or 12h track

### ISSUE THREAD

**Issue by comminutus** [owntracks/recorder#438]
Hello, when I load the OwnTracks Recorder UI and click on a user's 12h points or 12h tracks, the UI shows a map of the world and this appears in the javascript console within the browser:
```
Map.js:302 Uncaught (in promise) Error: Bounds are not valid.
    at i.fitBounds (Map.js:302:44)
    at initialize (map_leaflet.js:66:7)
```

I am using v0.9.5 .

**Comment by jpmens** [comment]
Is this for a user who has no data? Can you verify the content of the specific .rec file for this user whether there would have been data for the 12h points/tracks?

**Comment by ckrey** [comment]
@comminutus If there is no data (in the last 12 hours), this is what recorder shows (empty world map and the JS error).
Without consulting the .rec file, you can check for the latest data in the "Table of current locations"

<img width="743" alt="Bildschirmfoto 2024-01-17 um 09 54 07" src="https://github.com/owntracks/recorder/assets/4027289/1b28eb1c-267e-41b2-bc0c-071fffb9f109">

**Comment by ckrey** [comment]
Will display a tooltip rather than throwing an error in the future:

<img width="275" alt="Bildschirmfoto 2024-01-17 um 11 33 49" src="https://github.com/owntracks/recorder/assets/4027289/16d0d0b8-817f-42db-8530-c41e5377e397">

**Comment by comminutus** [comment]
@ckrey there is definitely data in the 12h period. The data was available within a few hours of me looking.  The data also appeared fine on the other windows, just not the 12H one.

**Comment by ckrey** [comment]
If so,  consult the .rec file, and check for the latest data in the "Table of current locations".
In addition show us the URL. it should contain a “from” and a “to” element

**Comment by comminutus** [comment]
Thanks @ckrey, everything seems to be working as expected now.  I'm not sure if it was truly a bug or I need better glasses to look at the date/times on my screen 😵😜
