### ISSUE TITLE
Add alt field to GeoJSON points parameters

### ISSUE THREAD

**Issue by franchyze923** [owntracks/recorder#456]
Similar to - https://github.com/owntracks/recorder/issues/282 brought up by @aaliddell 

I would find it useful for the GeoJSON response to return altitude values found in the regular JSON response. I'd like to visualize the points based on elevation like this - https://youtu.be/wpv09kPNrms?si=3xyLmQfooy-rH9YZ&t=210

Also agree with the idea brought up in 282 about making the parameters returned be configurable.

**Comment by franchyze923** [comment]
Pull Request: https://github.com/owntracks/recorder/pull/457

**Comment by jpmens** [comment]
Good idea and thank you for the patch, which I've merged.

I'm not opposed to the idea of making the parameters returned be configurable, so if you're up to it ... :-)

Closing this now.

**Comment by franchyze923** [comment]
Thanks! I'm willing to take a look but I'm not familiar with C so I'm sure it'll be slow going
