### ISSUE TITLE
"Allow KML, GPX export - This we do enable in the back-end." what does this mean?

### ISSUE THREAD

**Issue by timdonovanuk** [owntracks/recorder#466]
Trying to understand how to export to GPX, but cannot find any documentation or mention of this other than this line in the FAQ. Thanks.

**Comment by jpmens** [comment]
This has to be done on the command line. For instance:

```console
$ ocat -u username -d devicername --from 2023-12-18 --to 2024-01-07 --format gpx > out.gpx
```

I can then upload the `out.gpx` file to https://www.gpsvisualizer.com/ to produce a map

![rabbit-11013](https://github.com/owntracks/recorder/assets/60706/f7a1f87f-74a9-4190-90d3-8f92fe35e88d)

**Comment by jpmens** [comment]
Closing as answered.
