### ISSUE TITLE
import google location history

### ISSUE THREAD

**Issue by dmd** [owntracks/recorder#467]
Now that [Google is sunsetting Location History](https://www.androidauthority.com/google-maps-killing-timeline-web-access-3449017/), there will likely be increased interest in Owntracks.

It would be extremely helpful to be able to import one's Google location history into Owntracks, to then keep adding to.

**Comment by jpmens** [comment]
(issue transferred to `Recorder` as it concerns storage of data)

**Comment by jpmens** [comment]
Would you be able and willing to work on this?

The "import" would have to create `*.rec` files with location data in our OwnTracks on-disk JSON format.

**Comment by dmd** [comment]
I can try, though this morning is my first time ever trying Owntracks. The format seems to be:

`YYYY-MM-DDTHH:mm:SSZ\t*                 \t{json payload}\n`

Which is defined by 

```c
#define RECFORMAT "%s\t%-18s\t%s\n"
```

1. I'm not sure what the * and blank are, which is to say I don't know what `reltopic` is. Can that be blank (`*` followed by 17 spaces) for import purposes?
2. What are the *required* fields of the payload? (I obviously won't have things like `SSID`.)
3.

**Comment by dmd** [comment]
I think maybe, at least for my use case, doing this isn't all that useful - I can use owntracks as a recorder, and since I end up doing any visualization elsewhere (e.g. in kepler.gl) I can just concatenate old and new at that stage.

**Comment by jpmens** [comment]
The `*` is a literal for location types, and the 18 spaces can contain subtypes, but not for locations. So, looking at a valid location record:

```
2023-12-31T23:57:54Z    *                       {"_type":"location","alt":3,"lat":21.434296,"lon":-87.33692499999999,"tid":"jp","tst":1704067074}
```

The following are required:
- `_type: location`
- `lat`
- `lon`
- `tst` (Unix epoch time in seconds)
- `tid` a two-character tracker-ID associated with the user (e.g. for me it's `jp`)

there are other, optional, values, such as:
- `alt` altitude in meters

**Comment by dmd** [comment]
Ok, that's pretty easy. I'll make a converter.

**Comment by dmd** [comment]
Presumably the tst value should exactly match the datetime at the start of the line? What happens if it doesn't? What is the difference in meaning between the two? Is one the time of the record being received vs time of the actual fix?

**Comment by dmd** [comment]
Also, does the YYYY-MM in the filename actually matter? I.e., do I *have* to split it out into correct years and months filenames, or could the whole thing be in a single `google-import.rec`?

**Comment by jpmens** [comment]
Digging deeply into memory here, my memory that is. The times need not match. The datetime string is the time at which the record was written into the `.rec` file whereas `tst` is the time at which the position was determined on the device (time of fix, normally). Typically `tst` will be earlier than datetime.

**Comment by jpmens** [comment]
IIRC, the Recorder uses the filenames, so yes, YYYY-MM matters.

**Comment by ckrey** [comment]
@dmd you may also want to take a look at the Google import script contributed here https://github.com/owntracks/recorder/tree/master/contrib/google-import

It takes a different approach by feeding the Google extract via MQTT to recorder, so recorder can handle the .rec files itself.

Or take a look at the GPX to .rec file conversion https://github.com/owntracks/recorder/tree/master/contrib/gpx-to-rec

**Comment by dmd** [comment]
Heh, I'd already finished -- although owntracks seems to be completely ignoring the new .rec files; is there something I need to do to make it aware of them?

```python
import json
import os
from datetime import datetime
import time

# Open the JSON file and read its contents
print('Loading data...')
with open('Records.json') as json_file:
    data = json.load(json_file)

# Loop through each location in the JSON data and write it to the appropriate file
print('Processing data...')
for location in data['locations']:
    try:
        dt = datetime.strptime(location['timestamp'], '%Y-%m-%dT%H:%M:%S.%fZ')
        timestamp = int(time.mktime(dt.timetuple()))
        date_str = dt.strftime('%Y-%m-%dT%H:%M:%SZ')
        file_name = dt.strftime('%Y-%m.rec')

        latitude = location['latitudeE7'] / 10**7
        longitude = location['longitudeE7'] / 10**7
    except KeyError:
        continue
    except ValueError:
        continue

    json_payload = {
        "lon": longitude,
        "lat": latitude,
        "tst": timestamp,
        "tid": "2E",
        "_type": "location"
    }
    line = f"{date_str}\t*{' ' * 17}\t{json.dumps(json_payload)}\n"

    with open(file_name, 'a') as file:
        file.write(line)
```

**Comment by jpmens** [comment]
>is there something I need to do to make it aware of them?

probably restart ot-recorder

**Comment by dmd** [comment]
I'm using docker - bringing the container down and up doesn't help.

**Comment by jpmens** [comment]
Then I've to assume the data isn't rightly formatted.

**Comment by jpmens** [comment]
.. or permissions on the files?

**Comment by dmd** [comment]
Here is an example (truncated) `rec` file I create; am I doing something wrong? (Renamed to .txt for github upload)

[2024-05.rec.txt](https://github.com/user-attachments/files/15593882/2024-05.rec.txt)

The permissions are the same as the 2024-06 file that owntracks created itself, and the `tid` is the same.

**Comment by jpmens** [comment]
there's no TAB in the lines

**Comment by jpmens** [comment]
```c
#define RECFORMAT "%s\t%-18s\t%s\n"
```

Note the `\t`

**Comment by dmd** [comment]
Sorry, that was an artifact of cut and paste. There is a tab in real life:

```
dmd@eco ~/owntracks/store/rec/dmd/24770961-1e6c-484a-827d-a183e67524ce🔒
$ tail -1 2024-05.rec | od -c
0000000   2   0   2   4   -   0   5   -   3   1   T   2   2   :   1   2
0000020   :   0   2   Z  \t   *
0000040                              \t   {   "   l   o   n   "   :
0000060   -   7   1   .   1   7   7   7   8   8   ,       "   l   a   t
0000100   "   :       4   2   .   4   1   7   7   4   5   ,       "   t
0000120   s   t   "   :       1   7   1   7   2   0   7   9   2   2   ,
0000140       "   t   i   d   "   :       "   C   E   "   ,       "   _
0000160   t   y   p   e   "   :       "   l   o   c   a   t   i   o   n
0000200   "   }  \n
0000203
```

**Comment by dmd** [comment]
Compare with:

```
$ tail -1 2024-06.rec | od -c
0000000   2   0   2   4   -   0   6   -   0   5   T   1   6   :   3   9
0000020   :   5   0   Z  \t   *
0000040                              \t   {   "   b   a   t   t   "   :
0000060   8   5   ,   "   l   o   n   "   :   -   7   1   .   1   7   7
0000100   7   7   5   9   9   9   9   9   9   9   9   ,   "   a   c   c
0000120   "   :   5   ,   "   b   s   "   :   1   ,   "   p   "   :   1
0000140   0   0   .   0   8   ,   "   v   e   l   "   :   1   ,   "   B
0000160   S   S   I   D   "   :   "   d   8   :   4   7   :   3   2   :
0000200   d   a   :   e   d   :   8   6   "   ,   "   S   S   I   D   "
0000220   :   "   3   e   d   g   e   s   "   ,   "   v   a   c   "   :
0000240   3   ,   "   l   a   t   "   :   4   2   .   4   1   7   8   7
0000260   7   ,   "   t   o   p   i   c   "   :   "   o   w   n   t   r
0000300   a   c   k   s   /   d   m   d   /   2   4   7   7   0   9   6
0000320   1   -   1   E   6   C   -   4   8   4   A   -   8   2   7   D
0000340   -   A   1   8   3   E   6   7   5   2   4   C   E   "   ,   "
0000360   t   "   :   "   u   "   ,   "   c   o   n   n   "   :   "   w
0000400   "   ,   "   m   "   :   1   ,   "   t   s   t   "   :   1   7
0000420   1   7   6   0   5   5   9   0   ,   "   a   l   t   "   :   9
0000440   5   ,   "   _   t   y   p   e   "   :   "   l   o   c   a   t
0000460   i   o   n   "   ,   "   t   i   d   "   :   "   C   E   "   ,
0000500   "   _   h   t   t   p   "   :   t   r   u   e   }  \n
0000516
```

**Comment by jpmens** [comment]
In this record

```
2024-05-31T22:12:02Z    *                       {"lon": -71.177788, "lat": 42.417745, "tst": 1717207922, "tid": "CE", "_type": "location"}
```

the `tst` is 

```
1717207922 Sat Jun  1 04:12:02 2024
```

which is "past" May.

Can you see if that's the reason?

**Comment by dmd** [comment]
There are a few like that because of sloppiness with the time zone I guess, but in the real file for may there are thousands of actually-May lines. Would one or two at the end that are wrong cause it to reject the whole file?

```
$ wc -l 2024-05.rec
6587 2024-05.rec
```

**Comment by jpmens** [comment]
Unlikely.
  Sorry, you're on your own for a few hours now..

**Comment by jpmens** [comment]
Please send us a few lines from your `2024-05.rec` to support@owntracks.org if possible.

**Comment by rhyst** [comment]
@dmd your code appears to work for me with data going back to 2013

**Comment by jpmens** [comment]
Thanks for confirming that, @rhyst 

I've not received the data yet, but there's nothing (except the explained lack of TABs) in above txt file which is cause for concern.

**Comment by deplicator** [comment]
I also had luck with [the script shared above](https://github.com/owntracks/recorder/issues/467#issuecomment-2150494580). Haven't done anything extensive, but I was able to convert from google to a *.rec files. Data showed up after restarting the container!

**Comment by dmd** [comment]
Curious how big yours are. I still haven't been able to get it to work with mine oddly.

**Comment by jpmens** [comment]
I assume you've simply dropped the `.rec` file (which is fine) into `STORAGE/rec/dmd/phone/YYYY-MM.rec`. What is probably missing for the Recorder to display your data is an actual "last" position. (I had assumed you were "augmenting" data for an existing OwnTracks Recorder user):

```
$ mkdir -p STORAGE/last/dmd/phone    # your username / devicename
$ tail -1 2024-05.rec > STORAGE/last/dmd/phone/dmd-phone.json   # note the filename (again: username - device)
```

and if you refresh the page (without needing to restart the Recorder) you should see your data.

**Comment by dmd** [comment]
Aha, thanks. I think this can probably be closed; there are a few options here and this certainly doesn't need to be (and shouldn't be) incorporated into owntracks itself.

**Comment by dmd** [comment]
Yes, same - I have ~3 million rows (starting in 2010).

**Comment by jpmens** [comment]
What is it in "it would never load" ? Which part? Which map? or do you mean the API?

**Comment by dmd** [comment]
Yes, no points ever show on the map.

**Comment by jpmens** [comment]
What does a corresponding API query do?

**Comment by dmd** [comment]
No idea and no time to learn about it right now, sorry.

**Comment by deplicator** [comment]
I was just enter `to` and `from` in the map url. Haven't had a chance to dig deeper.

A month long range, like `from=2015-03-01&to=2015-03-31` the points show on the map in about 6 seconds (watching the network tab in the developer console). This loads just shy of 10k points. 

A year long range, `from=2015-04-01&to=2016-04-01`  loads in about 1.4 minutes. I didn't get a count of points but it's roughly 12 times the month long one. Navigating the map is possible, but sluggish.

A two year range took 4 minutes and the tab uses 4.7 GB of memory. Crashes if I try to move the map around.

I haven't tried the frontend yet.

**Comment by jpmens** [comment]
@deplicator I expect the map will be more responsive when choosing the line mode. Be that as it may the actual reaction on the map itself is not really something we can do anything about.

The API response times sound a bit high; can you please say what platform, OS, etc. ?

**Comment by deplicator** [comment]
You're right about line mode! After it loads it's quite snappy.

> The API response times sound a bit high; can you please say what platform, OS, etc. ?

I'm running in in a container on Unraid.

**Comment by jpmens** [comment]
```console
$ time curl -sSf 'http://192.168.1.30:8083/api/0/locations?user=jpm&device=5s&from=2019-06-15&to=2024-06-15' > /tmp/full.json

real	0m9.252s
user	0m0.219s
sys	0m0.483s

$ du -sh /tmp/full.json
 48M	/tmp/full.json

$ jq .count  /tmp/full.json
104235
```

104,000 points load from an old Shuttle PC here (FreeBSD 12.1 with Recorder running in a jail), over the network, in under 9.5 seconds. 

I'm only measuring the API access which is used by our maps (also Frontend). Obviously populating maps etc. will take longer, possibly much longer, for example with the GeoJSON points, as @deplicator has already determined.

**Comment by PilaScat** [comment]
What method do you recommend to do this now? The above script or via MQTT?
I have almost 15 years of recordings
