### ISSUE TITLE
unix socket support 

### ISSUE THREAD

**Issue by cyberb** [owntracks/recorder#468]
I am trying to add owntracks into a self hosting platform (https://github.com/syncloud/platform) where on a single device you have multiple apps installed behind a reverse proxy.

Is it possible to listen on a unix socket instead of tcp for http mode?

That way we could prevent port conflicts between installed apps.

**Comment by jpmens** [comment]
No, this is neither possible nor planned.

**Comment by jpmens** [comment]
BTW, the HTTP listen port is configurable in Recorder.

**Comment by cyberb** [comment]
Could you give a bit more technical details why it is not possible?
In HTTP only mode with reverse proxy in front of it.

**Comment by jpmens** [comment]
Sorry my answer was confusing. What I meant is that the Recorder currently has no support for HTTP over Unix domain sockets, and that we have no plans to actually implement that.

**Comment by jpmens** [comment]
Closed via #470
