### ISSUE TITLE
Handle _type: status messages

### ISSUE THREAD

**Issue by jpmens** [owntracks/recorder#482]
We need to process `_type: status` messages and do something "clever" with them.
Whatever "clever" is.

#481

**Comment by jpmens** [comment]
Status messages are currently written into the `.rec` file. I don't see a reason to handle them differently at this point.

**Comment by ckrey** [comment]
We may store the last `status` similar to `config` or `waypoints`. But other than `config` or `waypoints` we will never send the status information back to the device.

**Comment by jpmens** [comment]
For the record the `status` data looks like this:

```json
{
  "_type": "status",
  "iOS": {
    "altimeterAuthorizationStatus": "CMAuthorizationStatusAuthorized",
    "altimeterIsRelativeAltitudeAvailable": true,
    "backgroundRefreshStatus": "UIBackgroundRefreshStatusAvailable",
    "deviceIdentifierForVendor": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "deviceModel": "iPhone",
    "deviceSystemName": "iOS",
    "deviceSystemVersion": "17.5.1",
    "deviceUserInterfaceIdiom": "UIUserInterfaceIdiomPhone",
    "locale": "en_DE",
    "localeUsesMetricSystem": true,
    "locationManagerAuthorizationStatus": "kCLAuthorizationStatusAuthorizedAlways",
    "version": "17.3.1"
  }
}
```

I know the desire originated for [the Android app](https://github.com/owntracks/android/issues/1618), but I don't think this is terribly important for most users.

We'll leave it in the `.rec` file until we come up with a good reason to do otherwise.
