### ISSUE TITLE
How to achieve accuracy of Google Maps Timeline without killing the battery (iOS)?

### ISSUE THREAD

**Issue by sidamos** [owntracks/recorder#485]
I was testing Google Maps Timeline (Location History) against Owntracks (with "significant location change" setting) on my iPhone during a walk.

Google Maps accuracy was way better (many more points). It did consume more battery than Owntracks, but not by much.

If I would enable "movement" on Owntracks, where it tracks location all  the time (the location indicator is visible all the time in the iPhone title bar), then it would probably be as good or better as Maps, but this drains too much battery to let it be enabled all day.

I guess, somehow Maps is detecting that I am walking/moving and enables higher accuracy location tracking temporarily, because the location indicator for Maps is not always visible in the title bar.

Any chance, the Owntracks app could really compete with Maps regarding accuracy vs battery consumption?

**Comment by ckrey** [comment]
We are not competing with Google and we are not selling your data. We use no central components and no silent push notifications.

If you can contribute to the owntracks apps, we are happy to accept Pull Requests.

**Comment by jpmens** [comment]
There's also this thing with the billions of dollars invested into the software... We do take contributions.

**Comment by sidamos** [comment]
I see nothing wrong in trying to compete with Google. Given that Google Maps Timeline soon goes away on the web, this would be the chance for Owntracks to grow users because Google Maps Timeline has a lot of fans.
And making suggestion/asking questions does not automatically mean that one needs to be able to contribute code or money. I am contributing time.

**Comment by ckrey** [comment]
You may try this hint: https://owntracks.org/booklet/features/ios/#region-monitoring-with-follow
