### ISSUE TITLE
MQTT, and HTTP, simultaneously?

### ISSUE THREAD

**Issue by dhitchenor** [owntracks/recorder#487]
I'm testing more of the OwnTracks framework/ecosystem, and have decided to put some energy into recorder (I couldn't find the discussion board on [owntracks/recorder](https://github.com/owntracks/recorder), and have a quick question about it.

Is it possible/ relevant to have both MQTT and HTTP/websockets running simultaneously?

**Comment by jpmens** [comment]
> I'm having trouble getting recorder to work with MQTT

What exactly do you suggest we do with this type of report. Shall we **guess** as to what trouble you're having?

**Comment by dhitchenor** [comment]
HI @jpmens,

I appreciate your quick, albeit confusing reply; there was certainly no 'report' made, so I've edited the OP to get to the point, faster.

I will reiterate my intent, in this post too; I would like to know if a broker can function properly, with MQTT and Websockets simutaneously? a.k.a, can one broker receive/push MQTT data, and websockets data, at the same time.

**Comment by jpmens** [comment]
A suitably configured broker can do so.

**Comment by airdogvan** [comment]
I'm also interested in this topic.  Already configured Owntracks to log points to Darawich via http but would also like to display my partner's location in Owntracks for which I seem to need mqtt connection.  I can host mqqt broker but app won't allow me simultaneous connections to both.  Suggestions welcomed.  Thanks.

**Comment by jpmens** [comment]
You are responding to a closed issue. Open a new issue if you need help.
