### ISSUE TITLE
Gatewaying MQTT to HTTP

### ISSUE THREAD

**Issue by dl5dla** [owntracks/recorder#493]
I currently receive position data from the owntracks app via MQTT. As I have another server which is expecting http data from the owntracks app, I am looking for a lua script, which picks up the received mqtt data and forwards it as http data to the other server. 

Is such a script available or do you have some hints for a lua newbie how to start?

Thanks,
 Peter

**Comment by jpmens** [comment]
There are two routes you could take:
1. use a Lua hook in the Recorder to forward data to HTTP
2. use an MQTT->HTTP republisher which listens directly to your broker and decodes / modifies / POSTS data to your HTTP endpoint

I would chose the 2nd option as that doesn't limit you to using Lua if you are, say, more comfortable with Python or a different scripting language.

I'm not aware of any specific program which will do this for you, but browsing through the `contrib/` directory might give you some inspiration.

**Comment by dl5dla** [comment]
Thanks for your advice. I will think about both options. Meanwhile I have managed to access the individual fields of the position message using a LUA script. Only the http post request seems to be difficlt to implement - there are probably still some lua modules missing.

**Comment by dl5dla** [comment]
Finally, I found a solution (similar to option 2 above).  I have setup a mqtt client wich connects to the mqtt broker and processes the incoming data directly without using a http hook.

**Comment by jpmens** [comment]
I'm glad you got that sorted.

If you wish to become rich and famous, well famous, well maybe, you might want to contribute your work into  our `contrib/` directory with a pull request. 😀
