### ISSUE TITLE
`GLIBC_2.34' not found

### ISSUE THREAD

**Issue by Egregius** [owntracks/recorder#496]
When I try to install the recorder on Debian Bookworm with apt install ot-recorder I get this errormessage:
`/usr/sbin/ot-recorder: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/sbin/ot-recorder)
/usr/sbin/ot-recorder: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/sbin/ot-recorder)`

Any ideas how to fix this?

**Comment by jpmens** [comment]
This is Bookworm on which platform? arm? x86_64? Which hardware, please?
