### ISSUE TITLE
Recorder map blank

### ISSUE THREAD

**Issue by zkmay11** [owntracks/recorder#498]
I'm learning and new to Owntracks after bailing on a previous location service, so forgive me if this doesn't make sense or I'm missing something obvious.  When I open the Live Map it is blank with none of our devices, only a global view.  The Frontend page seems to be working just fine, and the apps seem to be working.  Unfortunately, I'm not sure where to begin troubleshooting the issue, if there is indeed an issue here with my setup.
![Screenshot 2024-09-18 120418](https://github.com/user-attachments/assets/708aef0d-c973-4eff-b083-b8cbcbc539ab)

**Comment by Jachimo** [comment]
At least on my system, there should be a blue banner above the map, and on the left side of that banner (above the +/- zoom controls), there is a menu button with three horizontal lines (aka the "hamburger" icon).  Clicking on that button switches the view to a list of settings that selects what is shown on the map—date range, user, device, etc.

It is not clear from your screenshot if the banner with the menu icon isn't being shown, or if you cropped it out.

**Comment by zkmay11** [comment]
No cropping, anything else was just browser bar and web address.  No errors in console, and OT service running with no issues

**Comment by jpmens** [comment]
(The blue banner Jachimo refers to is in Frontend)

I'm glad Frontend and everything else is working for you, @zkmay11 . Things you can do:
- please verify the `.rec` files are actually getting data when your devices  publish their location. (This appears to be occurring because you say Frontend works for you)
- double-check that the time range you're using on the map is within the bounds of data available from your device's `.rec` file
- double check that username and device used in the URL really exist (as `.rec` file)

Does the table with live data get populated?

**Comment by zkmay11** [comment]
So it does look like the .rec files are getting data from devices when locations are published.  The device table is also populated with correct data, and Frontend is showing movement updates.  I've got some occasional "location out-of-order, skipping 'last' update" notices in the recorder journal, but it seems like the live map just isn't displaying the last published locations.

![Screenshot 2024-09-19 204408](https://github.com/user-attachments/assets/cc0012b8-9500-4b88-b94e-77d65b230dcc)

![Screenshot 2024-09-19 204425](https://github.com/user-attachments/assets/7941cb88-d1d6-4b1f-9730-33e649ecbdbc)
(browser bar just cropped out of screenshots)

**Comment by jpmens** [comment]
Are you accessing these pages via a HTTP proxy? Can you test with a local URL (http://localhost:8083/....

**Comment by zkmay11** [comment]
Okay; think this narrows it down to the Apache reverse proxy.  It's a headless server (no GUI installed) sitting behind an Apache reverse proxy.  Registrar is CloudFlare, but proxying is turned off for this domain.  Accessing the server locally with the IP (HTTP) lands me on the default Nginx page, accessing with IP (HTTPS) prompts login, and the live map works as it should, Frontend is blank though.  When accessed through the configured domain, i.e. going through the reverse proxy, Frontend displays just fine, but the live map doesn't, so I'm going to guess its something in the Apache directives.  They're currently: 
<pre>
<VirtualHost *:80>
	ServerName xxx.xxx
    ProxyPreserveHost On
	ProxyRequests Off
	ProxyPass / http://10.0.6.11:80/
	ProxyPassReverse / http://10.0.6.11:80/    
    ProxyPass	/owntracks/ws	ws://10.0.6.11:8083/ws keepalive=on retry=60
    ProxyPassReverse	/owntracks/ws	ws://10.0.6.11:8083/ws keepalive=on    
    ProxyPass /owntracks	http://10.0.6.11:8083/
    ProxyPassReverse /owntracks		http://10.0.6.11:8083/
	ErrorLog ${APACHE_LOG_DIR}/owntracks_error.log
	CustomLog ${APACHE_LOG_DIR}/owntracks_access.log combined
RewriteEngine on
RewriteCond %{SERVER_NAME} =owntracks.xxx.xxx [OR]
RewriteCond %{SERVER_NAME} =www.owntracks.xxx.xxx
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
<IfModule mod_ssl.c>
<VirtualHost *:443>
	ServerName owntracks.xxx.xxx
    SSLEngine on
	SSLProxyEngine on
    SSLProxyCheckPeerCN Off
	ProxyPreserveHost On
	ProxyRequests Off
	ProxyPass / https://10.0.6.11:443/
	ProxyPassReverse / https://10.0.6.11:443/    
    ProxyPass        /owntracks/ws        ws://10.0.6.11:8083/ws keepalive=on retry=60
    ProxyPassReverse /owntracks/ws        ws://10.0.6.11:8083/ws keepalive=on
# Static files
	ProxyPass /owntracks                  http://10.0.6.11:8083/
	ProxyPassReverse /owntracks           http://10.0.6.11:8083/	
	ErrorLog ${APACHE_LOG_DIR}/owntracks_error.log
	CustomLog ${APACHE_LOG_DIR}/owntracks_access.log combined
Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateFile /etc/letsencrypt/live/xxx/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/xxx/privkey.pem
</VirtualHost>
</IfModule>
</pre>

**Comment by jpmens** [comment]
I see a ProxyPass (and reverse) for / to http: and to https:

Note that our backend doesn't do https so that might be an issue in your configuration

**Comment by zkmay11** [comment]
That makes sense then and explains what is going on; some tweaks for local access should resolve that, thanks!

**Comment by jcm4atx** [comment]
@zkmay11 would you mind posting your configuration? I have the same exact problem. The map works fine when I connect to my local IP address, but when I go through my Apache reverse proxy I get a blank map. Everything appears to work but this.

**Comment by zkmay11** [comment]
@jcm4atx same as above.  

HTTP:
<pre>
	ServerName owntracks.domain
        ProxyPreserveHost On
	ProxyRequests Off
	ProxyPass / http://backendip:80/
	ProxyPassReverse / http://backendip:80/    
        ProxyPass	/owntracks/ws	ws://backendip:8083/ws keepalive=on retry=60
        ProxyPassReverse	/owntracks/ws	ws://backendip:8083/ws keepalive=on     
        ProxyPass /owntracks	http://backendip:8083/
        ProxyPassReverse /owntracks		http://backendip:8083/
	ErrorLog ${APACHE_LOG_DIR}/owntracks_error.log
	CustomLog ${APACHE_LOG_DIR}/owntracks_access.log combined
        RewriteEngine on
        RewriteCond %{SERVER_NAME} =owntracks [OR]
        RewriteCond %{SERVER_NAME} =www.owntracks
        RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</pre>
HTTPS:

<pre>
	ServerName owntracks.domain
        SSLEngine on
	SSLProxyEngine on
        SSLProxyCheckPeerCN Off
	ProxyPreserveHost On
	ProxyRequests Off
	ProxyPass / https://backendip:443/
	ProxyPassReverse / https://backendip:443/    
        ProxyPass        /owntracks/ws        ws://backendip:8083/ws keepalive=on retry=60
	ProxyPassReverse /owntracks/ws        ws://backendip:8083/ws keepalive=on
	ProxyPass /owntracks                  http://backendip:8083/
	ProxyPassReverse /owntracks           http://backendip:8083/	
	ErrorLog ${APACHE_LOG_DIR}/owtracks_error.log
	CustomLog ${APACHE_LOG_DIR}/accesslog_access.log combined
        Include /etc/letsencrypt/options-ssl-apache.conf
        SSLCertificateFile /path/to/file
        SSLCertificateKeyFile /path/to/file
</pre>

I never really dug into changing the access at home, since if for some reason I really need to see the map at home Frontend works just fine.  Like 99.9% of the time my family uses the mobile app.  For me the fact that the app works and everything on the backend works just fine so I can run a few flows in Node-RED is enough.

The only other change I have made was to setup a cert renewal with Certbot rather than rely on the built-in renewal, since it didn't seem to want to work behind the reverse proxy.  I use Cloudflare for my registrar, so using Certbot with the Cloudflare plugin fixed that problem.
