### ISSUE TITLE
0.4.2 crashes on when accessing /last/

### ISSUE THREAD

**Issue by juzam** [owntracks/recorder#50]
Everything seems to be fine in 0.4.2 except when I try to access the live map. 

Here's the relevant log:
```
ot-recorder[22361]: starting
ot-recorder[22361]: connecting to MQTT on localhost:1883 as clientID ot-recorder-raspberrypi-22361 without TLS
ot-recorder[22361]: HTTP listener started on 0.0.0.0:8083
ot-recorder[22361]: Subscribing to owntracks/# (qos=2)
ot-recorder[22361]: http: GET /index.html
ot-recorder[22361]: http: GET /table/js/jquery-1.11.3.min.js
ot-recorder[22361]: http: GET /table/js/mustache.js
ot-recorder[22361]: http: GET /table/js/moment.min.js
ot-recorder[22361]: http: GET /api/0/last
ot-recorder[22361]: http: GET /favicon.ico
ot-recorder[22361]: http: GET /last/index.html
ot-recorder[22361]: http: GET /last/functions.js
ot-recorder[22361]: http: GET /last/websock.js
ot-recorder[22361]: http: GET /last/pista-micro.png
zsh: segmentation fault  /usr/local/sbin/ot-recorder --http-host 0.0.0.0 'owntracks/#'

```
Going back to release tag 0.4.1 fixes the problem.

I suspect there's something relevant in websock.js but I'm not able to track it down unfortunately.

**Comment by jpmens** [comment]
I cannot reproduce this. Which OS/version?

Can you please move the file in your _storage_ (`/last/user/device/user-device.json`) away safely, (with running recorder is fine), publish a new location and open the map? (Files in LAST contain the JSON sent to the map.)

Is the issue then reproducible?

**Comment by juzam** [comment]
This is happening on a Raspberry pi B, with raspbian wheezy (/etc/debian_version reports 7.6).

This is what I did, reset HEAD to the latest commit, copied config.mk.in to config.mk, make and make install.

While the recorder was running, I moved away the json (both in fact, the second one is the position of the International Space Station) open the /table/ first and then the live map. 

The map reported ws as connected (green square) prior to the new publish, after the publish via Android, it turned red immediately and the issue is reproduced: 

```
ot-recorder[11751]: http: GET /last/index.html
ot-recorder[11751]: http: GET /last/functions.js
ot-recorder[11751]: http: GET /last/websock.js
ot-recorder[12151]: starting
ot-recorder[12151]: connecting to MQTT on localhost:1883 as clientID ot-recorder-raspberrypi-12151 without TLS
ot-recorder[12151]: HTTP listener started on 0.0.0.0:8083
ot-recorder[12151]: Subscribing to owntracks/# (qos=2)
ot-recorder[12182]: starting
ot-recorder[12182]: connecting to MQTT on localhost:1883 as clientID ot-recorder-raspberrypi-12182 without TLS
ot-recorder[12182]: HTTP listener started on 0.0.0.0:8083
```

**Comment by jpmens** [comment]
I found a bug (unfixed) yesterday which may be the cause. Please check if your broker has a retained message for the owntracks topics which does NOT contain valid JSON.

**Comment by juzam** [comment]
There is a retained message for the android device, but it contains valid JSON so it shouldn't be it.

**Comment by jpmens** [comment]
Do me a favor please (I'm away from keyboard for a few days and this is keeping me awake). Would you launch Recorder with `--label Blabla`? I think this is the only change between 0.4.1 and .2 which affects the Websockets interface, and maybe I have a NULL there somewhere. That label ought to be shown on Map on top left with a green border indicating connected, and red border being disconnected.

Oh, and IIRC, you did say the Table view works fine.

**Comment by juzam** [comment]
That's it! as long as I specify a label everything is ok. (map and table were already fine)

Sorry for not spotting that early. Visually there was only a white square with green/red border.

**Comment by jpmens** [comment]
Thanks, that's a relief! I must have mucked up a bit somewhere, as the default `--label` ought to be "Recorder". Your hint a few messages back about a small square rang a bell. I will fix this as soon as I return.

**Comment by juzam** [comment]
Glad you found the issue :) there is also a minor inconsistency in the favicon displayed. When accessing /last/  it loads pista-micro.png which is the square icon. everywhere else (/index.html or /map/) I'm seeing the round favicon.ico

**Comment by jpmens** [comment]
I cannot reproduce this crash locally. I am comitting a fix in a moment which caters for a _possible_ NULL `label`, but I'm not convinced that's the reason. Can you test that for me?

@ckrey has made a new logo for `recorder` which will also be included in favicon, etc.

**Comment by juzam** [comment]
with the fix, and owntracks-recorder launched without any label, the live
map now it's ok.
I still have the white square with green border without any label inside,
but the live map doesn't crash anymore.

On Sun, Oct 11, 2015 at 1:24 PM, JP Mens <notifications@github.com> wrote:

> I cannot reproduce this crash locally. I am comitting a fix in a moment
> which caters for a *possible* NULL label, but I'm not convinced that's
> the reason. Can you test that for me?
>
> @ckrey <https://github.com/ckrey> has made a new logo for recorder which
> will also be included in favicon, etc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owntracks/recorder/issues/50#issuecomment-147184341>.
>



-- 
Giovanni Angoli

**Comment by jpmens** [comment]
Understood & **finally** fixed. I hope. Thanks for your patience. I believe you had compiled without Lua. This is now fixed. (Initialization of label was within an incorrect `#ifdef`.)

**Comment by juzam** [comment]
JP thank you for *your* patience! Yep, compiled without lua (did a simple
cp config.mk.in config.mk without any further editing)

On Sun, Oct 11, 2015 at 5:09 PM, JP Mens <notifications@github.com> wrote:

> Understood & *finally* fixed. I hope. Thanks for your patience. I believe
> you had compiled without Lua. This is now fixed. (Initialization of label
> was within an incorrect #ifdef.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owntracks/recorder/issues/50#issuecomment-147208471>.
>



-- 
Giovanni Angoli
