### ISSUE TITLE
OTR_CLEAN_AGE default not correctly handled

### ISSUE THREAD

**Issue by ckrey** [owntracks/recorder#500]
Feature introduced with #447 in version 0.9.8

If OTR_CLEAN_AGE is not specified (default = 0) or explicitly set to zero, the cache entries are always considered out of date, which leads to unintended reverse geo queries.

The cache is effectively invalidated 😭

**Comment by ckrey** [comment]
As a workaround, add the following line to the configuration file (/etc/default/ot-recorder):

> OTR_CLEAN_AGE=315360000

and restart to-recorder

**Comment by jpmens** [comment]
Closing as fixed in https://github.com/owntracks/recorder/commit/76b00e4b789bdbc6d6a259812427354a7972f53b
