### ISSUE TITLE
How to delete old location data ?

### ISSUE THREAD

**Issue by damionx7** [owntracks/recorder#501]
Thank you for this application.

I have one query. Is there any option on deleting old location data eg. an option to keep only the latest location data (30 d) in owntracks recorder. If not, how can I implement it.

**Comment by jpmens** [comment]
There is rudimentary and possibly dangerous support for [removing data via the API](https://github.com/owntracks/recorder/blob/master/API.md#kill), but beware this has probably had very little testing.

Other than that, you can safely at any time remove the `*.rec` files under `<STORAGE>/rec/<user>/<device>/`. These are named `YYYYMM.rec` and can easily be identified.
