### ISSUE TITLE
simultaneous http and mqtt connections

### ISSUE THREAD

**Issue by airdogvan** [owntracks/recorder#502]
Same as[ 487](https://github.com/owntracks/recorder/issues/487).
I'm also interested in this topic. Already configured Owntracks to log points to Darawich via http but would also like to display my partner's location in Owntracks for which I seem to need mqtt connection. I can host mqqt broker but app won't allow me simultaneous connections to both. Suggestions welcomed. Thanks

**Comment by jpmens** [comment]
Suggest you use MQTT which our apps prefer anyway and create a subscriber which POSTs the data you need via HTTP to the endpoint you need..

**Comment by airdogvan** [comment]
Thank for answering.
Sorry, not too familiar with MQTT.  I read a bit on the net, suppose Mosquito seems to be the easiest.  By "create a subscriber who posts the data" you mean I should write a small python script that would receive from Mosquito and send to Dawarich?
Or does something with that functionality already exist?
Thanks again.

Oct 13, 2024 11:03:33 Jan-Piet Mens 'notifications at github.com' ***@***.***>:

**Comment by jpmens** [comment]
>Or does something with that functionality already exist?

Not to my knowledge, but if you feel like tinkering it shouldn't be too difficult, and you might find bits and pieces (e.g. for Python) in our contrib/ directory.

**Comment by jpmens** [comment]
Closing as answered.
