### ISSUE TITLE
How to remove persistent data in Recorder?

### ISSUE THREAD

**Issue by voryzen** [owntracks/recorder#503]
Recorder (and Frontend) are showing older devices, that I've since removed with MQTTExplorer.
Newer devices, and devices that are actually in use, update as expected.

I've gone as far as deleting the mosquitto.db file, but the older devices still show up on recorder (they don't show up on any of the connected apps); is there a way to remove these older devices?

recorder 0.9.8 (docker)
frontend 2.x.x (docker)
mosquitto 2.0.19 (docker)

**Comment by jpmens** [comment]
Our Recorder, and thus also Frontend, obtain data not from the mosquitto.db file which contains the last retained messages only, but from the storage directory (typically `/var/spool/owntracks/recorder/`). 

Therein are a number of files in `last/` and in `rec/` which contain the persistent data for user/devices. `rec/` specifically holds this in `rec/<user>/<device>/YYYYMM.rec`; if you remove the files you no longer require, you won't be getting the data you're now seeing.

It is not necessary to stop the Recorder for doing this.

**Comment by voryzen** [comment]
Thanks for the quick reply.
I've deleted the respective directories, however I've yet to check recorder; I'll reply if there are any issues.

If it helps, I found the `rec/` and `last/` directories in the `/store` directory.

**Comment by voryzen** [comment]
Thanks for the quick reply.
I've deleted the respective directories, however I've yet to check recorder; I'll reply if there are any issues.

If it helps, I found the `rec/` and `last/` directories in the `/store` directory.
