### ISSUE TITLE
Why did you choose GPL??

### ISSUE THREAD

**Issue by hopeseekr** [owntracks/recorder#506]
I would like to build a service that allows anyone to migrate from Google Timeline, but the GNU General Public License hinders this. There's no way I would do all that work justt to be compelled to open source 100% of it.

GPL is in marked decline because it is mostly used by corporations to hinder competition, which is what is being done here.

So why license this project under it?

**Comment by joejordan** [comment]
What are your goals in building this migration tool, and why does the GPL license make achieving those goals difficult? I ask because I would love a tool like this and would very much like to see it come to fruition.

**Comment by jpmens** [comment]
Closing as dead.
