### ISSUE TITLE
Is it possible to remote config client in HTTP mode?

### ISSUE THREAD

**Issue by terrytw** [owntracks/recorder#516]
In the documentation here https://owntracks.org/booklet/tech/http/

It is mentioned that you can return a json payload to the client when client POST update. `cmd` is implemented, but only applies to dump, reportLocation, reportSteps, action, and setWaypoints. Is setConfiguration not supported here?

Moreover, can someone please tell me how to include the json payload in the response of HTTP mode? I am using docker for recorder. 

Thank you!

**Comment by jpmens** [comment]
Most if not all of our examples concern MQTT, that is correct. It has always been the better option as clients can subscribe or publish to OwnTracks topics on the broker to asynchronously do "things" with the data.

It might be possible to implement what you're asking for with Lua scripts in HTTP mode, but I  will not invest time thinking about it -- in my opinion it is the worst route.

The issue at hand is how to give the Recorder data which it should return to  your client; I'm don't think we actually have the possibility of doing that in HTTP mode. (In MQTT mode it wouldn't be the Recorder which does this, but the actual broker.)

**Comment by jpmens** [comment]
However, Remote config is of course possible by placing an `.otrc` file on a suitable HTTP endpoint and asking the user of the client to click on that and open the target in OwnTracks app. That might be a solution for your use-case.

**Comment by terrytw** [comment]
Thanks for the suggestions. However my use-case is that I want to remotely config a client without manual input, just like the linked issue where the author wants to modify configs based on the data received. Like change the interval if the device is moving fast. (In my experience only move mode produces good reliable data, so the only thing I can do is to change the move mode interval, I can't get timely and accurate updates at all in the 3 other modes)

I looked into automation and it seems that the only thing you can change is the mode, not other configs.

Also using `.otrc` file requires manual input, right?

**Comment by jpmens** [comment]
The otrc file is opened with the app.

**Comment by terrytw** [comment]
So I guess what I wanted to do is not feasible. 

The best ways to archive this is probably either allow otr_httpobject to pass nested table, or allow automation tool like tasker to modify detailed configs.

If the team's interest does not lie in either of these, please feel free to close this issue as not planned.
