### ISSUE TITLE
Out-of-order polyline points

### ISSUE THREAD

**Issue by tuukka** [owntracks/recorder#52]
If for some reason location messages don't arrive to Recorder in the order of their timestamps, then Recorder also serves them out-of-order in the polyline API etc. I think that Recorder should either store the messages ordered by timestamp or sort them before building the polyline.

**Comment by jpmens** [comment]
We store messages in the order they're received from the broker so, yes, this can happen. I'll think about how to sort by `tst` on creating GeoJSON.

**Comment by jpmens** [comment]
@tuukka I would appreciate you testing this.

**Comment by tuukka** [comment]
Hmm, didn't seem to work right away, but I'll look closer what's going on in my data.
