### ISSUE TITLE
Logging of mqtt conn request optional

### ISSUE THREAD

**Issue by przemas75** [owntracks/recorder#62]
Can you make this requests logging optional, please?

2015-09-21 version 0.4.0
- FIX: recorder logs MQTT connection request

I believe this is the commit: https://github.com/owntracks/recorder/commit/e4a09ca5e5968cc742fcb6466e7540c653961877

What is the reason anyway for having this?

edit:  i mean, this block
https://github.com/owntracks/recorder/blob/master/recorder.c#L1495
It fills syslog very frequent.

**Comment by jpmens** [comment]
If you are getting that frequently it means the recorder is being disconnected from your broker frequently; I think you should check what is happening on the broker side.

**Comment by przemas75** [comment]
Thanks for idea, it was right direction however with my broker was everything fine.
It turned out, i have configured ot-recorder to be started by systemd and also i was starting it manually.
Log was filled by ot-recorder from systemd (as a second instance).

Now, it is only  started by systemd and looks good.

Your soft is awesome!

**Comment by jpmens** [comment]
You understand the reason why that was happening? The Recorder was connecting with identical clientids, and a broker MUST kick out duplicates; hence the disconnections. Glad it's working for you now.
