### ISSUE TITLE
Unable to install on Ubuntu 15.10

### ISSUE THREAD

**Issue by dazzag24** [owntracks/recorder#63]
Hi,

Following the Readme.md instructions I headed off to https://packagecloud.io/owntracks/ot-recorder in order to install from a package.

However they don't work.  apt-get is unable to find the ot-recorder package:

$ curl -s https://packagecloud.io/install/repositories/owntracks/ot-recorder/script.deb.sh | sudo bash
[sudo] password for xxxxxx: 
Detected operating system as Ubuntu/wily.
Checking for curl...
Detected curl...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/owntracks_ot-recorder.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

$ sudo apt-get install ot-recorder=0.3.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ot-recorder

Next I tried to force it to use the trusty packages.  This also fails:

$ os=ubuntu dist=trusty sudo -E ./script.deb.sh 
Detected operating system as ubuntu/trusty.
Checking for curl...
Detected curl...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/owntracks_ot-recorder.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
$ sudo apt-get install ot-recorder=0.3.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ot-recorder

Please provide a working set of instructions for ubuntu.

Thanks

**Comment by jpmens** [comment]
That package is for Debian/Jessie and not for Ubuntu. We currently don't have packages for Ubuntu. Actually to be honest, we don't have any current packages -- those are still on our todo list and we need help doing that for all platforms.

**Comment by dazzag24** [comment]
OK thanks.

The packageio system appears to work and doesn't specifically state that it doesn't have support.  Ubuntu is a very popular distrobution including among hosted VM providers, so I would have thought this was a priority.

What exactly is required to do this.....?

**Comment by jpmens** [comment]
Well, it's a priority if you use Ubuntu, right? And unfortunately we don't. Actually we always build directly from source for our machines ...

What is required is ability to create package descriptions and a machine on which to build them. Preferably some sort of build farm which would do Ubuntu, Debian, Raspbian, etc.

**Comment by dazzag24** [comment]
Keen to help in anyway I can, but I don't have access to a build farm I'm afraid ;-(

**Comment by dazzag24** [comment]
I'm also happy to build from source myself, but my first attempt failed with errors.  (This was on another 14.04 LTS machine and I will try again and see what the errors were tonight.)   However my desire for packages and clear instructions is because I think it would help drive wider adoption.   Not everyone is happy with compiling from source.

**Comment by jpmens** [comment]
Please show us which errors you got (paste here between two lines each containing three backticks ` so formatting is kept) and we'll try and help as best we can.

**Comment by dazzag24** [comment]
I think that the function signatures provided by the Ubuntu 14.04 libmosquitto package differ from those used in recorder.c.   I should point out that there is no "libmosquitto-dev" package on 14.04, but there IS a "libmosquitto0-dev" package that provides the /usr/include/mosquitto.h file.

cc -Wall -Werror -I/usr/include -DGHASHPREC=7 -DWITH_PING=1 -DWITH_LMDB=1 -Imdb/ -DWITH_HTTP=1 -DJSON_INDENT=NULL -DSTORAGEDEFAULT=\"/var/spool/owntrack
s/recorder/store\" -DDOCROOT=\"/var/spool/owntracks/recorder/htdocs\"   -c -o recorder.o recorder.c
recorder.c: In function ‘republish’:
recorder.c:208:33: error: pointer targets in passing argument 5 of ‘mosquitto_publish’ differ in signedness [-Werror=pointer-sign]
                                 strlen(payload), payload, 1, true);
                                 ^
In file included from recorder.c:30:0:
/usr/include/mosquitto.h:395:20: note: expected ‘const uint8_t *’ but argument is of type ‘char *’
 libmosq_EXPORT int mosquitto_publish(struct mosquitto *mosq, uint16_t *mid, const char *topic, uint32_t payloadlen, const uint8_t *payload, int qos, bool retain);
                    ^
recorder.c: In function ‘on_message’:
recorder.c:518:9: error: implicit declaration of function ‘mosquitto_sub_topic_tokenise’ [-Werror=implicit-function-declaration]
         if (mosquitto_sub_topic_tokenise(m->topic, &topics, &count) != MOSQ_ERR_SUCCESS) {
         ^
recorder.c:534:3: error: implicit declaration of function ‘mosquitto_sub_topic_tokens_free’ [-Werror=implicit-function-declaration]
   mosquitto_sub_topic_tokens_free(&topics, count);
   ^
recorder.c:575:2: error: pointer targets in passing argument 1 of ‘json_decode’ differ in signedness [-Werror=pointer-sign]
  if ((json = json_decode(m->payload)) == NULL) {
  ^
In file included from recorder.c:34:0:
json.h:71:13: note: expected ‘const char *’ but argument is of type ‘uint8_t * const’
 JsonNode   *json_decode         (const char *json);
             ^
recorder.c:576:3: error: pointer targets in passing argument 1 of ‘csv_to_json’ differ in signedness [-Werror=pointer-sign]
   if ((json = csv_to_json(m->payload)) == NULL) {
   ^
recorder.c:256:11: note: expected ‘char *’ but argument is of type ‘uint8_t * const’
 JsonNode *csv_to_json(char *payload)
           ^
recorder.c:589:4: error: pointer targets in passing argument 1 of ‘bindump’ differ in signedness [-Werror=pointer-sign]
    putrec(ud, now, reltopic, username, device, bindump(m->payload, m->payloadlen));
    ^
In file included from recorder.c:41:0:
misc.h:15:7: note: expected ‘char *’ but argument is of type ‘uint8_t * const’
 char *bindump(char *buf, long buflen);
       ^
recorder.c:677:5: error: pointer targets in passing argument 1 of ‘bindump’ differ in signedness [-Werror=pointer-sign]
     putrec(ud, now, reltopic, username, device, bindump(m->payload, m->payloadlen));
     ^
In file included from recorder.c:41:0:
misc.h:15:7: note: expected ‘char *’ but argument is of type ‘uint8_t * const’
 char *bindump(char *buf, long buflen);
       ^
recorder.c:681:4: error: pointer targets in passing argument 4 of ‘waypoints_dump’ differ in signedness [-Werror=pointer-sign]
    waypoints_dump(ud, username, device, m->payload);
   ^
recorder.c:393:6: note: expected ‘char *’ but argument is of type ‘uint8_t * const’
 void waypoints_dump(struct udata *ud, UT_string *username, UT_string *device, char *payloadstring)
      ^
recorder.c:684:4: error: pointer targets in passing argument 4 of ‘config_dump’ differ in signedness [-Werror=pointer-sign]
    config_dump(ud, username, device, m->payload);
    ^
recorder.c:374:6: note: expected ‘char *’ but argument is of type ‘uint8_t * const’
 void config_dump(struct udata *ud, UT_string *username, UT_string *device, char *payloadstring)
      ^
recorder.c:692:5: error: pointer targets in passing argument 1 of ‘bindump’ differ in signedness [-Werror=pointer-sign]
     putrec(ud, now, reltopic, username, device, bindump(m->payload, m->payloadlen));
     ^
In file included from recorder.c:41:0:
misc.h:15:7: note: expected ‘char *’ but argument is of type ‘uint8_t * const’
 char *bindump(char *buf, long buflen);
       ^
recorder.c:720:3: error: pointer targets in passing argument 1 of ‘bindump’ differ in signedness [-Werror=pointer-sign]
   olog(LOG_ERR, "lat or lon for %s are NaN: %s", m->topic, bindump(m->payload, m->payloadlen));
   ^
In file included from recorder.c:41:0:
misc.h:15:7: note: expected ‘char *’ but argument is of type ‘uint8_t * const’
 char *bindump(char *buf, long buflen);
       ^
recorder.c: In function ‘on_connect’:
recorder.c:950:4: error: passing argument 2 of ‘mosquitto_subscribe’ from incompatible pointer type [-Werror]
    mosquitto_subscribe(mosq, &mid, t->string_, ud->qos);
    ^
In file included from recorder.c:30:0:
/usr/include/mosquitto.h:417:20: note: expected ‘uint16_t *’ but argument is of type ‘int *’
 libmosq_EXPORT int mosquitto_subscribe(struct mosquitto *mosq, uint16_t *mid, const char *sub, int qos);
                    ^
recorder.c: In function ‘main’:
recorder.c:1377:2: error: too many arguments to function ‘mosquitto_new’
  mosq = mosquitto_new(UB(clientid), CLEAN_SESSION, (void *)&udata);
  ^
In file included from recorder.c:30:0:
/usr/include/mosquitto.h:196:34: note: declared here
 libmosq_EXPORT struct mosquitto *mosquitto_new(const char *id, void *obj);
                                  ^
recorder.c:1393:2: error: implicit declaration of function ‘mosquitto_reconnect_delay_set’ [-Werror=implicit-function-declaration]
  mosquitto_reconnect_delay_set(mosq,
  ^
recorder.c:1398:2: error: passing argument 2 of ‘mosquitto_message_callback_set’ from incompatible pointer type [-Werror]
  mosquitto_message_callback_set(mosq, on_message);
  ^
In file included from recorder.c:30:0:
/usr/include/mosquitto.h:673:21: note: expected ‘void (*)(void *, const struct mosquitto_message *)’ but argument is of type ‘void (*)(struct mosquitto 
*, void *, const struct mosquitto_message *)’
 libmosq_EXPORT void mosquitto_message_callback_set(struct mosquitto *mosq, void (*on_message)(void *, const struct mosquitto_message *));
                     ^
recorder.c:1399:2: error: passing argument 2 of ‘mosquitto_connect_callback_set’ from incompatible pointer type [-Werror]
  mosquitto_connect_callback_set(mosq, on_connect);
  ^
In file included from recorder.c:30:0:
/usr/include/mosquitto.h:618:21: note: expected ‘void (*)(void *, int)’ but argument is of type ‘void (*)(struct mosquitto *, void *, int)’
 libmosq_EXPORT void mosquitto_connect_callback_set(struct mosquitto *mosq, void (*on_connect)(void *, int));
                     ^
recorder.c:1400:2: error: passing argument 2 of ‘mosquitto_disconnect_callback_set’ from incompatible pointer type [-Werror]
  mosquitto_disconnect_callback_set(mosq, on_disconnect);
  ^
In file included from recorder.c:30:0:
/usr/include/mosquitto.h:634:21: note: expected ‘void (*)(void *)’ but argument is of type ‘void (*)(struct mosquitto *, void *, int)’
 libmosq_EXPORT void mosquitto_disconnect_callback_set(struct mosquitto *mosq, void (*on_disconnect)(void *));
                     ^
recorder.c:1410:17: error: implicit declaration of function ‘mosquitto_tls_set’ [-Werror=implicit-function-declaration]
                 rc = mosquitto_tls_set(mosq,
                 ^
recorder.c:1419:33: error: implicit declaration of function ‘mosquitto_strerror’ [-Werror=implicit-function-declaration]
                                 mosquitto_strerror(rc));
                                 ^
recorder.c:1419:33: error: format ‘%s’ expects argument of type ‘char *’, but argument 3 has type ‘int’ [-Werror=format=]
recorder.c:1423:17: error: implicit declaration of function ‘mosquitto_tls_opts_set’ [-Werror=implicit-function-declaration]
                 mosquitto_tls_opts_set(mosq,
                 ^
recorder.c:1440:2: error: too few arguments to function ‘mosquitto_connect’
  rc = mosquitto_connect(mosq, hostname, port, 60);
  ^
In file included from recorder.c:30:0:
/usr/include/mosquitto.h:322:20: note: declared here
 libmosq_EXPORT int mosquitto_connect(struct mosquitto *mosq, const char *host, int port, int keepalive, bool clean_session);
                    ^
recorder.c:1447:5: error: format ‘%s’ expects argument of type ‘char *’, but argument 4 has type ‘int’ [-Werror=format=]
     rc, mosquitto_strerror(rc), mosquitto_reason(rc));
     ^
recorder.c:1492:3: error: too many arguments to function ‘mosquitto_loop’
   rc = mosquitto_loop(mosq, loop_timeout, /* max-packets */ 1);
   ^
In file included from recorder.c:30:0:
/usr/include/mosquitto.h:503:20: note: declared here
 libmosq_EXPORT int mosquitto_loop(struct mosquitto *mosq, int timeout);
                    ^
cc1: all warnings being treated as errors
make: *** [recorder.o] Error 1

**Comment by jpmens** [comment]
I assume (but don't know for sure and can't check now) that Ubuntu is still shipping an ancient library and broker. Do yourself a favor and get Mosquitto and libraries from the PPA provided by the Mosquitto project at [http://mosquitto.org](http://mosquitto.org) under Downloads/

**Comment by dazzag24** [comment]
I can confirm that using the package from mosquitto.org I was able to build it.

sudo apt-add-repository ppa:mosquitto-dev/mosquitto-ppa
sudo apt-get update
sudo apt-get install libmosquitto-dev

I've no idea why Ubuntu 14.04 LTS uses such an out of date version.   On my work 15.10 box I didn't have this issue, but I think it worth documenting the above on your Readme.md as plenty of people use 14.04 due to the long term support.
