### ISSUE TITLE
Better instructions for required dependencies for the make option

### ISSUE THREAD

**Issue by dazzag24** [owntracks/recorder#64]
When compiling from source on Ubuntu it would be great if you could clearly define what apt-get packages are required.

On 15.10 I think this is what I needed in order to compile successfully:

sudo apt-get install libcurl3 libmosquitto1 liblmdb0 libmosquitto-dev libcurl4-openssl-dev

Note that I am not sure if these are correct.  There are version 3 and version 4 curl packages available not to mention the 3 different flavours of -dev that could be chosen.

**Comment by jpmens** [comment]
You do not need liblmdb0 as we provide the source of that.
Other than that, I think your list covers it. If you confirm that later, I'll gladly add it to the README (or better yet: you submit a PR for that documentation. :-)
