### ISSUE TITLE
Support for Proxy servers?

### ISSUE THREAD

**Issue by dazzag24** [owntracks/recorder#65]
When running behind a corporate http proxy the recorder fails to connect.

$ sudo -E ./hosted.sh
ot-recorder[20417]: starting
ot-recorder[20417]: connecting to Hosted as clientID ot-RECORDER-xxxxxx-Phone-zzzzzz
Error: Connection timed out

Not sure what our options are here.   Note the "sudo -E" invokation, to make sudo inherit environment variables from current user, including http_proxy and https_proxy.

**Comment by jpmens** [comment]
You are trying to proxy MQTT over an HTTP proxy? Good luck with that!
Honestly, how is that supposed to work?

**Comment by dazzag24** [comment]
Well from your response I sense that it isn't supposed to work.  From the perspective of a slightly less technical user, why do you think it would be obvious that it wouldn't work.   I don't think I've seen any where in the docs where this is explicitly stated.

I'll have to try again on a machine not behind a proxy.

**Comment by jpmens** [comment]
I wasn't under the impression that you were a "slightly less technical user", so I apologize if I was snarky.

The MQTT protocol is not designed to be transported via an HTTP proxy server. Whilst it may be possible to use, say, a SOCKS proxy, we don't have support for that in the Recorder. The point is, the Recorder needs a direct TCP connection to your MQTT broker, be in on (standard) port 1883 or, if using TLS, on port 8883. If you are behind a firewall, the Recorder must be able to reach its broker on the appropriate TCP port provided by the MQTT broker (outgoing connection).
