### ISSUE TITLE
TLS PSK support

### ISSUE THREAD

**Issue by jpmens** [owntracks/recorder#74]

**Comment by jshridha** [comment]
+1 this would be awesome!

**Comment by jpmens** [comment]
What will you use it for?

**Comment by jshridha** [comment]
Currently my owntracks mqtt is secured with TLS and private keys for each user. I cannot get ot-recorder to connect to unless I turn off the certificate requirement: `require_certificate false` in mosquitto.conf

**Comment by jpmens** [comment]
TLS PSK has nothing to do with client certificates.

**Comment by jshridha** [comment]
Sorry, my mistake. Thanks for opening up a new issue for this.
