### ISSUE TITLE
Cannot set TLS CA: Invalid function arguments provided. (check path names)

### ISSUE THREAD

**Issue by ralin3** [owntracks/recorder#80]
if I have a file with:
#!/bin/sh
export OTR_PASS="<password>"
export OTR_CAFILE="/etc/mosquitto/certs/ca.crt"

/usr/local/sbin/ot-recorder -H localhost -p 8883 --norec --http-host 10.0.1.23 --clientid otrecorder --debug "owntracks/#"

And I run it as root, I only get:
./ot-stuff
ot-recorder[17502]: starting
Cannot set TLS CA: Invalid function arguments provided. (check path names)

The path is correct, it's the same used by mosquitto, and the crt is the same as used to my successfully reporting clients.

Not saying this is a bug, but I'm so stuck I'm starting to distrust my own existence.

This is the deb-package, version 0.4.8.
Running on Debian Jessie.

**Comment by jpmens** [comment]
The `ot-recorder` binary from the Debian package runs suid `owntracks` which means your `ca.crt` file must be readable for user `owntracks`.

I suggest you copy `ca.crt` to a different location and change its permissions accordingly.

**Comment by ralin3** [comment]
Yup, that's correct.
That's how it is when you bang your head to the wall too long.
