### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by wunderbaum** [owntracks/recorder#85]
Cannot compile this version:
``recorder.c: In function 'main':
recorder.c:1274:6: error: variable 'loop_timeout' set but not used [-Werror=unused-but-set-variable]
  int loop_timeout = 0;
      ^
cc1: all warnings being treated as errors
``

**Comment by jpmens** [comment]
Please say which OS/version you're compiling on, and show `config.mk` you've used.

**Comment by jpmens** [comment]
FWIW you seem to have compiled `WITH_MQTT = no`; I hope you know what you're doing? ;-)
