### ISSUE TITLE
Allow view to specify past interval

### ISSUE THREAD

**Issue by jpmens** [owntracks/recorder#99]
Currently we have `from` / `to` which default to `-6h` / `now`.
Allow something like `hours` which overrides the above, e.g. for ISS feed

**Comment by juzam** [comment]
ha! so you have a weak spot for the ISS ;)

**Comment by jpmens** [comment]
Which is your fault, IIRC? ;-)

**Comment by juzam** [comment]
@jpmens Indeed ;) I was almost too easy to set up the tracking via Owntracks, thanks again for all the time you put into this gem of a software.
